// re2c $INPUT -o $OUTPUT
/*!re2c
    :api = simple;
    :api = record;
    :api = generic;
    :api = custom; // deprecated alias
    :api = default; // deprecated alias
    re2c:api = generic;
    re2c:flags:input = generic;
    :api:style = free-form;
    re2c:api:style = free-form;
    :api:sigil = "";
    re2c:api:sigil = "";

    :header = "all_configs.h";
    re2c:header = "all_configs.h";
    re2c:flags:type-header = "all_configs.h";
    re2c:flags:t = "all_configs.h";

    :eof = -1;
    re2c:eof = -1;
    :sentinel = 0;
    re2c:sentinel = 0;

    :yyfill:enable = 0;
    re2c:yyfill:enable = 0;
    :yyfill:parameter = 0;
    re2c:yyfill:parameter = 0;
    :yyfill:check = 0;
    re2c:yyfill:check = 0;

    :tags = 0;
    re2c:tags = 0;
    re2c:flags:tags = 0;
    re2c:flags:T = 0;
    :captures = 0;
    re2c:captures = 0;
    :leftmost-captures = 0;
    re2c:leftmost-captures = 0;
    :posix-captures = 0;
    re2c:posix-captures = 0;
    re2c:flags:posix-captures = 0;
    re2c:flags:P = 0;
    :invert-captures = 0;
    re2c:invert-captures = 0;
    :tags:prefix = "";
    re2c:tags:prefix = "";
    :tags:expression = "";
    re2c:tags:expression = "";
    :tags:negative = "";
    re2c:tags:negative = "";

    re2c:yyfn:sep = ";";

    :YYBACKUP = "";
    re2c:define:YYBACKUP = "";
    :YYBACKUPCTX = "";
    re2c:define:YYBACKUPCTX = "";
    :YYCONDTYPE = "";
    re2c:define:YYCONDTYPE = "";
    :YYCTYPE = "";
    re2c:define:YYCTYPE = "";
    :YYCTXMARKER = "";
    re2c:define:YYCTXMARKER = "";
    :YYCURSOR = "";
    re2c:define:YYCURSOR = "";
    :YYDEBUG = "";
    re2c:define:YYDEBUG = "";
    :YYFILL = "";
    re2c:define:YYFILL = "";
    re2c:define:YYFILL@len = "";
    re2c:define:YYFILL:naked = 0;
    :YYFN = ["name;type"];
    re2c:define:YYFN = ["name;type"];
    :YYGETCOND = "";
    re2c:define:YYGETCOND = "";
    re2c:define:YYGETCOND:naked = 0;
    re2c:define:YYGETCONDITION = ""; // deprecated
    re2c:define:YYGETCONDITION:naked = 0; // deprecated
    :YYGETSTATE = "";
    re2c:define:YYGETSTATE = "";
    :YYGETSTATE:naked = 0;
    re2c:define:YYGETSTATE:naked = 0;
    :YYINPUT = "";
    re2c:define:YYINPUT = "";
    :YYLESSTHAN = "";
    re2c:define:YYLESSTHAN = "";
    :YYLIMIT = "";
    re2c:define:YYLIMIT = "";
    :YYMARKER = "";
    re2c:define:YYMARKER = "";
    :YYMTAGN = "";
    re2c:define:YYMTAGN = "";
    :YYMTAGP = "";
    re2c:define:YYMTAGP = "";
    :YYPEEK = "";
    re2c:define:YYPEEK = "";
    :YYRESTORE = "";
    re2c:define:YYRESTORE = "";
    :YYRESTORECTX = "";
    re2c:define:YYRESTORECTX = "";
    :YYRESTORETAG = "";
    re2c:define:YYRESTORETAG = "";
    :YYSETCOND = "";
    re2c:define:YYSETCOND = "";
    re2c:define:YYSETCOND@cond = "";
    re2c:define:YYSETCOND:naked = 0;
    re2c:define:YYSETCONDITION = ""; // deprecated
    re2c:define:YYSETCONDITION@cond = ""; // deprecated
    re2c:define:YYSETCONDITION:naked = 0; // deprecated
    :YYSETSTATE = "";
    re2c:define:YYSETSTATE = "";
    re2c:define:YYSETSTATE:naked = 0;
    re2c:define:YYSETSTATE@state = "";
    :YYSHIFT = "";
    re2c:define:YYSHIFT = "";
    :YYSHIFTSTAG = "";
    re2c:define:YYSHIFTSTAG = "";
    :YYSHIFTMTAG = "";
    re2c:define:YYSHIFTMTAG = "";
    :YYSKIP = "";
    re2c:define:YYSKIP = "";
    :YYSTAGN = "";
    re2c:define:YYSTAGN = "";
    :YYSTAGP = "";
    re2c:define:YYSTAGP = "";

    :yycond = "";
    re2c:variable:yycond = "";
    :yyctable = "";
    re2c:variable:yyctable = "";
    :yyaccept = "";
    re2c:variable:yyaccept = "";
    :yytarget = "";
    re2c:variable:yytarget = "";
    :yystate = "";
    re2c:variable:yystate = "";
    :yynmatch = "";
    re2c:variable:yynmatch = "";
    :yypmatch = "";
    re2c:variable:yypmatch = "";
    :yyrecord = "";
    re2c:variable:yyrecord = "";
    :yych = "";
    re2c:variable:yych = "";
    :yych:conversion = 0;
    re2c:variable:yych:conversion = 0;
    :yych:emit = 0;
    re2c:variable:yych:emit = 0;
    :yybm = "";
    re2c:variable:yybm = "";
    :yybm:hex = 0;
    re2c:variable:yybm:hex = 0;
    :yyfill = "";
    re2c:variable:yyfill = "";
    :yystable = "";
    re2c:variable:yystable = "";

    :cond:prefix = "";
    re2c:cond:prefix = "";
    re2c:condprefix = "";
    :cond:enumprefix = "";
    re2c:cond:enumprefix = "";
    re2c:condenumprefix = "";
    :cond:divider = "";
    re2c:cond:divider = "";
    re2c:cond:divider@cond = "";
    :cond:goto = "";
    re2c:cond:goto = "";
    re2c:cond:goto@cond = "";

    :state:abort = 0;
    re2c:state:abort = 0;
    :state:nextlabel = 0;
    re2c:state:nextlabel = 0;

    :bit-vectors = 0;
    re2c:bit-vectors = 0;
    re2c:flags:bit-vectors = 0;
    re2c:flags:b = 0;
    :debug-output = 0;
    re2c:debug-output = 0;
    re2c:flags:debug-output = 0;
    re2c:flags:d = 0;
    :computed-gotos = 0;
    re2c:computed-gotos = 0;
    re2c:flags:computed-gotos = 0;
    re2c:flags:g = 0;
    :computed-gotos:threshold = 0;
    re2c:computed-gotos:threshold = 0;
    re2c:cgoto:threshold = 0;
    :nested-ifs = 0;
    re2c:nested-ifs = 0;
    re2c:flags:nested-ifs = 0;
    re2c:flags:s = 0;
    :case-insensitive = 0;
    re2c:case-insensitive = 0;
    re2c:flags:case-insensitive = 0;
    :case-inverted = 0;
    re2c:case-inverted = 0;
    re2c:flags:case-inverted = 0;
    :case-ranges = 0;
    re2c:case-ranges = 0;
    re2c:flags:case-ranges = 0;
    // :unsafe = 0; // unsupported for C backend
    // :monadic = 0; // unsupported for C backend

    :encoding:ebcdic = 0;
    re2c:encoding:ebcdic = 0;
    re2c:flags:ecb = 0;
    re2c:flags:e = 0;
    :encoding:utf32 = 0;
    re2c:encoding:utf32 = 0;
    re2c:flags:unicode = 0;
    re2c:flags:u = 0;
    :encoding:ucs2 = 0;
    re2c:encoding:ucs2 = 0;
    re2c:flags:wide-chars = 0;
    re2c:flags:w = 0;
    :encoding:utf16 = 0;
    re2c:encoding:utf16 = 0;
    re2c:flags:utf-16 = 0;
    re2c:flags:x = 0;
    :encoding:utf8 = 0;
    re2c:encoding:utf8 = 0;
    re2c:flags:utf-8 = 0;
    re2c:flags:8 = 0;

    :encoding-policy = ignore;
    :encoding-policy = substitute;
    :encoding-policy = fail;
    re2c:encoding-policy = fail;
    re2c:flags:encoding-policy = fail;

    :empty-class = match-empty;
    :empty-class = match-none;
    :empty-class = error;
    re2c:empty-class = error;
    re2c:flags:empty-class = error;

    :indent:string = "";
    re2c:indent:string = "";
    :indent:top = 0;
    re2c:indent:top = 0;

    :label:prefix = "";
    re2c:label:prefix = "";
    re2c:labelprefix = "";
    :label:yyfill = "";
    re2c:label:yyfill = "";
    re2c:label:yyFillLabel = "";
    :label:yyloop = "";
    re2c:label:yyloop = "";
    :label:yyNext = "";
    re2c:label:yyNext = "";
    :label:start = "";
    :label:start = 0;
    re2c:label:start = 0;
    re2c:startlabel = 0;
*/
