/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -ci
#include <stdio.h>

enum YYCONDTYPE {
	yycinit,
	yycC2,
};


int test(const char* str)
{
    const unsigned char* YYCURSOR = (const unsigned char*)str;
    const unsigned char* YYMARKER;
    const unsigned char *YYCTXMARKER;
    int c = yycinit;

    
{
	unsigned char yych;
	switch (c) {
	case yycinit:
		goto yyc_init;
	case yycC2:
		goto yyc_C2;
	}
/* *********************************** */
yyc_init:
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':	goto yy4;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
	{ return 0; }
yy4:
	++YYCURSOR;
	c = yycC2;
	goto yyc_C2;
/* *********************************** */
yyc_C2:
	yych = *YYCURSOR;
	switch (yych) {
	case 'B':	goto yy10;
	default:	goto yy8;
	}
yy8:
	++YYCURSOR;
	{ return 0; }
yy10:
	++YYCURSOR;
	{ return 1; }
}

}

int main()
{
    printf("%d\n", test("AB"));
    return 0;
}
