#include "src/parse/conf_parser.h"
const char* DEFAULT_SYNTAX_C =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    ":supported_apis = [\"simple\", \"generic\", \"record\"];\n"
    ":supported_api_styles = [\"functions\", \"free-form\"];\n"
    ":supported_code_models = [\"goto-label\", \"loop-switch\", \"recursive-functions\"];\n"
    ":supported_targets = [\"code\", \"dot\", \"skeleton\"];\n"
    ":supported_features = [\"nested-ifs\", \"bitmaps\", \"computed-gotos\", \"case-ranges\",\n"
    "    \"tags\", \"captures\", \"captvars\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    ":semicolons = 1;\n"
    ":backtick_quoted_strings = 0;\n"
    ":single_quoted_strings = 0;\n"
    ":indentation_sensitive = 0;\n"
    ":wrap_blocks_in_braces = 1;\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    ":target = code;\n"
    ":code-model = goto-label;\n"
    ":input-encoding = ascii;\n"
    ":date = 1;\n"
    ":version = 1;\n"
    ":conditions = 0;\n"
    ":storable-state = 0;\n"
    ":flex-syntax = 0;\n"
    ":verbose = 0;\n"
    ":line-dirs = 1;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    ":api = simple;\n"
    ":api:style = functions;\n"
    ":api:sigil = \"@@\";\n"
    ":YYGETCOND:naked = 0;\n"
    ":YYSETCOND:naked = 0;\n"
    ":YYSETCOND@cond = \"@@\";\n"
    ":YYGETSTATE:naked = 0;\n"
    ":YYSETSTATE:naked = 0;\n"
    ":YYSETSTATE@state = \"@@\";\n"
    ":YYFILL@len = \"@@\";\n"
    ":YYFILL:naked = 0;\n"
    ":YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    ":yyfn:sep = \";\";\n"
    ":yycond = \"yycond\";\n"
    ":yyctable = \"yyctable\";\n"
    ":yyaccept = \"yyaccept\";\n"
    ":yytarget = \"yytarget\";\n"
    ":yystate = \"yystate\";\n"
    ":yynmatch = \"yynmatch\";\n"
    ":yypmatch = \"yypmatch\";\n"
    ":yyrecord = \"yyrecord\";\n"
    ":yych = \"yych\";\n"
    ":yych:conversion = 0;\n"
    ":yych:literals = char-or-hex;\n"
    ":yych:emit = (.code_model.recursive_functions ? 0 : 1);\n"
    ":yybm = \"yybm\";\n"
    ":yybm:hex = 0;\n"
    ":yyfill = \"\";\n"
    ":yystable = \"\"; // deprecated\n"
    ":header = \"\";\n"
    ":eof = -1;\n"
    ":sentinel = -1;\n"
    ":yyfill:enable = 1;\n"
    ":yyfill:parameter = 1;\n"
    ":yyfill:check = 1;\n"
    ":tags = 0;\n"
    ":tags:prefix = \"yyt\";\n"
    ":captures = 0;\n"
    ":captvars = 0;\n"
    ":posix-captures = 0;\n"
    ":posix-captvars = 0;\n"
    ":invert-captures = 0;\n"
    ":cond:abort = (.code_model.recursive_functions ? 1 : 0); // `abort()` requires include\n"
    ":cond:prefix = \"yyc_\";\n"
    ":cond:enumprefix = \"yyc\";\n"
    ":cond:divider@cond = \"@@\";\n"
    ":cond:goto@cond = \"@@\";\n"
    ":state:abort = (.code_model.recursive_functions ? 1 : 0); // `abort()` requires include\n"
    ":state:nextlabel = 0;\n"
    ":bit-vectors = 0;\n"
    ":debug-output = 0;\n"
    ":computed-gotos = 0;\n"
    ":computed-gotos:threshold = 9;\n"
    ":nested-ifs = 0;\n"
    ":case-insensitive = 0;\n"
    ":case-inverted = 0;\n"
    ":case-ranges = 0;\n"
    ":unsafe = 0;\n"
    ":monadic = 0;\n"
    ":encoding:ebcdic = 0;\n"
    ":encoding:utf32 = 0;\n"
    ":encoding:ucs2 = 0;\n"
    ":encoding:utf16 = 0;\n"
    ":encoding:utf8 = 0;\n"
    ":encoding-policy = ignore;\n"
    ":empty-class = match-empty;\n"
    ":indent:string = \"\\t\";\n"
    ":indent:top = 0;\n"
    ":label:prefix = \"yy\";\n"
    ":label:yyfill = \"yyFillLabel\";\n"
    ":label:yyloop = \"\";\n"
    ":label:yyNext = \"yyNext\";\n"
    ":label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    ":YYBACKUP = \"YYBACKUP\";\n"
    ":YYBACKUPCTX = \"YYBACKUPCTX\";\n"
    ":YYCONDTYPE = \"YYCONDTYPE\";\n"
    ":YYCOPYMTAG = sigil \"{lhs} = \" sigil \"{rhs};\";\n"
    ":YYCOPYSTAG = sigil \"{lhs} = \" sigil \"{rhs};\";\n"
    ":YYCTXMARKER = (.api.record ? yyrecord \"->yyctxmarker\" : \"YYCTXMARKER\");\n"
    ":YYCTYPE = \"YYCTYPE\";\n"
    ":YYCURSOR = (.api.record ? yyrecord \"->yycursor\" : \"YYCURSOR\");\n"
    ":YYDEBUG = \"YYDEBUG\";\n"
    ":YYFILL = \"YYFILL\";\n"
    ":YYGETACCEPT = sigil \"{var}\";\n"
    ":YYGETCOND = \"YYGETCONDITION\"; // historic default\n"
    ":YYGETSTATE = \"YYGETSTATE\";\n"
    ":YYINPUT = (.api.record ? yyrecord \"->yyinput\" : \"YYINPUT\");\n"
    ":YYLESSTHAN = \"YYLESSTHAN\";\n"
    ":YYLIMIT = (.api.record ? yyrecord \"->yylimit\" : \"YYLIMIT\");\n"
    ":YYMARKER = (.api.record ? yyrecord \"->yymarker\" : \"YYMARKER\");\n"
    ":YYMAXFILL = \"YYMAXFILL\";\n"
    ":YYMAXNMATCH = \"YYMAXNMATCH\";\n"
    ":YYMTAGN = \"YYMTAGN\";\n"
    ":YYMTAGP = \"YYMTAGP\";\n"
    ":YYPEEK = \"YYPEEK\";\n"
    ":YYRESTORE = \"YYRESTORE\";\n"
    ":YYRESTORECTX = \"YYRESTORECTX\";\n"
    ":YYRESTORETAG = \"YYRESTORETAG\";\n"
    ":YYSETACCEPT = sigil \"{var} = \" sigil \"{val};\";\n"
    ":YYSETCOND = \"YYSETCONDITION\"; // historic default\n"
    ":YYSETSTATE = \"YYSETSTATE\";\n"
    ":YYSHIFT = \"YYSHIFT\";\n"
    ":YYSHIFTSTAG = \"YYSHIFTSTAG\";\n"
    ":YYSHIFTMTAG = \"YYSHIFTMTAG\";\n"
    ":YYSKIP = \"YYSKIP\";\n"
    ":YYSTAGN = \"YYSTAGN\";\n"
    ":YYSTAGP = \"YYSTAGP\";\n"
    ":tags:expression = (.api.record ? yyrecord \"->\") sigil;\n"
    ":tags:negative = (.api.generic ? \"@@\" : \"NULL\");\n"
    ":cond:divider = \"/* *********************************** */\";\n"
    ":cond:goto = \"goto \" sigil \";\";\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "::var_local = topindent type \" \" name (.init ? \" = \" init) \";\" nl;\n"
    "::var_global = ::var_local;\n"
    "\n"
    "::const_local = topindent type \" \" name \" = \" init \";\" nl;\n"
    "::const_global = topindent \"#define \" name \" \" init nl;\n"
    "\n"
    "::array_local =\n"
    "    topindent type \" \" name \"[\" size \"] = {\" nl indent\n"
    "        [row{0:-2}: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "        [row{-1}:   topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem]     nl]\n"
    "    dedent topindent \"};\" nl;\n"
    "\n"
    "::array_global = ::array_local;\n"
    "\n"
    "::array_elem = array \"[\" index \"]\";\n"
    "\n"
    "::enum =\n"
    "    \"enum \" name \" {\" nl indent\n"
    "        [elem{0:-2}: topindent elem (.init ? \" = \" init) \",\" nl]\n"
    "        [elem{-1}:   topindent elem (.init ? \" = \" init) nl]\n"
    "    dedent \"};\" nl;\n"
    "\n"
    "::enum_elem = name;\n"
    "\n"
    "::assign = topindent lhs \" = \" rhs \";\" nl;\n"
    "\n"
    "::type_int = \"int\";\n"
    "::type_uint = \"unsigned int\";\n"
    "::type_cond_enum = <undefined>;\n"
    "::type_yybm = \"static const unsigned char\";\n"
    "::type_yytarget = \"static const void*\";\n"
    "\n"
    "::cmp_eq = \"==\";\n"
    "::cmp_ne = \"!=\";\n"
    "::cmp_lt = \"<\";\n"
    "::cmp_gt = \">\";\n"
    "::cmp_le = \"<=\";\n"
    "::cmp_ge = \">=\";\n"
    "\n"
    "::if_then_else =\n"
    "    [branch{0}: topindent \"if (\" cond \") {\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent \"} else \" (.cond ? \"if (\" cond \") \") \"{\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::if_then_else_oneline =\n"
    "    [branch{0}:    topindent \"if (\" cond \") \" [stmt: stmt] nl]\n"
    "    [branch{1:-1}: topindent \"else \" (.cond ? \"if (\" cond \") \") [stmt: stmt] nl];\n"
    "\n"
    "::switch =\n"
    "    topindent \"switch (\" expr \") {\" nl\n"
    "        indent [case: case] dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::switch_cases =\n"
    "    [case: case nl]\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::switch_cases_oneline =\n"
    "    [case{0:-2}: case nl]\n"
    "    [case{-1}:   case \" \" [stmt: stmt] nl];\n"
    "\n"
    "::switch_case_range = (.case_ranges\n"
    "    ? topindent \"case \" [val{0}: val] (.many ? \" ... \" [val{-1}: val]) \":\"\n"
    "    : [val{0:-2}: topindent \"case \" val \":\" nl]\n"
    "      [val{-1}:   topindent \"case \" val \":\"]);\n"
    "\n"
    "::switch_case_default =\n"
    "    topindent \"default:\";\n"
    "\n"
    "::loop =\n"
    "    topindent \"for (;;) {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::continue = topindent \"continue;\" nl;\n"
    "\n"
    "::goto = topindent \"goto \" label \";\" nl;\n"
    "\n"
    "::fndecl =\n"
    "    topindent type \" \" name \"(\"\n"
    "        [arg{0:-2}: argtype \" \" argname \", \"]\n"
    "        [arg{-1}:   argtype \" \" argname]\n"
    "    \");\" nl;\n"
    "\n"
    "::fndef =\n"
    "    topindent type \" \" name \"(\"\n"
    "        [arg{0:-2}: argtype \" \" argname \", \"]\n"
    "        [arg{-1}:   argtype \" \" argname]\n"
    "    \") {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    \"}\" nl;\n"
    "\n"
    "::fncall =\n"
    "    topindent (.retval ? retval \" = \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \");\" nl;\n"
    "\n"
    "::tailcall =\n"
    "    topindent (.retval ? \"return \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \");\" nl;\n"
    "\n"
    "::recursive_functions =\n"
    "    [fn: fndecl] nl\n"
    "    [fn: fndef nl];\n"
    "\n"
    "::fingerprint =\n"
    "    \"/* Generated by re2c\" (.version ? \" \" version) (.date ? \" on \" date) \" */\" nl;\n"
    "\n"
    "::line_info = \"#line \" line \" \\\"\" file \"\\\"\" nl;\n"
    "\n"
    "::abort = topindent \"abort();\" nl;\n"
    "\n"
    "::yydebug =\n"
    "    topindent (.api.generic\n"
    "        ? YYDEBUG (.api_style.functions ? \"();\")\n"
    "    : (.api.record\n"
    "        ? YYDEBUG \"(\" yyrecord \");\"\n"
    "        : YYDEBUG \"(\" state \", \" yych \");\"\n"
    "    )) nl;\n"
    "\n"
    "::yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \" (.api.generic\n"
    "        ? YYPEEK (.api_style.functions ? \"()\")\n"
    "        : (.cast ? \"(\" YYCTYPE \")\") \"*\" YYCURSOR\n"
    "    ) \";\" nl;\n"
    "\n"
    "::yyskip =\n"
    "    topindent (.api.generic\n"
    "        ? YYSKIP (.api_style.functions ? \"();\")\n"
    "        : \"++\" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yybackup =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUP (.api_style.functions ? \"();\")\n"
    "        : YYMARKER \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yybackupctx =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUPCTX (.api_style.functions ? \"();\")\n"
    "        : YYCTXMARKER \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyskip_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*++\" YYCURSOR \";\" nl;\n"
    "\n"
    "::yypeek_yyskip =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*\" YYCURSOR \"++;\" nl;\n"
    "\n"
    "::yyskip_yybackup =\n"
    "    topindent YYMARKER \" = ++\" YYCURSOR \";\" nl;\n"
    "\n"
    "::yybackup_yyskip =\n"
    "    topindent YYMARKER \" = \" YYCURSOR \"++;\" nl;\n"
    "\n"
    "::yybackup_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = \" YYCURSOR \");\" nl;\n"
    "\n"
    "::yyskip_yybackup_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = ++\" YYCURSOR \");\" nl;\n"
    "\n"
    "::yybackup_yypeek_yyskip =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = \" YYCURSOR \"++);\" nl;\n"
    "\n"
    "::yyrestore =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORE (.api_style.functions ? \"();\")\n"
    "        : YYCURSOR \" = \" YYMARKER \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyrestorectx =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORECTX (.api_style.functions ? \"();\")\n"
    "        : YYCURSOR \" = \" YYCTXMARKER \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyrestoretag =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORETAG (.api_style.functions ? \"(\" tag \");\")\n"
    "        : YYCURSOR \" = \" tag \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyshift =\n"
    "    topindent (.api.generic\n"
    "        ? YYSHIFT (.api_style.functions ? \"(-\" offset \");\")\n"
    "        : YYCURSOR \" -= \" offset \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftstag =\n"
    "    topindent (.nested ? \"if (\" tag \" != \" neg \") \") (.api.generic\n"
    "        ? YYSHIFTSTAG (.api_style.functions ? \"(\" tag \", -\" offset \");\")\n"
    "        : tag \" -= \" offset \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG (.api_style.functions ? \"(\" tag \", -\" offset \");\") nl;\n"
    "\n"
    "::yystagp =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGP (.api_style.functions ? \"(\" tag \");\")\n"
    "        : tag \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yymtagp =\n"
    "    topindent YYMTAGP (.api_style.functions ? \"(\" tag \");\") nl;\n"
    "\n"
    "::yystagn =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGN (.api_style.functions ? \"(\" tag \");\")\n"
    "        : tag \" = \" neg \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yymtagn =\n"
    "    topindent YYMTAGN (.api_style.functions ? \"(\" tag \");\") nl;\n"
    "\n"
    "::yycopystag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYSTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yycopymtag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYMTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yygetaccept =\n"
    "    (.api.generic\n"
    "        ? YYGETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \"->\") var);\n"
    "\n"
    "::yysetaccept =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \"->\")\n"
    "            var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "// Historically simple API did not provide default definition for YYGETCOND.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yycond` that re2c is unable to see, e.g. included from a header file.\n"
    "::yygetcond =\n"
    "    (.api.generic | .api.simple\n"
    "        ? YYGETCOND (.api_style.functions ? \"()\")\n"
    "        : yyrecord \"->\" var);\n"
    "\n"
    "// Historically simple API did not provide default definition for YYSETCOND.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yycond` that re2c is unable to see, e.g. included from a header file.\n"
    "::yysetcond =\n"
    "    topindent (.api.generic | .api.simple\n"
    "        ? YYSETCOND (.api_style.functions ? \"(\" val \");\")\n"
    "        : yyrecord \"->\" var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "// Historically simple API did not provide default definition for YYGETSTATE.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yystate` that re2c is unable to see, e.g. included from a header file.\n"
    "::yygetstate =\n"
    "    (.api.generic | .api.simple\n"
    "        ? YYGETSTATE (.api_style.functions ? \"()\")\n"
    "        : yyrecord \"->\" var);\n"
    "\n"
    "// Historically simple API did not provide default definition for YYSETSTATE.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yystate` that re2c is unable to see, e.g. included from a header file.\n"
    "::yysetstate =\n"
    "    topindent (.api.generic | .api.simple\n"
    "        ? YYSETSTATE (.api_style.functions ? \"(\" val \");\")\n"
    "        : yyrecord \"->\" var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "::yylessthan =\n"
    "    (.api.generic\n"
    "        ? YYLESSTHAN (.api_style.functions ? \"(\" need \")\")\n"
    "        : (.many\n"
    "            ? \"(\" YYLIMIT \" - \" YYCURSOR \") < \" need\n"
    "            : YYLIMIT \" <= \" YYCURSOR));\n"
    "\n"
    "::yybm_filter = yych \" & ~0xFF\";\n"
    "\n"
    "::yybm_match = yybm \"[\" offset \"+\" yych \"] & \" mask;\n"
    ;
