#include "src/parse/conf_parser.h"
const char* DEFAULT_SYNTAX_OCAML =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    ":supported_apis = [\"record\", \"generic\"];\n"
    ":supported_api_styles = [\"free-form\"];\n"
    ":supported_code_models = [\"recursive-functions\"];\n"
    ":supported_targets = [\"code\", \"dot\"];\n"
    ":supported_features = [\"nested-ifs\", \"bitmaps\", \"case-ranges\",\n"
    "    \"tags\", \"captures\", \"captvars\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    ":semicolons = 0;\n"
    ":backtick_quoted_strings = 0;\n"
    ":single_quoted_strings = 0;\n"
    ":indentation_sensitive = 0;\n"
    ":wrap_blocks_in_braces = 0;\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    ":target = code;\n"
    ":code-model = recursive-functions;\n"
    ":input-encoding = ascii;\n"
    ":date = 1;\n"
    ":version = 1;\n"
    ":conditions = 0;\n"
    ":storable-state = 0;\n"
    ":flex-syntax = 0;\n"
    ":verbose = 0;\n"
    ":line-dirs = 1;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    ":api = record;\n"
    ":api:style = free-form;\n"
    ":api:sigil = \"@@\";\n"
    ":YYGETCOND:naked = 0;\n"
    ":YYSETCOND:naked = 0;\n"
    ":YYSETCOND@cond = \"@@\";\n"
    ":YYGETSTATE:naked = 0;\n"
    ":YYSETSTATE:naked = 0;\n"
    ":YYSETSTATE@state = \"@@\";\n"
    ":YYFILL@len = \"@@\";\n"
    ":YYFILL:naked = 0;\n"
    ":YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    ":yyfn:sep = \";\";\n"
    ":yycond = \"yycond\";\n"
    ":yyctable = \"yyctable\";\n"
    ":yyaccept = \"yyaccept\";\n"
    ":yytarget = \"yytarget\";\n"
    ":yystate = \"yystate\";\n"
    ":yynmatch = \"yynmatch\";\n"
    ":yypmatch = \"yypmatch\";\n"
    ":yyrecord = \"yyrecord\";\n"
    ":yych = \"yych\";\n"
    ":yych:conversion = 0;\n"
    ":yych:literals = char;\n"
    ":yych:emit = (.code_model.recursive_functions ? 0 : 1);\n"
    ":yybm = \"yybm\";\n"
    ":yybm:hex = 0;\n"
    ":yyfill = \"\";\n"
    ":yystable = \"\"; // deprecated\n"
    ":header = \"\";\n"
    ":eof = -1;\n"
    ":sentinel = -1;\n"
    ":yyfill:enable = 1;\n"
    ":yyfill:parameter = 1;\n"
    ":yyfill:check = 1;\n"
    ":tags = 0;\n"
    ":tags:prefix = \"yyt\";\n"
    ":captures = 0;\n"
    ":captvars = 0;\n"
    ":posix-captures = 0;\n"
    ":posix-captvars = 0;\n"
    ":invert-captures = 0;\n"
    ":cond:abort = 0; // default case causes [redundant-case] warnings\n"
    ":cond:prefix = \"yyc_\";\n"
    ":cond:enumprefix = \"YYC_\";\n"
    ":cond:divider@cond = \"@@\";\n"
    ":cond:goto@cond = \"@@\";\n"
    ":state:abort = 1;\n"
    ":state:nextlabel = 0;\n"
    ":bit-vectors = 0;\n"
    ":debug-output = 0;\n"
    ":computed-gotos = 0;\n"
    ":computed-gotos:threshold = 9;\n"
    ":nested-ifs = 0;\n"
    ":case-insensitive = 0;\n"
    ":case-inverted = 0;\n"
    ":case-ranges = 1;\n"
    ":unsafe = 0;\n"
    ":monadic = 0;\n"
    ":encoding:ebcdic = 0;\n"
    ":encoding:utf32 = 0;\n"
    ":encoding:ucs2 = 0;\n"
    ":encoding:utf16 = 0;\n"
    ":encoding:utf8 = 0;\n"
    ":encoding-policy = ignore;\n"
    ":empty-class = match-empty;\n"
    ":indent:string = \"    \";\n"
    ":indent:top = 0;\n"
    ":label:prefix = \"yy\"; // used for generating function names\n"
    ":label:yyfill = \"\";\n"
    ":label:yyloop = \"\";\n"
    ":label:yyNext = \"\";\n"
    ":label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    ":YYBACKUP = \"yybackup\";\n"
    ":YYBACKUPCTX = \"yybackupctx\";\n"
    ":YYCONDTYPE = \"yycondtype\";\n"
    ":YYCOPYMTAG = sigil \"{lhs} <- \" sigil \"{rhs};\";\n"
    ":YYCOPYSTAG = sigil \"{lhs} <- \" sigil \"{rhs};\";\n"
    ":YYCTYPE = \"char\";\n"
    ":YYCTXMARKER = (.api.record ? yyrecord \".\") \"yyctxmarker\";\n"
    ":YYCURSOR = (.api.record ? yyrecord \".\") \"yycursor\";\n"
    ":YYDEBUG = \"yydebug\";\n"
    ":YYFILL = \"yyfill\";\n"
    ":YYGETACCEPT = sigil \"{var}\";\n"
    ":YYGETCOND = \"yygetcond\";\n"
    ":YYGETSTATE = \"yygetstate\";\n"
    ":YYINPUT = (.api.record ? yyrecord \".\") \"yyinput\";\n"
    ":YYLESSTHAN = \"yylesthan\";\n"
    ":YYLIMIT = (.api.record ? yyrecord \".\") \"yylimit\";\n"
    ":YYMARKER = (.api.record ? yyrecord \".\") \"yymarker\";\n"
    ":YYMAXFILL = \"yymaxfill\";\n"
    ":YYMAXNMATCH = \"yymaxnmatch\";\n"
    ":YYMTAGN = \"yymatgn\";\n"
    ":YYMTAGP = \"yymtagp\";\n"
    ":YYPEEK = (.api.record ? \"get\" : \"yypeek\");\n"
    ":YYRESTORE = \"yyrestore\";\n"
    ":YYRESTORECTX = \"yyrestorectx\";\n"
    ":YYRESTORETAG = \"yyrestoretag\";\n"
    ":YYSETACCEPT = sigil \"{var} <- \" sigil \"{val};\";\n"
    ":YYSETCOND = \"yysetcond\";\n"
    ":YYSETSTATE = \"yysetstate\";\n"
    ":YYSHIFT = \"yyshift\";\n"
    ":YYSHIFTSTAG = \"yyshiftstag\";\n"
    ":YYSHIFTMTAG = \"yyshiftmtag\";\n"
    ":YYSKIP = \"yyskip\";\n"
    ":YYSTAGN = \"yystagn\";\n"
    ":YYSTAGP = \"yystagp\";\n"
    ":tags:expression = (.api.record ? yyrecord \".\") sigil;\n"
    ":tags:negative = (.api.generic ? \"@@\" : \"-1\");\n"
    ":cond:divider = \"\";\n"
    ":cond:goto = \"\";\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "::var_local = topindent \"let \" name \" = \" init \" in\" nl;\n"
    "::var_global = topindent \"let \" name \" = \" init nl;\n"
    "\n"
    "::const_local = topindent \"let \" name \" = \" init \" in\" nl;\n"
    "::const_global = topindent \"let \" name \" = \" init nl;\n"
    "\n"
    "::array_local =\n"
    "    topindent \"and \" name \" = [|\" nl indent\n"
    "        [row: topindent [elem{0:-2}: elem \"; \"] [elem{-1}: elem \";\"] nl]\n"
    "    dedent topindent \"|]\" nl;\n"
    "\n"
    "::array_global = ::array_local;\n"
    "\n"
    "::array_elem = array \".(\" index \")\";\n"
    "\n"
    "::enum =\n"
    "    \"type \" name \" = \"\n"
    "        [elem{0}:          elem]\n"
    "        [elem{1:-1}: \" | \" elem]\n"
    "    nl;\n"
    "\n"
    "::enum_elem = name;\n"
    "\n"
    "::assign = topindent lhs \" <- \" rhs \";\" nl;\n"
    "\n"
    "::type_int = \"int\";\n"
    "::type_uint = \"uint\";\n"
    "::type_cond_enum = (.storable_state ? \"int\" : \"uint\");\n"
    "::type_yybm = \"int\";\n"
    "::type_yytarget = <undefined>;\n"
    "\n"
    "::cmp_eq = \"==\"; // physical equality, as this is used to compare primitive values\n"
    "::cmp_ne = \"!=\"; // physical inequality, as this is used to compare primitive values\n"
    "::cmp_lt = \"<\";\n"
    "::cmp_gt = \">\";\n"
    "::cmp_le = \"<=\";\n"
    "::cmp_ge = \">=\";\n"
    "\n"
    "::if_then_else =\n"
    "    [branch{0}: topindent \"if (\" cond \") then (\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent \") else \" (.cond ? \"if (\" cond \") then \") \"(\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    topindent \")\" nl;\n"
    "\n"
    "::if_then_else_oneline =\n"
    "    [branch{0}: topindent \"if (\" cond \") then \" [stmt: stmt] nl]\n"
    "    [branch{1:-1}: topindent \"else \" (.cond ? \"if (\" cond \") then \") [stmt: stmt] nl];\n"
    "\n"
    "::switch =\n"
    "    topindent \"match \" expr \" with\" nl\n"
    "        indent [case: case] dedent;\n"
    "\n"
    "::switch_cases =\n"
    "    [case{0:-2}: topindent \"| \" case nl]\n"
    "    [case{-1}:   topindent \"| \" case \" ->\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    ];\n"
    "\n"
    "::switch_cases_oneline =\n"
    "    [case{0:-2}: topindent \"| \" case nl]\n"
    "    [case{-1}:   topindent \"| \" case \" -> \" [stmt: stmt] nl];\n"
    "\n"
    "// In OCaml only literals of type `char` support case ranges.\n"
    "// For `int`, we have to exlicitly list all range values. We cannot use\n"
    "//     `\"c when \" [val{0}: val] \" <= c && c <= \" [val{-1}: val]`\n"
    "// as it causes error when there are multiple cases:\n"
    "//     `Error: Variable c must occur on both sides of this | pattern`.\n"
    "::switch_case_range = (.char_literals\n"
    "    ? [val{0}: val] (.many ? \"..\" [val{-1}: val])\n"
    "    : [val{0}: val] [val{1:-1}: \"|\" val]);\n"
    "\n"
    "::switch_case_default = \"_\";\n"
    "\n"
    "::loop = <undefined>;\n"
    "\n"
    "::continue = <undefined>;\n"
    "\n"
    "::goto = <undefined>;\n"
    "\n"
    "::fndecl = <undefined>;\n"
    "\n"
    "::fndef =\n"
    "    name [arg: \" (\" argname \" : \" argtype \")\"] \" : \" type \" =\" nl\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::fncall =\n"
    "    topindent (.retval ? \"let \" retval \" = \")\n"
    "        \"(\" name \" [@tailcall])\" (.args ? [arg: \" \" arg] : \" ()\") nl;\n"
    "\n"
    "::tailcall = topindent \"(\" name \" [@tailcall])\" (.args ? [arg: \" \" arg] : \" ()\") nl;\n"
    "\n"
    "::recursive_functions =\n"
    "    [fn{0}:    \"let rec \" fndef nl]\n"
    "    [fn{1:-1}: \"and \"     fndef nl];\n"
    "\n"
    "::fingerprint =\n"
    "    \"(* Generated by re2ocaml\" (.version ? \" \" version) (.date ? \" on \" date) \" *)\" nl;\n"
    "\n"
    "::line_info = \"#\" line \" \\\"\" file \"\\\"\" nl;\n"
    "\n"
    "::abort = topindent \"raise (Failure \\\"internal lexer error\\\")\" nl;\n"
    "\n"
    "::yydebug =\n"
    "    topindent (.api.record\n"
    "        ? YYDEBUG \" \" yyrecord\n"
    "        : YYDEBUG\n"
    "    ) nl;\n"
    "\n"
    "::yypeek =\n"
    "    topindent (.api.record\n"
    "        ? \"let \" yych \" = \" YYPEEK \" \" YYINPUT \" \" YYCURSOR \" in\"\n"
    "        : \"let \" yych \" = \" YYPEEK \" in\"\n"
    "    ) nl;\n"
    "\n"
    "::yyskip =\n"
    "    topindent (.api.record\n"
    "        ? YYCURSOR \" <- \" YYCURSOR \" + 1;\"\n"
    "        : YYSKIP\n"
    "    ) nl;\n"
    "\n"
    "::yybackup =\n"
    "    topindent (.api.record\n"
    "        ? YYMARKER \" <- \" YYCURSOR \";\"\n"
    "        : YYBACKUP\n"
    "    ) nl;\n"
    "\n"
    "::yybackupctx =\n"
    "    topindent (.api.record\n"
    "        ? YYCTXMARKER \" <- \" YYCURSOR \";\"\n"
    "        : YYBACKUPCTX\n"
    "    ) nl;\n"
    "\n"
    "::yyskip_yypeek = <undefined>;\n"
    "::yypeek_yyskip = <undefined>;\n"
    "::yyskip_yybackup = <undefined>;\n"
    "::yybackup_yyskip = <undefined>;\n"
    "::yybackup_yypeek = <undefined>;\n"
    "::yyskip_yybackup_yypeek = <undefined>;\n"
    "::yybackup_yypeek_yyskip = <undefined>;\n"
    "\n"
    "::yyrestore =\n"
    "    topindent (.api.record\n"
    "        ? YYCURSOR \" <- \" YYMARKER \";\"\n"
    "        : YYRESTORE\n"
    "    ) nl;\n"
    "\n"
    "::yyrestorectx =\n"
    "    topindent (.api.record\n"
    "        ? YYCURSOR \" <- \" YYCTXMARKER \";\"\n"
    "        : YYRESTORECTX\n"
    "    ) nl;\n"
    "\n"
    "::yyrestoretag =\n"
    "    topindent (.api.record\n"
    "        ? YYCURSOR \" <- \" tag \";\"\n"
    "        : YYRESTORETAG\n"
    "    ) nl;\n"
    "\n"
    "::yyshift =\n"
    "    topindent (.api.record\n"
    "        ? YYCURSOR \" <- \" YYCURSOR \" - \" offset \";\"\n"
    "        : YYSHIFT\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftstag =\n"
    "    topindent (.nested ? \"if \" tag \" <> \" neg \" then \") (.api.record\n"
    "        ? tag \" <- \" tag \" - \" offset \";\"\n"
    "        : YYSHIFTSTAG\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG nl;\n"
    "\n"
    "::yystagp =\n"
    "    topindent (.api.record\n"
    "        ? tag \" <- \" YYCURSOR \";\"\n"
    "        : YYSTAGP\n"
    "    ) nl;\n"
    "\n"
    "::yymtagp =\n"
    "    topindent YYMTAGP nl;\n"
    "\n"
    "::yystagn =\n"
    "    topindent (.api.record\n"
    "        ? tag \" <- \" neg \";\"\n"
    "        : YYSTAGN\n"
    "    ) nl;\n"
    "\n"
    "::yymtagn =\n"
    "    topindent YYMTAGN nl;\n"
    "\n"
    "::yycopystag =\n"
    "    topindent (.api.record\n"
    "        ? lhs \" <- \" rhs \";\"\n"
    "        : YYCOPYSTAG\n"
    "    ) nl;\n"
    "\n"
    "::yycopymtag =\n"
    "    topindent (.api.record\n"
    "        ? lhs \" <- \" rhs \";\"\n"
    "        : YYCOPYMTAG\n"
    "    ) nl;\n"
    "\n"
    "::yygetaccept =\n"
    "    (.api.record ? yyrecord \".\" var : YYGETACCEPT);\n"
    "\n"
    "::yysetaccept =\n"
    "    topindent (.api.record\n"
    "        ? yyrecord \".\" var \" <- \" val \";\"\n"
    "        : YYSETACCEPT\n"
    "    ) nl;\n"
    "\n"
    "::yygetcond =\n"
    "    (.api.record ? yyrecord \".\" var : YYGETCOND);\n"
    "\n"
    "::yysetcond =\n"
    "    topindent (.api.record\n"
    "        ? yyrecord \".\" var \" <- \" val \";\"\n"
    "        : YYSETCOND\n"
    "    ) nl;\n"
    "\n"
    "::yygetstate =\n"
    "    (.api.record ? yyrecord \".\" var : YYGETSTATE);\n"
    "\n"
    "::yysetstate =\n"
    "    topindent (.api.record\n"
    "        ? yyrecord \".\" var \" <- \" val \";\"\n"
    "        : YYSETSTATE\n"
    "    ) nl;\n"
    "\n"
    "::yylessthan =\n"
    "    (.api.record\n"
    "        ? (.many\n"
    "            ? \"(\" YYLIMIT \" - \" YYCURSOR \") < \" need\n"
    "            : YYLIMIT \" <= \" YYCURSOR)\n"
    "        : YYLESSTHAN);\n"
    "\n"
    "::yybm_filter = yych \" land ~0xFF\";\n"
    "\n"
    "::yybm_match = \"(\" yybm \".(\" offset \" + Char.code \" yych \") land \" mask \") != 0\";\n"
    ;
