#include "src/parse/conf_parser.h"
const char* DEFAULT_SYNTAX_PYTHON =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    ":supported_apis = [\"simple\", \"generic\", \"record\"];\n"
    ":supported_api_styles = [\"free-form\"];\n"
    "// \"recursive_functions\" works syntactically, but causes stack overflows due to non-tail recusion\n"
    ":supported_code_models = [\"loop-switch\"];\n"
    ":supported_targets = [\"code\", \"dot\"];\n"
    ":supported_features = [\"nested-ifs\", \"bitmaps\", \"tags\", \"captures\", \"captvars\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    ":semicolons = 0;\n"
    ":backtick_quoted_strings = 0;\n"
    ":single_quoted_strings = 1;\n"
    ":indentation_sensitive = 1;\n"
    ":wrap_blocks_in_braces = 0;\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    ":target = code;\n"
    ":code-model = loop-switch;\n"
    ":input-encoding = ascii;\n"
    ":date = 1;\n"
    ":version = 1;\n"
    ":conditions = 0;\n"
    ":storable-state = 0;\n"
    ":flex-syntax = 0;\n"
    ":verbose = 0;\n"
    ":line-dirs = 0;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    ":api = simple;\n"
    ":api:style = free-form;\n"
    ":api:sigil = \"@@\";\n"
    ":YYGETCOND:naked = 0;\n"
    ":YYSETCOND:naked = 0;\n"
    ":YYSETCOND@cond = \"@@\";\n"
    ":YYGETSTATE:naked = 0;\n"
    ":YYSETSTATE:naked = 0;\n"
    ":YYSETSTATE@state = \"@@\";\n"
    ":YYFILL@len = \"@@\";\n"
    ":YYFILL:naked = 0;\n"
    ":YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    ":yyfn:sep = \";\";\n"
    ":yycond = \"yycond\";\n"
    ":yyctable = \"yyctable\";\n"
    ":yyaccept = \"yyaccept\";\n"
    ":yytarget = \"yytarget\";\n"
    ":yystate = \"yystate\";\n"
    ":yynmatch = \"yynmatch\";\n"
    ":yypmatch = \"yypmatch\";\n"
    ":yyrecord = \"yyrecord\";\n"
    ":yych = \"yych\";\n"
    ":yych:conversion = 0;\n"
    ":yych:literals = hex;\n"
    ":yych:emit = 0;\n"
    ":yybm = \"yybm\";\n"
    ":yybm:hex = 0;\n"
    ":yyfill = \"\";\n"
    ":yystable = \"\"; // deprecated\n"
    ":header = \"\";\n"
    ":eof = -1;\n"
    ":sentinel = -1;\n"
    ":yyfill:enable = 1;\n"
    ":yyfill:parameter = 1;\n"
    ":yyfill:check = 1;\n"
    ":tags = 0;\n"
    ":tags:prefix = \"yyt\";\n"
    ":captures = 0;\n"
    ":captvars = 0;\n"
    ":posix-captures = 0;\n"
    ":posix-captvars = 0;\n"
    ":invert-captures = 0;\n"
    ":cond:abort = 0; // default case causes [redundant-case] warnings\n"
    ":cond:prefix = \"yyc_\";\n"
    ":cond:enumprefix = \"YYC_\";\n"
    ":cond:divider@cond = \"@@\";\n"
    ":cond:goto@cond = \"@@\";\n"
    ":state:abort = 1;\n"
    ":state:nextlabel = 0;\n"
    ":bit-vectors = 0;\n"
    ":debug-output = 0;\n"
    ":computed-gotos = 0;\n"
    ":computed-gotos:threshold = 9;\n"
    ":nested-ifs = 1;\n"
    ":case-insensitive = 0;\n"
    ":case-inverted = 0;\n"
    ":case-ranges = 0;\n"
    ":unsafe = 0;\n"
    ":monadic = 0;\n"
    ":encoding:ebcdic = 0;\n"
    ":encoding:utf32 = 0;\n"
    ":encoding:ucs2 = 0;\n"
    ":encoding:utf16 = 0;\n"
    ":encoding:utf8 = 0;\n"
    ":encoding-policy = ignore;\n"
    ":empty-class = match-empty;\n"
    ":indent:string = \"    \";\n"
    ":indent:top = 0;\n"
    ":label:prefix = \"\";\n"
    ":label:yyfill = \"\";\n"
    ":label:yyloop = \"\";\n"
    ":label:yyNext = \"\";\n"
    ":label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    ":YYBACKUP = \"yybackup\";\n"
    ":YYBACKUPCTX = \"yybackupctx\";\n"
    ":YYCONDTYPE = \"yycondtype\";\n"
    ":YYCOPYMTAG = sigil \"{lhs} = \" sigil \"{rhs}\";\n"
    ":YYCOPYSTAG = sigil \"{lhs} = \" sigil \"{rhs}\";\n"
    ":YYCTYPE = \"yyctype\";\n"
    ":YYCTXMARKER = (.api.record ? yyrecord \".\") \"yyctxmarker\";\n"
    ":YYCURSOR = (.api.record ? yyrecord \".\") \"yycursor\";\n"
    ":YYDEBUG = \"yydebug\";\n"
    ":YYFILL = \"yyfill\";\n"
    ":YYGETACCEPT = sigil \"{var}\";\n"
    ":YYGETCOND = \"yygetcond\";\n"
    ":YYGETSTATE = \"yygetstate\";\n"
    ":YYINPUT = (.api.record ? yyrecord \".\") \"yyinput\";\n"
    ":YYLESSTHAN = \"yylessthan\";\n"
    ":YYLIMIT = (.api.record ? yyrecord \".\") \"yylimit\";\n"
    ":YYMARKER = (.api.record ? yyrecord \".\") \"yymarker\";\n"
    ":YYMAXFILL = \"YYMAXFILL\";\n"
    ":YYMAXNMATCH = \"YYMAXNMATCH\";\n"
    ":YYMTAGN = \"yymtagn\";\n"
    ":YYMTAGP = \"yymtagp\";\n"
    ":YYPEEK = \"yypeek\";\n"
    ":YYRESTORE = \"yyrestore\";\n"
    ":YYRESTORECTX = \"yyrestorectx\";\n"
    ":YYRESTORETAG = \"yyrestoretag\";\n"
    ":YYSETACCEPT = sigil \"{var} = \" sigil \"{val}\";\n"
    ":YYSETCOND = \"yysetcond\";\n"
    ":YYSETSTATE = \"yysetstate\";\n"
    ":YYSHIFT = \"yyshift\";\n"
    ":YYSHIFTSTAG = \"yyshiftstag\";\n"
    ":YYSHIFTMTAG = \"yyshiftmtag\";\n"
    ":YYSKIP = \"yyskip\";\n"
    ":YYSTAGN = \"yystagn\";\n"
    ":YYSTAGP = \"yystagp\";\n"
    ":tags:expression = sigil;\n"
    ":tags:negative = (.api.generic ? \"@@\" : \"-1\");\n"
    ":cond:divider = \"\";\n"
    ":cond:goto = \"\";\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "::var_local = topindent name (.init ? \" = \" init) nl;\n"
    "::var_global = ::var_local;\n"
    "\n"
    "::const_local = topindent name \" = \" init nl;\n"
    "::const_global = ::const_local;\n"
    "\n"
    "::array_local =\n"
    "    topindent name \" = [\" nl indent\n"
    "        [row: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "    dedent topindent \"]\" nl;\n"
    "\n"
    "::array_global = <undefined>;\n"
    "\n"
    "::array_elem = array \"[\" index \"]\";\n"
    "\n"
    "::enum = [elem: elem \" = \" init nl];\n"
    "\n"
    "::enum_elem = name;\n"
    "\n"
    "::assign = topindent lhs \" = \" rhs nl;\n"
    "\n"
    "::type_int = <undefined>;\n"
    "::type_uint = <undefined>;\n"
    "::type_cond_enum = <undefined>;\n"
    "::type_yybm = <undefined>;\n"
    "::type_yytarget = <undefined>;\n"
    "\n"
    "::cmp_eq = \"==\";\n"
    "::cmp_ne = \"!=\";\n"
    "::cmp_lt = \"<\";\n"
    "::cmp_gt = \">\";\n"
    "::cmp_le = \"<=\";\n"
    "::cmp_ge = \">=\";\n"
    "\n"
    "::if_then_else =\n"
    "    [branch{0}: topindent \"if \" cond \":\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent (.cond ? \"elif \" cond : \"else\") \":\" nl\n"
    "        indent [stmt: stmt] dedent];\n"
    "\n"
    "::if_then_else_oneline = <undefined>;\n"
    "\n"
    "::switch =\n"
    "    topindent \"match \" expr \":\" nl\n"
    "        indent [case: case] dedent;\n"
    "\n"
    "::switch_cases = topindent \"case \"\n"
    "    [case{0:-2}: case \"|\"]\n"
    "    [case{-1}:   case \":\" nl]\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::switch_cases_oneline = <undefined>;\n"
    "\n"
    "::switch_case_range = (.many\n"
    "    ? [val{0}: val] [val{1:-1}: \"|\" val]\n"
    "    : [val{0}: val]);\n"
    "\n"
    "::switch_case_default = \"_\";\n"
    "\n"
    "::loop =\n"
    "    topindent \"while True:\" nl\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::continue = topindent \"continue\" nl;\n"
    "\n"
    "::goto = <undefined>;\n"
    "\n"
    "::fndecl = <undefined>;\n"
    "\n"
    "::fndef =\n"
    "    \"def \" name \"(\" [arg{0}: argname] [arg{1:-1}: \", \" argname] \"):\" nl\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::fncall =\n"
    "    topindent (.retval ? retval \" = \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \")\" nl;\n"
    "\n"
    "::tailcall =\n"
    "    topindent (.retval ? \"return \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \")\" nl;\n"
    "\n"
    "::recursive_functions = [fn: fndef nl];\n"
    "\n"
    "::fingerprint =\n"
    "    \"# Generated by re2py\" (.version ? \" \" version) (.date ? \" on \" date) nl;\n"
    "\n"
    "::line_info = <undefined>;\n"
    "\n"
    "::abort = topindent \"raise \\\"internal lexer error\\\"\" nl;\n"
    "\n"
    "::yydebug =\n"
    "    topindent (.api.generic\n"
    "        ? YYDEBUG\n"
    "    : (.api.record\n"
    "        ? YYDEBUG \"(\" yyrecord \")\"\n"
    "        : YYDEBUG \"(\" state \", \" yych \")\"\n"
    "    )) nl;\n"
    "\n"
    "::yypeek =\n"
    "    topindent (.api.generic\n"
    "        ? yych \" = \" YYPEEK\n"
    "        : yych \" = \" YYINPUT \"[\" YYCURSOR \"]\"\n"
    "    ) nl;\n"
    "\n"
    "::yyskip =\n"
    "    topindent (.api.generic\n"
    "        ? YYSKIP\n"
    "        : YYCURSOR \" += 1\"\n"
    "    ) nl;\n"
    "\n"
    "::yybackup =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUP\n"
    "        : YYMARKER \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yybackupctx =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUPCTX\n"
    "        : YYCTXMARKER \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yyskip_yypeek = <undefined>;\n"
    "::yypeek_yyskip = <undefined>;\n"
    "::yyskip_yybackup = <undefined>;\n"
    "::yybackup_yyskip = <undefined>;\n"
    "::yybackup_yypeek = <undefined>;\n"
    "::yyskip_yybackup_yypeek = <undefined>;\n"
    "::yybackup_yypeek_yyskip = <undefined>;\n"
    "\n"
    "::yyrestore =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORE\n"
    "        : YYCURSOR \" = \" YYMARKER\n"
    "    ) nl;\n"
    "\n"
    "::yyrestorectx =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORECTX\n"
    "        : YYCURSOR \" = \" YYCTXMARKER\n"
    "    ) nl;\n"
    "\n"
    "::yyrestoretag =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORETAG\n"
    "        : YYCURSOR \" = \" tag\n"
    "    ) nl;\n"
    "\n"
    "::yyshift =\n"
    "    topindent (.api.generic\n"
    "        ? YYSHIFT\n"
    "        : YYCURSOR \" -= \" offset\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftstag =\n"
    "    topindent (.nested ? \"if \" tag \" != \" neg \": \") (.api.generic\n"
    "        ? YYSHIFTSTAG\n"
    "        : tag \" -= \" offset\n"
    "    )  nl;\n"
    "\n"
    "::yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG nl;\n"
    "\n"
    "::yystagp =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGP\n"
    "        : tag \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yymtagp =\n"
    "    topindent YYMTAGP nl;\n"
    "\n"
    "::yystagn =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGN\n"
    "        : tag \" = \" neg\n"
    "    ) nl;\n"
    "\n"
    "::yymtagn =\n"
    "    topindent YYMTAGN nl;\n"
    "\n"
    "::yycopystag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYSTAG\n"
    "        : lhs \" = \" rhs\n"
    "    ) nl;\n"
    "\n"
    "::yycopymtag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYMTAG\n"
    "        : lhs \" = \" rhs\n"
    "    ) nl;\n"
    "\n"
    "::yygetaccept =\n"
    "    (.api.generic\n"
    "        ? YYGETACCEPT\n"
    "        : (.api.record & .storable_state ? yyrecord \".\") var);\n"
    "\n"
    "::yysetaccept =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETACCEPT\n"
    "        : (.api.record & .storable_state ? yyrecord \".\") var \" = \" val\n"
    "    ) nl;\n"
    "\n"
    "::yygetcond =\n"
    "    (.api.generic\n"
    "        ? YYGETCOND\n"
    "        : (.api.record ? yyrecord \".\") var);\n"
    "\n"
    "::yysetcond =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETCOND\n"
    "        : (.api.record ? yyrecord \".\") var \" = \" val\n"
    "    ) nl;\n"
    "\n"
    "::yygetstate =\n"
    "     (.api.generic\n"
    "         ? YYGETSTATE\n"
    "         : (.api.record ? yyrecord \".\") var);\n"
    "\n"
    "::yysetstate =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETSTATE\n"
    "        : (.api.record ? yyrecord \".\") var \" = \" val\n"
    "    ) nl;\n"
    "\n"
    "::yylessthan =\n"
    "    (.api.generic\n"
    "        ? YYLESSTHAN\n"
    "        : (.many\n"
    "            ? \"(\" YYLIMIT \" - \" YYCURSOR \") < \" need\n"
    "            : YYLIMIT \" <= \" YYCURSOR));\n"
    "\n"
    "::yybm_filter = yych \" & ~0xFF\";\n"
    "\n"
    "::yybm_match = \"(\" yybm \"[\" offset \"+\" yych \"] & \" mask \") != 0\";\n"
    ;
