#include "src/parse/conf_parser.h"
const char* DEFAULT_SYNTAX_HASKELL =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    ":supported_apis = [\"record\", \"generic\"];\n"
    ":supported_api_styles = [\"free-form\"];\n"
    ":supported_code_models = [\"recursive-functions\"];\n"
    ":supported_targets = [\"code\", \"dot\"];\n"
    ":supported_features = [\"nested-ifs\", \"bitmaps\", \"monadic\", \"tags\", \"captvars\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    ":semicolons = 0;\n"
    ":backtick_quoted_strings = 0;\n"
    ":single_quoted_strings = 0;\n"
    ":indentation_sensitive = 1;\n"
    ":wrap_blocks_in_braces = 0;\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    ":target = code;\n"
    ":code-model = recursive-functions;\n"
    ":input-encoding = ascii;\n"
    ":date = 1;\n"
    ":version = 1;\n"
    ":conditions = 0;\n"
    ":storable-state = 0;\n"
    ":flex-syntax = 0;\n"
    ":verbose = 0;\n"
    ":line-dirs = 1;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    ":api = record;\n"
    ":api:style = free-form;\n"
    ":api:sigil = \"@@\";\n"
    ":YYGETCOND:naked = 0;\n"
    ":YYSETCOND:naked = 0;\n"
    ":YYSETCOND@cond = \"@@\";\n"
    ":YYGETSTATE:naked = 0;\n"
    ":YYSETSTATE:naked = 0;\n"
    ":YYSETSTATE@state = \"@@\";\n"
    ":YYFILL@len = \"@@\";\n"
    ":YYFILL:naked = 0;\n"
    ":YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    ":yyfn:sep = \";\";\n"
    ":yycond = \"_yycond\";\n"
    ":yyctable = \"\"; // unused\n"
    ":yyaccept = \"_yyaccept\";\n"
    ":yytarget = \"\"; // unused\n"
    ":yystate = \"_yystate\";\n"
    ":yynmatch = \"yynmatch\";\n"
    ":yypmatch = \"yypmatch\";\n"
    ":yyrecord = \"yyrecord\";\n"
    ":yych = \"yych\";\n"
    ":yych:conversion = 0;\n"
    ":yych:literals = hex;\n"
    ":yych:emit = (.code_model.recursive_functions ? 0 : 1);\n"
    ":yybm = \"yybm\";\n"
    ":yybm:hex = 0;\n"
    ":yyfill = \"yyfill\";\n"
    ":yystable = \"\"; // deprecated\n"
    ":header = \"\";\n"
    ":eof = -1;\n"
    ":sentinel = -1;\n"
    ":yyfill:enable = 1;\n"
    ":yyfill:parameter = 1;\n"
    ":yyfill:check = 1;\n"
    ":tags = 0;\n"
    ":tags:prefix = \"_yyt\";\n"
    ":captures = 0;\n"
    ":captvars = 0;\n"
    ":posix-captures = 0;\n"
    ":posix-captvars = 0;\n"
    ":invert-captures = 0;\n"
    ":cond:abort = 1;\n"
    ":cond:prefix = \"yyc_\";\n"
    ":cond:enumprefix = \"YYC_\";\n"
    ":cond:divider@cond = \"@@\";\n"
    ":cond:goto@cond = \"@@\";\n"
    ":state:abort = 1;\n"
    ":state:nextlabel = 0;\n"
    ":bit-vectors = 0;\n"
    ":debug-output = 0;\n"
    ":computed-gotos = 0;\n"
    ":computed-gotos:threshold = 9;\n"
    ":nested-ifs = 0;\n"
    ":case-insensitive = 0;\n"
    ":case-inverted = 0;\n"
    ":case-ranges = 0;\n"
    ":unsafe = 0;\n"
    ":monadic = 0;\n"
    ":encoding:ebcdic = 0;\n"
    ":encoding:utf32 = 0;\n"
    ":encoding:ucs2 = 0;\n"
    ":encoding:utf16 = 0;\n"
    ":encoding:utf8 = 0;\n"
    ":encoding-policy = ignore;\n"
    ":empty-class = match-empty;\n"
    ":indent:string = \"    \";\n"
    ":indent:top = 0;\n"
    ":label:prefix = \"yy\"; // used for generating function names\n"
    ":label:yyfill = \"\";\n"
    ":label:yyloop = \"\";\n"
    ":label:yyNext = \"\";\n"
    ":label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    ":YYBACKUP = \"yybackup\";\n"
    ":YYBACKUPCTX = \"yybackupctx\";\n"
    ":YYCONDTYPE = \"YYCONDTYPE\";\n"
    ":YYCOPYMTAG = \"yycopymtag\";\n"
    ":YYCOPYSTAG = \"yycopystag\";\n"
    ":YYCTYPE = \"YYCTYPE\";\n"
    ":YYCTXMARKER = \"_yyctxmarker\";\n"
    ":YYCURSOR = \"_yycursor\";\n"
    ":YYDEBUG = \"yydebug\";\n"
    ":YYFILL = \"yyfill\";\n"
    ":YYGETACCEPT = \"yygetaccept\";\n"
    ":YYGETCOND = \"yygetcond\";\n"
    ":YYGETSTATE = \"yygetstate\";\n"
    ":YYINPUT = \"_yyinput\";\n"
    ":YYLESSTHAN = \"yylessthan\";\n"
    ":YYLIMIT = \"_yylimit\";\n"
    ":YYMARKER = \"_yymarker\";\n"
    ":YYMAXFILL = \"yymaxfill\";\n"
    ":YYMAXNMATCH = \"yymaxnmatch\";\n"
    ":YYMTAGN = \"yymtagn\";\n"
    ":YYMTAGP = \"yymtagp\";\n"
    ":YYPEEK = (.api.record ? \"index\" : \"yypeek\");\n"
    ":YYRESTORE = \"yyrestore\";\n"
    ":YYRESTORECTX = \"yyrestorectx\";\n"
    ":YYRESTORETAG = \"yyrestoretag\";\n"
    ":YYSETACCEPT = \"yysetaccept\";\n"
    ":YYSETCOND = \"yysetcond\";\n"
    ":YYSETSTATE = \"yysetstate\";\n"
    ":YYSHIFT = \"yyshift\";\n"
    ":YYSHIFTSTAG = \"yyshiftstag\";\n"
    ":YYSHIFTMTAG = \"yyshiftmtag\";\n"
    ":YYSKIP = \"yyskip\";\n"
    ":YYSTAGN = \"yystagn\";\n"
    ":YYSTAGP = \"yystagp\";\n"
    ":tags:expression = sigil;\n"
    ":tags:negative = (.api.generic ? \"@@\" : \"(-1)\");\n"
    ":cond:divider = \"\";\n"
    ":cond:goto = \"\";\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "::var_local = topindent \"let \" name \" = \" init \" in\" nl;\n"
    "::var_global = topindent \"let \" name \" = \" init nl;\n"
    "\n"
    "::const_local = topindent \"let \" name \" = \" init \" in\" nl;\n"
    "::const_global = topindent name \" = \" init nl;\n"
    "\n"
    "::array_local = <undefined>;\n"
    "\n"
    "::array_global =\n"
    "    topindent name \" :: Array Int \" type nl\n"
    "    topindent name \" = array (0, \" size \" - 1) $ Prelude.zip [0 .. \" size \" - 1] [\" nl indent\n"
    "        [row{0:-2}: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "        [row{-1}:   topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \"]\"] nl];\n"
    "\n"
    "::array_elem = array \" ! \" index;\n"
    "\n"
    "::enum =\n"
    "    \"data \" name \" = \"\n"
    "        [elem{0:-2}: elem \" | \"]\n"
    "        [elem{-1}: elem] \" deriving (Eq, Show)\"\n"
    "    nl;\n"
    "\n"
    "::enum_elem = name;\n"
    "\n"
    "::assign = <undefined>;\n"
    "\n"
    "::type_int = <undefined>;\n"
    "::type_uint = <undefined>;\n"
    "::type_cond_enum = <undefined>;\n"
    "::type_yybm = \"Word8\";\n"
    "::type_yytarget = <undefined>;\n"
    "\n"
    "::cmp_eq = \"==\";\n"
    "::cmp_ne = \"/=\";\n"
    "::cmp_lt = \"<\";\n"
    "::cmp_gt = \">\";\n"
    "::cmp_le = \"<=\";\n"
    "::cmp_ge = \">=\";\n"
    "\n"
    "::if_then_else =\n"
    "    [branch{0}: topindent (.many ? \"if \" cond \" then\" : \"when (\" cond \") $\") (.monadic ? \" do\") nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent \"else\" (.cond ? \" if \" cond \" then\") (.monadic ? \" do\") nl\n"
    "        indent [stmt: stmt] dedent];\n"
    "\n"
    "::if_then_else_oneline =\n"
    "    [branch{0}: topindent (.many ? \"if \" cond \" then \" : \"when (\" cond \") $ \") [stmt: stmt] nl]\n"
    "    [branch{1:-1}: topindent \"else \" (.cond ? \"if \" cond \" then \") [stmt: stmt] nl];\n"
    "\n"
    "::switch =\n"
    "    topindent \"case \" expr \" of\" nl\n"
    "        indent [case: case] dedent;\n"
    "\n"
    "::switch_cases = topindent \"_c | \"\n"
    "    [case{0:-2}: case \" || \"]\n"
    "    [case{-1}:   case \" ->\" (.monadic ? \" do\") nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    ];\n"
    "\n"
    "::switch_cases_oneline = <undefined>;\n"
    "\n"
    "::switch_case_range = (.many\n"
    "    ? [val{0}: val] \" <= _c && _c <= \" [val{-1}: val]\n"
    "    : [val{0}: val] \" == _c\");\n"
    "\n"
    "::switch_case_default = \"True\";\n"
    "\n"
    "::loop = <undefined>;\n"
    "\n"
    "::continue = <undefined>;\n"
    "\n"
    "::goto = <undefined>;\n"
    "\n"
    "::fndecl = <undefined>;\n"
    "\n"
    "::fndef =\n"
    "    name \" :: \" [arg: argtype \" -> \"] type nl\n"
    "    name [arg: \" \" argname] \" =\" (.monadic ? \" do\") nl\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::fncall =\n"
    "    topindent (.retval ? \"let \" retval \" = \")\n"
    "        name (.args ? [arg: \" \" arg] : \" ()\") nl;\n"
    "\n"
    "::tailcall = topindent name (.args ? [arg: \" \" arg] : \" ()\") nl;\n"
    "\n"
    "::recursive_functions = [fn: fndef nl];\n"
    "\n"
    "::fingerprint =\n"
    "    \"-- Generated by re2hs\" (.version ? \" \" version) (.date ? \" on \" date) nl\n"
    "    (.api.record ? \"{-# LANGUAGE RecordWildCards #-}\" nl);\n"
    "\n"
    "::line_info = \"#\" line \" \\\"\" file \"\\\"\" nl;\n"
    "\n"
    "::abort = topindent \"error \\\"internal lexer error\\\"\" nl;\n"
    "\n"
    "::yydebug = topindent YYDEBUG nl;\n"
    "\n"
    "::yypeek =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? yych \" <- return $ \" YYPEEK \" \" YYINPUT \" \" YYCURSOR\n"
    "            : \"let \" yych \" = \" YYPEEK \" \" YYINPUT \" \" YYCURSOR \" in\")\n"
    "        : (.monadic\n"
    "            ? yych \" <- \" YYPEEK\n"
    "            : \"let \" yych \" = \" YYPEEK \" in\")\n"
    "    ) nl;\n"
    "\n"
    "::yyskip =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? YYCURSOR \" <- return $ \" YYCURSOR \" + 1\"\n"
    "            : \"let __ = \" YYCURSOR \" + 1 in let \" YYCURSOR \" = __ in\")\n"
    "        : YYSKIP\n"
    "    ) nl;\n"
    "\n"
    "::yybackup =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" YYMARKER \" = \" YYCURSOR\n"
    "            : \"let \" YYMARKER \" = \" YYCURSOR \" in\")\n"
    "        : YYBACKUP\n"
    "    ) nl;\n"
    "\n"
    "::yybackupctx =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" YYCTXMARKER \" = \" YYCURSOR\n"
    "            : \"let \" YYCTXMARKER \" = \" YYCURSOR \" in\")\n"
    "        : YYBACKUPCTX\n"
    "    ) nl;\n"
    "\n"
    "::yyskip_yypeek = <undefined>;\n"
    "::yypeek_yyskip = <undefined>;\n"
    "::yyskip_yybackup = <undefined>;\n"
    "::yybackup_yyskip = <undefined>;\n"
    "::yybackup_yypeek = <undefined>;\n"
    "::yyskip_yybackup_yypeek = <undefined>;\n"
    "::yybackup_yypeek_yyskip = <undefined>;\n"
    "\n"
    "::yyrestore =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" YYCURSOR \" = \" YYMARKER\n"
    "            : \"let \" YYCURSOR \" = \" YYMARKER \" in\")\n"
    "        : YYRESTORE\n"
    "    ) nl;\n"
    "\n"
    "::yyrestorectx =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" YYCURSOR \" = \" YYCTXMARKER\n"
    "            : \"let \" YYCURSOR \" = \" YYCTXMARKER \" in\")\n"
    "        : YYRESTORECTX\n"
    "    ) nl;\n"
    "\n"
    "::yyrestoretag =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" YYCURSOR \" = \" tag\n"
    "            : \"let \" YYCURSOR \" = \" tag \" in\")\n"
    "        : YYRESTORETAG\n"
    "    ) nl;\n"
    "\n"
    "::yyshift =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? YYCURSOR \" <- return $ \" YYCURSOR \" - \" offset\n"
    "            : \"let __ = \" YYCURSOR \" - \" offset \" in let \" YYCURSOR \" = __ in\")\n"
    "        : YYSHIFT\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftstag =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? tag \" <- return $ if \" tag \" == \" neg \" then \" neg \" else \" tag \" - \" offset\n"
    "            :         \"let __ = if \" tag \" == \" neg \" then \" neg \" else \" tag \" - \" offset\n"
    "                \" in let \" tag \" = __ in\")\n"
    "        : YYSHIFTSTAG\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG nl;\n"
    "\n"
    "::yystagp =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" tag \" = \" YYCURSOR\n"
    "            : \"let \" tag \" = \" YYCURSOR \" in\")\n"
    "        : YYSTAGP\n"
    "    ) nl;\n"
    "\n"
    "::yymtagp =\n"
    "    topindent YYMTAGP nl;\n"
    "\n"
    "::yystagn =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" tag \" = \" neg\n"
    "            : \"let \" tag \" = \" neg \" in\")\n"
    "        : YYSTAGN\n"
    "    ) nl;\n"
    "\n"
    "::yymtagn =\n"
    "    topindent YYMTAGN nl;\n"
    "\n"
    "::yycopystag =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" lhs \" = \" rhs\n"
    "            : \"let \" lhs \" = \" rhs \" in\")\n"
    "        : YYCOPYSTAG\n"
    "    ) nl;\n"
    "\n"
    "::yycopymtag =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" lhs \" = \" rhs\n"
    "            : \"let \" lhs \" = \" rhs \" in\")\n"
    "        : YYCOPYMTAG\n"
    "    ) nl;\n"
    "\n"
    "::yygetaccept =\n"
    "    (.api.record ? var : YYGETACCEPT);\n"
    "\n"
    "::yysetaccept =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" var \" = \" val\n"
    "            : \"let \" var \" = \" val \" in\")\n"
    "        : YYSETACCEPT\n"
    "    ) nl;\n"
    "\n"
    "::yygetcond =\n"
    "    (.api.record ? var : YYGETCOND);\n"
    "\n"
    "::yysetcond =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" var \" = \" val\n"
    "            : \"let \" var \" = \" val \" in\")\n"
    "        : YYSETCOND\n"
    "    ) nl;\n"
    "\n"
    "::yygetstate =\n"
    "    (.api.record ? var : YYGETSTATE);\n"
    "\n"
    "::yysetstate =\n"
    "    topindent (.api.record\n"
    "        ? (.monadic\n"
    "            ? \"let \" var \" = \" val\n"
    "            : \"let \" var \" = \" val \" in\")\n"
    "        : YYSETSTATE\n"
    "    ) nl;\n"
    "\n"
    "::yylessthan =\n"
    "    (.api.record\n"
    "        ? YYCURSOR \" >= \" YYLIMIT // YYFILL check can only be used with EOF rule $\n"
    "        : YYLESSTHAN);\n"
    "\n"
    "::yybm_filter = \"(\" yych \" .&. complement 0xFF) /= 0\";\n"
    "\n"
    "::yybm_match = \"(\" yybm \" ! (\" offset \" + fromIntegral \" yych \") .&. \" mask \") /= 0\";\n"
    ;
