#include "src/parse/conf_parser.h"
const char* DEFAULT_SYNTAX_GO =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    ":supported_apis = [\"simple\", \"generic\", \"record\"];\n"
    ":supported_api_styles = [\"free-form\", \"functions\"];\n"
    ":supported_code_models = [\"goto-label\", \"loop-switch\", \"recursive-functions\"];\n"
    ":supported_targets = [\"code\", \"dot\"];\n"
    ":supported_features = [\"nested-ifs\", \"bitmaps\", \"tags\", \"captures\", \"captvars\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    ":semicolons = 0;\n"
    ":backtick_quoted_strings = 1;\n"
    ":single_quoted_strings = 0;\n"
    ":indentation_sensitive = 0;\n"
    ":wrap_blocks_in_braces = 1;\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    ":target = code;\n"
    ":code-model = goto-label;\n"
    ":input-encoding = ascii;\n"
    ":date = 1;\n"
    ":version = 1;\n"
    ":conditions = 0;\n"
    ":storable-state = 0;\n"
    ":flex-syntax = 0;\n"
    ":verbose = 0;\n"
    ":line-dirs = 1;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    ":api = generic;\n"
    ":api:style = free-form;\n"
    ":api:sigil = \"@@\";\n"
    ":YYGETCOND:naked = 0;\n"
    ":YYSETCOND:naked = 0;\n"
    ":YYSETCOND@cond = \"@@\";\n"
    ":YYGETSTATE:naked = 0;\n"
    ":YYSETSTATE:naked = 0;\n"
    ":YYSETSTATE@state = \"@@\";\n"
    ":YYFILL@len = \"@@\";\n"
    ":YYFILL:naked = 0;\n"
    ":YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    ":yyfn:sep = \";\";\n"
    ":yycond = \"yycond\";\n"
    ":yyctable = \"yyctable\";\n"
    ":yyaccept = \"yyaccept\";\n"
    ":yytarget = \"yytarget\";\n"
    ":yystate = \"yystate\";\n"
    ":yynmatch = \"yynmatch\";\n"
    ":yypmatch = \"yypmatch\";\n"
    ":yyrecord = \"yyrecord\";\n"
    ":yych = \"yych\";\n"
    ":yych:conversion = 0;\n"
    ":yych:literals = char-or-hex;\n"
    ":yych:emit = (.code_model.recursive_functions ? 0 : 1);\n"
    ":yybm = \"yybm\";\n"
    ":yybm:hex = 0;\n"
    ":yyfill = \"\";\n"
    ":yystable = \"\"; // deprecated\n"
    ":header = \"\";\n"
    ":eof = -1;\n"
    ":sentinel = -1;\n"
    ":yyfill:enable = 1;\n"
    ":yyfill:parameter = 1;\n"
    ":yyfill:check = 1;\n"
    ":tags = 0;\n"
    ":tags:prefix = \"yyt\";\n"
    ":captures = 0;\n"
    ":captvars = 0;\n"
    ":posix-captures = 0;\n"
    ":posix-captvars = 0;\n"
    ":invert-captures = 0;\n"
    ":cond:abort = 1;\n"
    ":cond:prefix = \"yyc_\";\n"
    ":cond:enumprefix = \"yyc\";\n"
    ":cond:divider@cond = \"@@\";\n"
    ":cond:goto@cond = \"@@\";\n"
    ":state:abort = (.code_model.goto_label ? 0 : 1); // historically disabled for goto/label\n"
    ":state:nextlabel = 0;\n"
    ":bit-vectors = 0;\n"
    ":debug-output = 0;\n"
    ":computed-gotos = 0;\n"
    ":computed-gotos:threshold = 9;\n"
    ":nested-ifs = 0;\n"
    ":case-insensitive = 0;\n"
    ":case-inverted = 0;\n"
    ":case-ranges = 0;\n"
    ":unsafe = 0;\n"
    ":monadic = 0;\n"
    ":encoding:ebcdic = 0;\n"
    ":encoding:utf32 = 0;\n"
    ":encoding:ucs2 = 0;\n"
    ":encoding:utf16 = 0;\n"
    ":encoding:utf8 = 0;\n"
    ":encoding-policy = ignore;\n"
    ":empty-class = match-empty;\n"
    ":indent:string = \"\\t\";\n"
    ":indent:top = 0;\n"
    ":label:prefix = \"yy\";\n"
    ":label:yyfill = \"yyFillLabel\";\n"
    ":label:yyloop = \"yyl\";\n"
    ":label:yyNext = \"yyNext\";\n"
    ":label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    ":YYBACKUP = \"YYBACKUP\";\n"
    ":YYBACKUPCTX = \"YYBACKUPCTX\";\n"
    ":YYCONDTYPE = \"YYCONDTYPE\";\n"
    ":YYCOPYMTAG = sigil \"{lhs} = \" sigil \"{rhs}\";\n"
    ":YYCOPYSTAG = sigil \"{lhs} = \" sigil \"{rhs}\";\n"
    ":YYCTYPE = \"YYCTYPE\";\n"
    ":YYCTXMARKER = (.api.generic ? \"YYCTXMARKER\" : (.api.record ? yyrecord \".\") \"yyctxmarker\");\n"
    ":YYCURSOR = (.api.generic ? \"YYCURSOR\" : (.api.record ? yyrecord \".\") \"yycursor\");\n"
    ":YYDEBUG = \"YYDEBUG\";\n"
    ":YYFILL = \"YYFILL\";\n"
    ":YYGETACCEPT = sigil \"{var}\";\n"
    ":YYGETCOND = \"YYGETCONDITION\"; // historic default\n"
    ":YYGETSTATE = \"YYGETSTATE\";\n"
    ":YYINPUT = (.api.generic ? \"YYINPUT\" : (.api.record ? yyrecord \".\") \"yyinput\");\n"
    ":YYLESSTHAN = \"YYLESSTHAN\";\n"
    ":YYLIMIT = (.api.generic ? \"YYLIMIT\" : (.api.record ? yyrecord \".\") \"yylimit\");\n"
    ":YYMARKER = (.api.generic ? \"YYMARKER\" : (.api.record ? yyrecord \".\") \"yymarker\");\n"
    ":YYMAXFILL = \"YYMAXFILL\";\n"
    ":YYMAXNMATCH = \"YYMAXNMATCH\";\n"
    ":YYMTAGN = \"YYMTAGN\";\n"
    ":YYMTAGP = \"YYMTAGP\";\n"
    ":YYPEEK = \"YYPEEK\";\n"
    ":YYRESTORE = \"YYRESTORE\";\n"
    ":YYRESTORECTX = \"YYRESTORECTX\";\n"
    ":YYRESTORETAG = \"YYRESTORETAG\";\n"
    ":YYSETACCEPT = sigil \"{var} = \" sigil \"{val}\";\n"
    ":YYSETCOND = \"YYSETCONDITION\"; // historic default\n"
    ":YYSETSTATE = \"YYSETSTATE\";\n"
    ":YYSHIFT = \"YYSHIFT\";\n"
    ":YYSHIFTSTAG = \"YYSHIFTSTAG\";\n"
    ":YYSHIFTMTAG = \"YYSHIFTMTAG\";\n"
    ":YYSKIP = \"YYSKIP\";\n"
    ":YYSTAGN = \"YYSTAGN\";\n"
    ":YYSTAGP = \"YYSTAGP\";\n"
    ":tags:expression = (.api.record ? yyrecord \".\") sigil;\n"
    ":tags:negative = (.api.generic ? \"@@\" : \"-1\");\n"
    ":cond:divider = \"/* *********************************** */\";\n"
    ":cond:goto = \"goto \" sigil;\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "::var_local = topindent (.init ? name \" := \" init : \"var \" name \" \" type) nl;\n"
    "::var_global = topindent \"var \" name \" \" type (.init ? \" = \" init) nl;\n"
    "\n"
    "::const_local = topindent \"const \" name \" = \" init nl;\n"
    "::const_global = ::const_local;\n"
    "\n"
    "::array_local =\n"
    "    topindent name \" := [\" size \"]\" type \"{\" nl indent\n"
    "        [row: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "    dedent topindent \"}\" nl;\n"
    "\n"
    "::array_global =\n"
    "    topindent \"var \" name \" = {\" nl indent\n"
    "        [row: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "    dedent topindent \"}\" nl;\n"
    "\n"
    "::array_elem = array \"[\" index \"]\";\n"
    "\n"
    "::enum =\n"
    "    \"const (\" nl indent\n"
    "        [elem{0}:    topindent elem \" = \" (.init ? init : \"iota\") nl]\n"
    "        [elem{1:-1}: topindent elem (.init ? \" = \" init) nl]\n"
    "    dedent \")\" nl;\n"
    "\n"
    "::enum_elem = name;\n"
    "\n"
    "::assign = topindent lhs \" = \" rhs nl;\n"
    "\n"
    "::type_int = \"int\";\n"
    "::type_uint = \"uint\";\n"
    "::type_cond_enum = <undefined>;\n"
    "::type_yybm = \"byte\";\n"
    "::type_yytarget = <undefined>;\n"
    "\n"
    "::cmp_eq = \"==\";\n"
    "::cmp_ne = \"!=\";\n"
    "::cmp_lt = \"<\";\n"
    "::cmp_gt = \">\";\n"
    "::cmp_le = \"<=\";\n"
    "::cmp_ge = \">=\";\n"
    "\n"
    "::if_then_else =\n"
    "    [branch{0}: topindent \"if (\" cond \") {\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent \"} else \" (.cond ? \"if (\" cond \") \") \"{\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::if_then_else_oneline = <undefined>;\n"
    "\n"
    "::switch =\n"
    "    topindent \"switch (\" expr \") {\" nl\n"
    "    [case: case]\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::switch_cases =\n"
    "    [case{0:-2}: topindent case nl\n"
    "        indent topindent \"fallthrough\" dedent nl]\n"
    "    [case{-1}: topindent case nl]\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "::switch_cases_oneline = <undefined>;\n"
    "\n"
    "::switch_case_range = \"case \" [val{0}: val] [val{1:-1}: \",\" val] \":\";\n"
    "\n"
    "::switch_case_default = \"default:\";\n"
    "\n"
    "::loop =\n"
    "    (.loop_label ? label \":\" nl)\n"
    "    topindent \"for {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "::continue = topindent \"continue\" (.loop_label ? \" \" label) nl;\n"
    "\n"
    "::goto = topindent \"goto \" label nl;\n"
    "\n"
    "::fndecl = <undefined>;\n"
    "\n"
    "::fndef =\n"
    "    topindent \"func \" name \"(\"\n"
    "        [arg{0:-2}: argname \" \" argtype \", \"]\n"
    "        [arg{-1}:   argname \" \" argtype]\n"
    "    \")\" (.type ? \" \" type) \" {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    \"}\" nl;\n"
    "\n"
    "::fncall =\n"
    "    topindent (.retval ? retval \" = \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \")\" nl;\n"
    "\n"
    "::tailcall =\n"
    "    topindent (.retval ? \"return \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \")\" nl;\n"
    "\n"
    "::recursive_functions = [fn: fndef nl];\n"
    "\n"
    "::fingerprint =\n"
    "    \"// Code generated by re2go\" (.version ? \" \" version) (.date ? \" on \" date) \", DO NOT EDIT.\" nl;\n"
    "\n"
    "::line_info = \"//line \\\"\" file \"\\\":\" line nl;\n"
    "\n"
    "::abort = topindent \"panic(\\\"internal lexer error\\\")\" nl;\n"
    "\n"
    "::yydebug =\n"
    "    topindent (.api.generic\n"
    "        ? YYDEBUG (.api_style.functions ? \"()\")\n"
    "    : (.api.record\n"
    "        ? YYDEBUG \"(\" yyrecord \")\"\n"
    "        : YYDEBUG \"(\" state \", \" yych \")\"\n"
    "    )) nl;\n"
    "\n"
    "::yypeek =\n"
    "    topindent yych (.code_model.recursive_functions ? \" := \" : \" = \") (.api.generic\n"
    "        ? YYPEEK (.api_style.functions ? \"()\")\n"
    "        : (.cast ? YYCTYPE \"(\") YYINPUT \"[\" YYCURSOR \"]\" (.cast ? \")\")\n"
    "    ) nl;\n"
    "\n"
    "::yyskip =\n"
    "    topindent (.api.generic\n"
    "        ? YYSKIP (.api_style.functions ? \"()\")\n"
    "        : YYCURSOR \" += 1\"\n"
    "    ) nl;\n"
    "\n"
    "::yybackup =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUP (.api_style.functions ? \"()\")\n"
    "        : YYMARKER \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yybackupctx =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUPCTX (.api_style.functions ? \"()\")\n"
    "        : YYCTXMARKER \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yyskip_yypeek = <undefined>;\n"
    "::yypeek_yyskip = <undefined>;\n"
    "::yyskip_yybackup = <undefined>;\n"
    "::yybackup_yyskip = <undefined>;\n"
    "::yybackup_yypeek = <undefined>;\n"
    "::yyskip_yybackup_yypeek = <undefined>;\n"
    "::yybackup_yypeek_yyskip = <undefined>;\n"
    "\n"
    "::yyrestore =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORE (.api_style.functions ? \"()\")\n"
    "        : YYCURSOR \" = \" YYMARKER\n"
    "    ) nl;\n"
    "\n"
    "::yyrestorectx =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORECTX (.api_style.functions ? \"()\")\n"
    "        : YYCURSOR \" = \" YYCTXMARKER\n"
    "    ) nl;\n"
    "\n"
    "::yyrestoretag =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORETAG (.api_style.functions ? \"(\" tag \")\")\n"
    "        : YYCURSOR \" = \" tag\n"
    "    ) nl;\n"
    "\n"
    "::yyshift =\n"
    "    topindent (.api.generic\n"
    "        ? YYSHIFT (.api_style.functions ? \"(-\" offset \")\")\n"
    "        : YYCURSOR \" -= \" offset\n"
    "    ) nl;\n"
    "\n"
    "::yyshiftstag =\n"
    "    (.nested ? topindent \"if (\" tag \" != \" neg \") {\" nl indent)\n"
    "        topindent (.api.generic\n"
    "            ? YYSHIFTSTAG (.api_style.functions ? \"(\" tag \", -\" offset \")\")\n"
    "            : tag \" -= \" offset\n"
    "        ) nl\n"
    "    (.nested ? dedent topindent \"}\" nl);\n"
    "\n"
    "::yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG (.api_style.functions ? \"(\" tag \", -\" offset \")\") nl;\n"
    "\n"
    "::yystagp =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGP (.api_style.functions ? \"(\" tag \")\")\n"
    "        : tag \" = \" YYCURSOR\n"
    "    ) nl;\n"
    "\n"
    "::yymtagp =\n"
    "    topindent YYMTAGP (.api_style.functions ? \"(\" tag \")\") nl;\n"
    "\n"
    "::yystagn =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGN (.api_style.functions ? \"(\" tag \")\")\n"
    "        : tag \" = \" neg\n"
    "    ) nl;\n"
    "\n"
    "::yymtagn =\n"
    "    topindent YYMTAGN (.api_style.functions ? \"(\" tag \")\") nl;\n"
    "\n"
    "::yycopystag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYSTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs\n"
    "    ) nl;\n"
    "\n"
    "::yycopymtag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYMTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs\n"
    "    ) nl;\n"
    "\n"
    "::yygetaccept =\n"
    "    (.api.generic\n"
    "        ? YYGETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \".\") var);\n"
    "\n"
    "::yysetaccept =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \".\")\n"
    "            var \" = \" val\n"
    "    ) nl;\n"
    "\n"
    "::yygetcond =\n"
    "    (.api.generic\n"
    "        ? YYGETCOND (.api_style.functions ? \"()\")\n"
    "        : (.api.record ? yyrecord \".\") var);\n"
    "\n"
    "::yysetcond =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETCOND (.api_style.functions ? \"(\" val \")\")\n"
    "        : (.api.record ? yyrecord \".\") var \" = \" val \n"
    "    ) nl;\n"
    "\n"
    "::yygetstate =\n"
    "    (.api.generic\n"
    "        ? YYGETSTATE (.api_style.functions ? \"()\")\n"
    "        : (.api.record ? yyrecord \".\") var);\n"
    "\n"
    "::yysetstate =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETSTATE (.api_style.functions ? \"(\" val \")\")\n"
    "        : (.api.record ? yyrecord \".\") var \" = \" val\n"
    "    ) nl;\n"
    "\n"
    "::yylessthan =\n"
    "    (.api.generic\n"
    "        ? YYLESSTHAN (.api_style.functions ? \"(\" need \")\")\n"
    "        : (.many\n"
    "            ? \"(\" YYLIMIT \" - \" YYCURSOR \") < \" need\n"
    "            : YYLIMIT \" <= \" YYCURSOR));\n"
    "\n"
    "::yybm_filter = yych \" & ~0xFF\";\n"
    "\n"
    "::yybm_match = \"(\" yybm \"[\" offset \"+\" yych \"] & \" mask \") != 0\";\n"
    ;
