/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i --tags --no-lookahead --input custom

{
	YYCTYPE yych;
	YYSTAGP(yyt1);
	if (YYLESSTHAN(1)) YYFILL(1);
	yych = YYPEEK();
	YYSKIP();
	switch (yych) {
	case 'a':	goto yy2;
	default:
		YYSTAGN(yyt1);
		goto yy2;
	}
yy2:
	a = yyt1;
	YYSTAGP(b);
	{}
}

tags/lost_tag.re:4:19: warning: tag 'a' has 2nd degree of nondeterminism [-Wnondeterministic-tags]
