/* Generated by re2c */
// re2c $INPUT -o $OUTPUT --recursive-functions -i
#include <assert.h>


int yy0(const char* YYCURSOR, int count);
int yy1(const char* YYCURSOR, int count);
int yy2(const char* YYCURSOR, int count);
int yy3(const char* YYCURSOR, int count);
int yy4(const char* YYCURSOR, int count);
int yy5(const char* YYCURSOR, int count);
int yy6(const char* YYCURSOR, int count);
int lex(const char* YYCURSOR, int count);

int yy0(const char* YYCURSOR, int count) {
	char yych = *YYCURSOR++;
	switch (yych) {
		case 0x00: return yy1(YYCURSOR, count);
		case ' ': return yy3(YYCURSOR, count);
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': return yy5(YYCURSOR, count);
		default: return yy2(YYCURSOR, count);
	}
}

int yy1(const char* YYCURSOR, int count) {
	return count;
}

int yy2(const char* YYCURSOR, int count) {
	return -1;
}

int yy3(const char* YYCURSOR, int count) {
	char yych = *YYCURSOR;
	switch (yych) {
		case ' ':
			++YYCURSOR;
			return yy3(YYCURSOR, count);
		default: return yy4(YYCURSOR, count);
	}
}

int yy4(const char* YYCURSOR, int count) {
	return lex(YYCURSOR, count);
}

int yy5(const char* YYCURSOR, int count) {
	char yych = *YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
			++YYCURSOR;
			return yy5(YYCURSOR, count);
		default: return yy6(YYCURSOR, count);
	}
}

int yy6(const char* YYCURSOR, int count) {
	return lex(YYCURSOR, ++count);
}

int lex(const char* YYCURSOR, int count) {
	return yy0(YYCURSOR, count);
}



int main()
{
    assert(lex("", 0) == 0);
    assert(lex("one two three", 0) == 3);
    assert(lex("f0ur", 0) == -1);
    return 0;
}
