// Code generated by re2c, DO NOT EDIT.
//go:generate re2go -f $INPUT -o $OUTPUT --loop-switch -i



	yystate := YYGETSTATE
	for {
		switch (yystate) {
		case -1,0:
			YYSETSTATE
			if (YYLESSTHAN) {
				YYFILL
			}
			yych = YYPEEK
			YYSKIP
			switch (yych) {
			case 'a':
				yystate = 2
				continue
			default:
				yystate = 1
				continue
			}
		case 1:
			YYSETSTATE
			{ * }
		case 2:
			YYSETSTATE
			{ a }
		case 3:
			yystate = 0
			continue
		default:
			panic("internal lexer error")
		}
	}




	yystate := YYGETSTATE
	for {
		switch (yystate) {
		case -1,0:
			yych = YYPEEK
			switch (yych) {
			case 'b':
				YYSKIP
				yystate = 2
				continue
			default:
				if (YYLESSTHAN) {
					YYSETSTATE
					YYFILL
				}
				YYSKIP
				yystate = 1
				continue
			}
		case 1:
			YYSETSTATE
			{ * }
		case 2:
			YYSETSTATE
			{ b }
		case 3:
			YYSETSTATE
			{ $ }
		case 4:
			if (YYLESSTHAN) {
				yystate = 3
				continue
			}
			yystate = 0
			continue
		default:
			panic("internal lexer error")
		}
	}

