/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i --tags --stadfa

{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 18) YYFILL(18);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a': goto yy2;
		case 'b': goto yy4;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
	{}
yy2:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy5;
		case 'b': goto yy6;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy3:
	x = yyt1;
	y = yyt2;
	{}
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy6;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy7;
		case 'b': goto yy8;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy8;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy9;
		case 'b': goto yy10;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy10;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy12;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy12;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy13;
		case 'b': goto yy14;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy14;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy15;
		case 'b': goto yy16;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy16;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy17;
		case 'b': goto yy18;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy18;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy19;
		case 'b': goto yy20;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy20;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy21;
		case 'b': goto yy22;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy22;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy23;
		case 'b': goto yy24;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy24;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy25;
		case 'b': goto yy26;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy26;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy27;
		case 'b': goto yy28;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy28;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy29;
		case 'b': goto yy30;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy30;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy31;
		case 'b': goto yy32;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy32;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy33;
		case 'b': goto yy34;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy34;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy35;
		case 'b': goto yy36;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy36;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy37;
		default:
			yyt2 = NULL;
			yyt1 = YYCURSOR;
			goto yy3;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a':
		case 'b': goto yy37;
		default:
			yyt1 = yyt2 = NULL;
			goto yy3;
	}
yy37:
	++YYCURSOR;
	yyt1 = yyt2 = NULL;
	goto yy3;
}

stadfa/stadfa_23.re:4:26: warning: rule matches empty string [-Wmatch-empty-string]
stadfa/stadfa_23.re:5:3: warning: unreachable rule (shadowed by rule at line 4) [-Wunreachable-rules]
