/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i

{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a': goto yy2;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
	{}
yy2:
	++YYCURSOR;
	{}
}





{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'b': goto yy5;
		default: goto yy4;
	}
yy4:
	++YYCURSOR;
	{}
yy5:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'b') goto yy7;
	++YYCURSOR;
	{}
yy7:
	++YYCURSOR;
	{}
}





{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'c': goto yy10;
		default: goto yy9;
	}
yy9:
	++YYCURSOR;
	{}
yy10:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'c') goto yy12;
	++YYCURSOR;
	{}
yy12:
	++YYCURSOR;
	{}
}



{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'd': goto yy15;
		default: goto yy14;
	}
yy14:
	++YYCURSOR;
	{}
yy15:
	++YYCURSOR;
	{}
}



{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'c': goto yy18;
		default: goto yy17;
	}
yy17:
	++YYCURSOR;
	{}
yy18:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'c') goto yy20;
	++YYCURSOR;
	{}
yy20:
	++YYCURSOR;
	{}
}





{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'e': goto yy23;
		default: goto yy22;
	}
yy22:
	++YYCURSOR;
	{}
yy23:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'e') goto yy25;
	++YYCURSOR;
	{}
yy25:
	++YYCURSOR;
	{}
}



{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'f': goto yy28;
		default: goto yy27;
	}
yy27:
	++YYCURSOR;
	{}
yy28:
	++YYCURSOR;
	{}
}



{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'e': goto yy31;
		default: goto yy30;
	}
yy30:
	++YYCURSOR;
	{}
yy31:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'e') goto yy33;
	++YYCURSOR;
	{}
yy33:
	++YYCURSOR;
	{}
}







{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'h': goto yy36;
		default: goto yy35;
	}
yy35:
	++YYCURSOR;
	{}
yy36:
	++YYCURSOR;
	{}
}


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == 'h') goto yy38;
	++YYCURSOR;
	{}
yy38:
	++YYCURSOR;
	{}
}

