/* Generated by re2c 0.16 on Thu Feb  9 12:04:05 2017 */
#line 1 "../src/parse/lex_conf.re"
#include "src/util/c99_stdint.h"
#include <string>

#include "src/codegen/output.h"
#include "src/ir/regexp/encoding/enc.h"
#include "src/parse/scanner.h"
#include "src/util/s_to_n32_unsafe.h"

namespace re2c
{

// global re2c config (affects the whole file)
#line 34 "../src/parse/lex_conf.re"


void Scanner::lex_conf ()
{
	tok = cur;

#line 23 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 27) fill(27);
	yych = (unsigned char)*cur;
	switch (yych) {
	case 'c':	goto yy4;
	case 'd':	goto yy5;
	case 'f':	goto yy6;
	case 'i':	goto yy7;
	case 'l':	goto yy8;
	case 's':	goto yy9;
	case 't':	goto yy10;
	case 'v':	goto yy11;
	case 'y':	goto yy12;
	default:	goto yy2;
	}
yy2:
	++cur;
yy3:
#line 40 "../src/parse/lex_conf.re"
	{ fatal ((tok - pos) - tchar, "unrecognized configuration"); }
#line 80 "src/parse/lex_conf.cc"
yy4:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'g') goto yy13;
	if (yych == 'o') goto yy15;
	goto yy3;
yy5:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'e') goto yy16;
	goto yy3;
yy6:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'l') goto yy17;
	goto yy3;
yy7:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'n') goto yy18;
	goto yy3;
yy8:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy19;
	goto yy3;
yy9:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 't') goto yy20;
	goto yy3;
yy10:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy21;
	goto yy3;
yy11:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy22;
	goto yy3;
yy12:
	yyaccept = 0;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'y') goto yy23;
	goto yy3;
yy13:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy24;
yy14:
	cur = ptr;
	if (yyaccept <= 11) {
		if (yyaccept <= 5) {
			if (yyaccept <= 2) {
				if (yyaccept <= 1) {
					if (yyaccept == 0) {
						goto yy3;
					} else {
						goto yy101;
					}
				} else {
					goto yy103;
				}
			} else {
				if (yyaccept <= 4) {
					if (yyaccept == 3) {
						goto yy105;
					} else {
						goto yy107;
					}
				} else {
					goto yy109;
				}
			}
		} else {
			if (yyaccept <= 8) {
				if (yyaccept <= 7) {
					if (yyaccept == 6) {
						goto yy113;
					} else {
						goto yy116;
					}
				} else {
					goto yy118;
				}
			} else {
				if (yyaccept <= 10) {
					if (yyaccept == 9) {
						goto yy120;
					} else {
						goto yy122;
					}
				} else {
					goto yy124;
				}
			}
		}
	} else {
		if (yyaccept <= 17) {
			if (yyaccept <= 14) {
				if (yyaccept <= 13) {
					if (yyaccept == 12) {
						goto yy126;
					} else {
						goto yy192;
					}
				} else {
					goto yy286;
				}
			} else {
				if (yyaccept <= 16) {
					if (yyaccept == 15) {
						goto yy364;
					} else {
						goto yy441;
					}
				} else {
					goto yy552;
				}
			}
		} else {
			if (yyaccept <= 20) {
				if (yyaccept <= 19) {
					if (yyaccept == 18) {
						goto yy612;
					} else {
						goto yy655;
					}
				} else {
					goto yy662;
				}
			} else {
				if (yyaccept == 21) {
					goto yy747;
				} else {
					goto yy750;
				}
			}
		}
	}
yy15:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy25;
	goto yy14;
yy16:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy26;
	goto yy14;
yy17:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy27;
	goto yy14;
yy18:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy28;
	goto yy14;
yy19:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy29;
	goto yy14;
yy20:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy30;
	goto yy14;
yy21:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy31;
	goto yy14;
yy22:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy32;
	goto yy14;
yy23:
	yych = (unsigned char)*++cur;
	if (yych <= 'c') {
		if (yych <= 'a') goto yy14;
		if (yych <= 'b') goto yy33;
		goto yy34;
	} else {
		if (yych == 'f') goto yy35;
		goto yy14;
	}
yy24:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy36;
	goto yy14;
yy25:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy37;
	goto yy14;
yy26:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy38;
	goto yy14;
yy27:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy39;
	goto yy14;
yy28:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy40;
	goto yy14;
yy29:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy41;
	goto yy14;
yy30:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy42;
	if (yych == 't') goto yy43;
	goto yy14;
yy31:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy44;
	goto yy14;
yy32:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy45;
	goto yy14;
yy33:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy46;
	goto yy14;
yy34:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy47;
	goto yy14;
yy35:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy48;
	goto yy14;
yy36:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy49;
	goto yy14;
yy37:
	yych = (unsigned char)*++cur;
	if (yych <= 'd') {
		if (yych == ':') goto yy50;
		goto yy14;
	} else {
		if (yych <= 'e') goto yy51;
		if (yych == 'p') goto yy52;
		goto yy14;
	}
yy38:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy53;
	goto yy14;
yy39:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy54;
	goto yy14;
yy40:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy55;
	goto yy14;
yy41:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy56;
	goto yy14;
yy42:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy57;
	goto yy14;
yy43:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy58;
	goto yy14;
yy44:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy59;
	goto yy14;
yy45:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy60;
	goto yy14;
yy46:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy61;
	goto yy14;
yy47:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy62;
	goto yy14;
yy48:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy63;
	goto yy14;
yy49:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy64;
	goto yy14;
yy50:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy65;
	if (yych == 'g') goto yy66;
	goto yy14;
yy51:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy67;
	goto yy14;
yy52:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy68;
	goto yy14;
yy53:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy69;
	goto yy14;
yy54:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy70;
	goto yy14;
yy55:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy71;
	goto yy14;
yy56:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy72;
	if (yych == 'p') goto yy73;
	goto yy14;
yy57:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy74;
	goto yy14;
yy58:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy75;
	goto yy14;
yy59:
	yych = (unsigned char)*++cur;
	if (yych <= 'e') {
		if (yych <= 'c') goto yy14;
		if (yych <= 'd') goto yy76;
		goto yy77;
	} else {
		if (yych == 'p') goto yy78;
		goto yy14;
	}
yy60:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy79;
	goto yy14;
yy61:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy80;
	goto yy14;
yy62:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy81;
	if (yych == 'e') goto yy82;
	goto yy14;
yy63:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy83;
	goto yy14;
yy64:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy84;
	goto yy14;
yy65:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy85;
	goto yy14;
yy66:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy86;
	goto yy14;
yy67:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy87;
	goto yy14;
yy68:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy88;
	goto yy14;
yy69:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy89;
	goto yy14;
yy70:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case '8':	goto yy90;
	case 'D':	goto yy92;
	case 'F':	goto yy94;
	case 'S':	goto yy96;
	case 'T':	goto yy98;
	case 'b':	goto yy100;
	case 'c':	goto yy102;
	case 'd':	goto yy104;
	case 'e':	goto yy106;
	case 'f':	goto yy108;
	case 'g':	goto yy110;
	case 'i':	goto yy112;
	case 'n':	goto yy114;
	case 'o':	goto yy115;
	case 'r':	goto yy117;
	case 's':	goto yy119;
	case 't':	goto yy121;
	case 'u':	goto yy123;
	case 'w':	goto yy125;
	case 'x':	goto yy127;
	default:	goto yy14;
	}
yy71:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy129;
	goto yy14;
yy72:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy130;
	goto yy14;
yy73:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy131;
	goto yy14;
yy74:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy132;
	goto yy14;
yy75:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy133;
	if (yych == 'n') goto yy134;
	goto yy14;
yy76:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy135;
	goto yy14;
yy77:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy136;
	goto yy14;
yy78:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy137;
	goto yy14;
yy79:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy138;
	goto yy14;
yy80:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy139;
	goto yy14;
yy81:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy140;
	goto yy14;
yy82:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy141;
	goto yy14;
yy83:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy142;
	goto yy14;
yy84:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy143;
	goto yy14;
yy85:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy144;
	goto yy14;
yy86:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy145;
	goto yy14;
yy87:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy146;
	goto yy14;
yy88:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy147;
	goto yy14;
yy89:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy148;
	goto yy14;
yy90:
	++cur;
#line 66 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF8);   return; }
#line 569 "src/parse/lex_conf.cc"
yy92:
	++cur;
#line 42 "../src/parse/lex_conf.re"
	{ opts.set_target(opt_t::DOT);      lex_conf_semicolon(); return; }
#line 574 "src/parse/lex_conf.cc"
yy94:
	++cur;
#line 49 "../src/parse/lex_conf.re"
	{ opts.set_FFlag(lex_conf_bool());              return; }
#line 579 "src/parse/lex_conf.cc"
yy96:
	++cur;
#line 43 "../src/parse/lex_conf.re"
	{ opts.set_target(opt_t::SKELETON); lex_conf_semicolon(); return; }
#line 584 "src/parse/lex_conf.cc"
yy98:
	++cur;
#line 54 "../src/parse/lex_conf.re"
	{ opts.set_tags(lex_conf_bool());               return; }
#line 589 "src/parse/lex_conf.cc"
yy100:
	yyaccept = 1;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'i') goto yy149;
yy101:
#line 45 "../src/parse/lex_conf.re"
	{ opts.set_bFlag(lex_conf_bool());              return; }
#line 597 "src/parse/lex_conf.cc"
yy102:
	yyaccept = 2;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy150;
	if (yych == 'o') goto yy151;
yy103:
#line 46 "../src/parse/lex_conf.re"
	{ opts.set_cFlag(lex_conf_bool());              return; }
#line 606 "src/parse/lex_conf.cc"
yy104:
	yyaccept = 3;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych <= 'd') goto yy105;
	if (yych <= 'e') goto yy152;
	if (yych <= 'f') goto yy153;
yy105:
#line 47 "../src/parse/lex_conf.re"
	{ opts.set_dFlag(lex_conf_bool());              return; }
#line 616 "src/parse/lex_conf.cc"
yy106:
	yyaccept = 4;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych <= 'c') {
		if (yych == 'a') goto yy154;
		if (yych >= 'c') goto yy155;
	} else {
		if (yych <= 'l') goto yy107;
		if (yych <= 'm') goto yy156;
		if (yych <= 'n') goto yy157;
	}
yy107:
#line 62 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::EBCDIC); return; }
#line 631 "src/parse/lex_conf.cc"
yy108:
	yyaccept = 5;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'l') goto yy158;
yy109:
#line 48 "../src/parse/lex_conf.re"
	{ opts.set_fFlag(lex_conf_bool());              return; }
#line 639 "src/parse/lex_conf.cc"
yy110:
	++cur;
#line 50 "../src/parse/lex_conf.re"
	{ opts.set_gFlag(lex_conf_bool());              return; }
#line 644 "src/parse/lex_conf.cc"
yy112:
	yyaccept = 6;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'n') goto yy159;
yy113:
#line 51 "../src/parse/lex_conf.re"
	{ opts.set_iFlag(lex_conf_bool());              return; }
#line 652 "src/parse/lex_conf.cc"
yy114:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy160;
	if (yych == 'o') goto yy161;
	goto yy14;
yy115:
	yyaccept = 7;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'u') goto yy162;
yy116:
#line 68 "../src/parse/lex_conf.re"
	{ opts.set_output_file(lex_conf_string()); return; }
#line 665 "src/parse/lex_conf.cc"
yy117:
	yyaccept = 8;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'e') goto yy163;
yy118:
#line 52 "../src/parse/lex_conf.re"
	{ opts.set_rFlag(lex_conf_bool());              return; }
#line 673 "src/parse/lex_conf.cc"
yy119:
	yyaccept = 9;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'k') goto yy164;
	if (yych == 't') goto yy165;
yy120:
#line 53 "../src/parse/lex_conf.re"
	{ opts.set_sFlag(lex_conf_bool());              return; }
#line 682 "src/parse/lex_conf.cc"
yy121:
	yyaccept = 10;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy166;
	if (yych == 'y') goto yy167;
yy122:
#line 69 "../src/parse/lex_conf.re"
	{ opts.set_header_file(lex_conf_string()); return; }
#line 691 "src/parse/lex_conf.cc"
yy123:
	yyaccept = 11;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'n') goto yy168;
	if (yych == 't') goto yy169;
yy124:
#line 63 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF32);  return; }
#line 700 "src/parse/lex_conf.cc"
yy125:
	yyaccept = 12;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'i') goto yy170;
yy126:
#line 64 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UCS2);   return; }
#line 708 "src/parse/lex_conf.cc"
yy127:
	++cur;
#line 65 "../src/parse/lex_conf.re"
	{ lex_conf_enc(Enc::UTF16);  return; }
#line 713 "src/parse/lex_conf.cc"
yy129:
	yych = (unsigned char)*++cur;
	if (yych <= 'r') goto yy14;
	if (yych <= 's') goto yy171;
	if (yych <= 't') goto yy172;
	goto yy14;
yy130:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy173;
	goto yy14;
yy131:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy174;
	goto yy14;
yy132:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy175;
	goto yy14;
yy133:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy176;
	goto yy14;
yy134:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy177;
	goto yy14;
yy135:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy178;
	goto yy14;
yy136:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy179;
	goto yy14;
yy137:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy180;
	goto yy14;
yy138:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy181;
	goto yy14;
yy139:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy182;
	goto yy14;
yy140:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy184;
	goto yy14;
yy141:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy185;
	goto yy14;
yy142:
	yych = (unsigned char)*++cur;
	if (yych <= 'd') {
		if (yych == 'c') goto yy186;
		goto yy14;
	} else {
		if (yych <= 'e') goto yy187;
		if (yych == 'p') goto yy188;
		goto yy14;
	}
yy143:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy189;
	goto yy14;
yy144:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy190;
	goto yy14;
yy145:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy191;
	goto yy14;
yy146:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy193;
	goto yy14;
yy147:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy194;
	goto yy14;
yy148:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy195;
	goto yy14;
yy149:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy196;
	goto yy14;
yy150:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy197;
	goto yy14;
yy151:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy198;
	goto yy14;
yy152:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy199;
	goto yy14;
yy153:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy200;
	goto yy14;
yy154:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy201;
	goto yy14;
yy155:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy202;
	goto yy14;
yy156:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy203;
	if (yych == 'p') goto yy204;
	goto yy14;
yy157:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy205;
	goto yy14;
yy158:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy206;
	goto yy14;
yy159:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy207;
	goto yy14;
yy160:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy208;
	goto yy14;
yy161:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy209;
	goto yy14;
yy162:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy210;
	goto yy14;
yy163:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy211;
	goto yy14;
yy164:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy212;
	goto yy14;
yy165:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy213;
	if (yych == 'o') goto yy214;
	goto yy14;
yy166:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy215;
	goto yy14;
yy167:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy216;
	goto yy14;
yy168:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy217;
	goto yy14;
yy169:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy218;
	goto yy14;
yy170:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy219;
	goto yy14;
yy171:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy220;
	goto yy14;
yy172:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy221;
	goto yy14;
yy173:
	yych = (unsigned char)*++cur;
	if (yych == 'F') goto yy222;
	if (yych == 'N') goto yy223;
	goto yy14;
yy174:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy224;
	goto yy14;
yy175:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy225;
	goto yy14;
yy176:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy226;
	goto yy14;
yy177:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy227;
	goto yy14;
yy178:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy228;
	goto yy14;
yy179:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy229;
	goto yy14;
yy180:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy230;
	goto yy14;
yy181:
	yych = (unsigned char)*++cur;
	if (yych == ':') goto yy231;
	goto yy14;
yy182:
	++cur;
#line 102 "../src/parse/lex_conf.re"
	{ opts.set_yybmHexTable (lex_conf_bool()); return; }
#line 941 "src/parse/lex_conf.cc"
yy184:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy232;
	goto yy14;
yy185:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy233;
	goto yy14;
yy186:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy235;
	goto yy14;
yy187:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy236;
	goto yy14;
yy188:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy237;
	goto yy14;
yy189:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy238;
	goto yy14;
yy190:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy239;
	goto yy14;
yy191:
	yyaccept = 13;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == '@') goto yy240;
yy192:
#line 86 "../src/parse/lex_conf.re"
	{ opts.set_condGoto         (lex_conf_string ()); return; }
#line 977 "src/parse/lex_conf.cc"
yy193:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy241;
	goto yy14;
yy194:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy242;
	goto yy14;
yy195:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case 'B':	goto yy244;
	case 'C':	goto yy245;
	case 'D':	goto yy246;
	case 'F':	goto yy247;
	case 'G':	goto yy248;
	case 'L':	goto yy249;
	case 'M':	goto yy250;
	case 'P':	goto yy251;
	case 'R':	goto yy252;
	case 'S':	goto yy253;
	default:	goto yy14;
	}
yy196:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy254;
	goto yy14;
yy197:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy255;
	goto yy14;
yy198:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy256;
	goto yy14;
yy199:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy257;
	goto yy14;
yy200:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy258;
	goto yy14;
yy201:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy259;
	goto yy14;
yy202:
	++cur;
	goto yy107;
yy203:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy260;
	goto yy14;
yy204:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy261;
	goto yy14;
yy205:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy262;
	goto yy14;
yy206:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy263;
	goto yy14;
yy207:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy264;
	goto yy14;
yy208:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy265;
	goto yy14;
yy209:
	yych = (unsigned char)*++cur;
	switch (yych) {
	case 'd':	goto yy266;
	case 'g':	goto yy267;
	case 'l':	goto yy268;
	case 'v':	goto yy269;
	default:	goto yy14;
	}
yy210:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy270;
	goto yy14;
yy211:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy271;
	goto yy14;
yy212:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy272;
	goto yy14;
yy213:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy273;
	goto yy14;
yy214:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy274;
	goto yy14;
yy215:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy98;
	goto yy14;
yy216:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy275;
	goto yy14;
yy217:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy276;
	goto yy14;
yy218:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy277;
	goto yy14;
yy219:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy278;
	goto yy14;
yy220:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy279;
	goto yy14;
yy221:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy280;
	goto yy14;
yy222:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy282;
	goto yy14;
yy223:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy283;
	goto yy14;
yy224:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy284;
	goto yy14;
yy225:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy285;
	goto yy14;
yy226:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy287;
	goto yy14;
yy227:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy288;
	goto yy14;
yy228:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy289;
	goto yy14;
yy229:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy290;
	goto yy14;
yy230:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy291;
	goto yy14;
yy231:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy292;
	goto yy14;
yy232:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy293;
	goto yy14;
yy233:
	++cur;
#line 152 "../src/parse/lex_conf.re"
	{ opts.set_bEmitYYCh      (lex_conf_bool()); return; }
#line 1157 "src/parse/lex_conf.cc"
yy235:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy294;
	goto yy14;
yy236:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy295;
	goto yy14;
yy237:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy296;
	goto yy14;
yy238:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy297;
	goto yy14;
yy239:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy298;
	goto yy14;
yy240:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy299;
	goto yy14;
yy241:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy300;
	goto yy14;
yy242:
	++cur;
#line 82 "../src/parse/lex_conf.re"
	{ opts.set_condPrefix       (lex_conf_string ()); return; }
#line 1190 "src/parse/lex_conf.cc"
yy244:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy301;
	goto yy14;
yy245:
	yych = (unsigned char)*++cur;
	if (yych <= 'S') {
		if (yych == 'O') goto yy302;
		goto yy14;
	} else {
		if (yych <= 'T') goto yy303;
		if (yych <= 'U') goto yy304;
		goto yy14;
	}
yy246:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy305;
	goto yy14;
yy247:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy306;
	goto yy14;
yy248:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy307;
	goto yy14;
yy249:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy308;
	if (yych == 'I') goto yy309;
	goto yy14;
yy250:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy310;
	goto yy14;
yy251:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy311;
	goto yy14;
yy252:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy312;
	goto yy14;
yy253:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy313;
	if (yych == 'K') goto yy314;
	goto yy14;
yy254:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy315;
	goto yy14;
yy255:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy316;
	goto yy14;
yy256:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy317;
	goto yy14;
yy257:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy318;
	goto yy14;
yy258:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy319;
	goto yy14;
yy259:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy320;
	goto yy14;
yy260:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy321;
	goto yy14;
yy261:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy322;
	goto yy14;
yy262:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy323;
	goto yy14;
yy263:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy324;
	goto yy14;
yy264:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy325;
	goto yy14;
yy265:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy327;
	goto yy14;
yy266:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy328;
	goto yy14;
yy267:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy329;
	goto yy14;
yy268:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy330;
	goto yy14;
yy269:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy331;
	goto yy14;
yy270:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy332;
	goto yy14;
yy271:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy333;
	goto yy14;
yy272:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy334;
	goto yy14;
yy273:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy335;
	goto yy14;
yy274:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy336;
	goto yy14;
yy275:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy337;
	goto yy14;
yy276:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy338;
	goto yy14;
yy277:
	yych = (unsigned char)*++cur;
	if (yych == '1') goto yy339;
	if (yych == '8') goto yy90;
	goto yy14;
yy278:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy340;
	goto yy14;
yy279:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy341;
	goto yy14;
yy280:
	++cur;
#line 137 "../src/parse/lex_conf.re"
	{
		const int32_t n = lex_conf_number ();
		if (n < 0)
		{
			fatal ("configuration 'indent:top' must be nonnegative");
		}
		opts.set_topIndent (static_cast<uint32_t> (n));
		return;
	}
#line 1356 "src/parse/lex_conf.cc"
yy282:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy342;
	goto yy14;
yy283:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy343;
	goto yy14;
yy284:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy344;
	goto yy14;
yy285:
	yyaccept = 14;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych <= 0x1F) {
		if (yych == '\t') {
			ctx = cur;
			goto yy346;
		}
	} else {
		if (yych <= ' ') {
			ctx = cur;
			goto yy346;
		}
		if (yych == '=') {
			ctx = cur;
			goto yy348;
		}
	}
yy286:
#line 165 "../src/parse/lex_conf.re"
	{ opts.set_startlabel       (lex_conf_string()); return; }
#line 1390 "src/parse/lex_conf.cc"
yy287:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy350;
	goto yy14;
yy288:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy352;
	goto yy14;
yy289:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy353;
	goto yy14;
yy290:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy354;
	goto yy14;
yy291:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy355;
	goto yy14;
yy292:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy357;
	goto yy14;
yy293:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy358;
	goto yy14;
yy294:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy359;
	goto yy14;
yy295:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy360;
	goto yy14;
yy296:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy361;
	goto yy14;
yy297:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy362;
	goto yy14;
yy298:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy363;
	goto yy14;
yy299:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy365;
	goto yy14;
yy300:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy366;
	goto yy14;
yy301:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy367;
	goto yy14;
yy302:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy368;
	if (yych == 'P') goto yy369;
	goto yy14;
yy303:
	yych = (unsigned char)*++cur;
	if (yych <= 'W') goto yy14;
	if (yych <= 'X') goto yy370;
	if (yych <= 'Y') goto yy371;
	goto yy14;
yy304:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy372;
	goto yy14;
yy305:
	yych = (unsigned char)*++cur;
	if (yych == 'B') goto yy373;
	goto yy14;
yy306:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy374;
	goto yy14;
yy307:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy375;
	goto yy14;
yy308:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy376;
	goto yy14;
yy309:
	yych = (unsigned char)*++cur;
	if (yych == 'M') goto yy377;
	goto yy14;
yy310:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy378;
	goto yy14;
yy311:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy379;
	goto yy14;
yy312:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy380;
	goto yy14;
yy313:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy381;
	goto yy14;
yy314:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy382;
	goto yy14;
yy315:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy383;
	goto yy14;
yy316:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy384;
	goto yy14;
yy317:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy385;
	goto yy14;
yy318:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy386;
	goto yy14;
yy319:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy387;
	goto yy14;
yy320:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy388;
	goto yy14;
yy321:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy389;
	goto yy14;
yy322:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy390;
	goto yy14;
yy323:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy391;
	goto yy14;
yy324:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy392;
	goto yy14;
yy325:
	++cur;
#line 72 "../src/parse/lex_conf.re"
	{ lex_conf_input();            return; }
#line 1550 "src/parse/lex_conf.cc"
yy327:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy393;
	goto yy14;
yy328:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy394;
	goto yy14;
yy329:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy395;
	goto yy14;
yy330:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy396;
	goto yy14;
yy331:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy397;
	goto yy14;
yy332:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy398;
	goto yy14;
yy333:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy399;
	goto yy14;
yy334:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy400;
	goto yy14;
yy335:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy401;
	goto yy14;
yy336:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy402;
	goto yy14;
yy337:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy403;
	goto yy14;
yy338:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy404;
	goto yy14;
yy339:
	yych = (unsigned char)*++cur;
	if (yych == '6') goto yy127;
	goto yy14;
yy340:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy405;
	goto yy14;
yy341:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy406;
	goto yy14;
yy342:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy407;
	goto yy14;
yy343:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy408;
	goto yy14;
yy344:
	++cur;
#line 161 "../src/parse/lex_conf.re"
	{ opts.set_labelPrefix (lex_conf_string ()); return; }
#line 1623 "src/parse/lex_conf.cc"
yy346:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 64) {
		goto yy346;
	}
	if (yych != '=') goto yy14;
yy348:
	++cur;
	if ((lim - cur) < 2) fill(2);
	yych = (unsigned char)*cur;
	if (yych <= ',') {
		if (yych <= '\t') {
			if (yych <= 0x08) goto yy14;
			goto yy348;
		} else {
			if (yych == ' ') goto yy348;
			goto yy14;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '-') goto yy410;
			goto yy14;
		} else {
			if (yych <= '0') goto yy411;
			if (yych <= '9') goto yy413;
			goto yy14;
		}
	}
yy350:
	++cur;
#line 97 "../src/parse/lex_conf.re"
	{ opts.set_bUseStateAbort  (lex_conf_bool()); return; }
#line 1658 "src/parse/lex_conf.cc"
yy352:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy415;
	goto yy14;
yy353:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy416;
	goto yy14;
yy354:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy418;
	goto yy14;
yy355:
	++cur;
#line 132 "../src/parse/lex_conf.re"
	{ opts.set_tags_prefix    (lex_conf_string ()); return; }
#line 1675 "src/parse/lex_conf.cc"
yy357:
	yych = (unsigned char)*++cur;
	if (yych <= 'c') {
		if (yych <= '`') goto yy14;
		if (yych <= 'a') goto yy419;
		if (yych <= 'b') goto yy420;
		goto yy421;
	} else {
		if (yych <= 'r') goto yy14;
		if (yych <= 's') goto yy422;
		if (yych <= 't') goto yy423;
		goto yy14;
	}
yy358:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy424;
	goto yy14;
yy359:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy425;
	goto yy14;
yy360:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy427;
	goto yy14;
yy361:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy428;
	goto yy14;
yy362:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy429;
	goto yy14;
yy363:
	yyaccept = 15;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == '@') goto yy430;
yy364:
#line 84 "../src/parse/lex_conf.re"
	{ opts.set_condDivider      (lex_conf_string ()); return; }
#line 1716 "src/parse/lex_conf.cc"
yy365:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy431;
	goto yy14;
yy366:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy432;
	goto yy14;
yy367:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy433;
	goto yy14;
yy368:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy434;
	goto yy14;
yy369:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy435;
	goto yy14;
yy370:
	yych = (unsigned char)*++cur;
	if (yych == 'M') goto yy436;
	goto yy14;
yy371:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy437;
	goto yy14;
yy372:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy438;
	goto yy14;
yy373:
	yych = (unsigned char)*++cur;
	if (yych == 'U') goto yy439;
	goto yy14;
yy374:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy440;
	goto yy14;
yy375:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy442;
	if (yych == 'S') goto yy443;
	goto yy14;
yy376:
	yych = (unsigned char)*++cur;
	if (yych == 'S') goto yy444;
	goto yy14;
yy377:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy445;
	goto yy14;
yy378:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy446;
	goto yy14;
yy379:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy447;
	goto yy14;
yy380:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy449;
	goto yy14;
yy381:
	yych = (unsigned char)*++cur;
	if (yych == 'C') goto yy450;
	if (yych == 'S') goto yy451;
	goto yy14;
yy382:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy452;
	goto yy14;
yy383:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy454;
	goto yy14;
yy384:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy455;
	goto yy14;
yy385:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy456;
	goto yy14;
yy386:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy457;
	goto yy14;
yy387:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy458;
	goto yy14;
yy388:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy459;
	goto yy14;
yy389:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy460;
	goto yy14;
yy390:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy461;
	goto yy14;
yy391:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy462;
	goto yy14;
yy392:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy463;
	goto yy14;
yy393:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy464;
	goto yy14;
yy394:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy465;
	goto yy14;
yy395:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy466;
	goto yy14;
yy396:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy467;
	goto yy14;
yy397:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy468;
	goto yy14;
yy398:
	++cur;
	goto yy116;
yy399:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy469;
	goto yy14;
yy400:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy470;
	goto yy14;
yy401:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy471;
	goto yy14;
yy402:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy472;
	goto yy14;
yy403:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy473;
	goto yy14;
yy404:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy474;
	goto yy14;
yy405:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy475;
	goto yy14;
yy406:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy476;
	goto yy14;
yy407:
	yych = (unsigned char)*++cur;
	if (yych == 'L') goto yy478;
	goto yy14;
yy408:
	++cur;
#line 96 "../src/parse/lex_conf.re"
	{ opts.set_yynext          (lex_conf_string ()); return; }
#line 1894 "src/parse/lex_conf.cc"
yy410:
	yych = (unsigned char)*++cur;
	if (yych <= '0') goto yy14;
	if (yych <= '9') goto yy413;
	goto yy14;
yy411:
	++cur;
yy412:
	cur = ctx;
#line 164 "../src/parse/lex_conf.re"
	{ opts.set_startlabel_force (lex_conf_bool());   return; }
#line 1906 "src/parse/lex_conf.cc"
yy413:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy413;
	}
	goto yy412;
yy415:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy479;
	goto yy14;
yy416:
	++cur;
#line 131 "../src/parse/lex_conf.re"
	{ opts.set_tags_default   (lex_conf_string ()); return; }
#line 1923 "src/parse/lex_conf.cc"
yy418:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy480;
	goto yy14;
yy419:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy481;
	goto yy14;
yy420:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy482;
	goto yy14;
yy421:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy484;
	if (yych == 't') goto yy486;
	goto yy14;
yy422:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy487;
	goto yy14;
yy423:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy488;
	goto yy14;
yy424:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy489;
	goto yy14;
yy425:
	++cur;
#line 159 "../src/parse/lex_conf.re"
	{ opts.set_fill_check   (lex_conf_bool()); return; }
#line 1957 "src/parse/lex_conf.cc"
yy427:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy490;
	goto yy14;
yy428:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy492;
	goto yy14;
yy429:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy493;
	goto yy14;
yy430:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy494;
	goto yy14;
yy431:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy495;
	goto yy14;
yy432:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy497;
	goto yy14;
yy433:
	yych = (unsigned char)*++cur;
	if (yych == 'U') goto yy499;
	goto yy14;
yy434:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy500;
	goto yy14;
yy435:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy501;
	goto yy14;
yy436:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy502;
	goto yy14;
yy437:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy503;
	goto yy14;
yy438:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy505;
	goto yy14;
yy439:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy506;
	goto yy14;
yy440:
	yyaccept = 16;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == ':') goto yy508;
	if (yych == '@') goto yy509;
yy441:
#line 154 "../src/parse/lex_conf.re"
	{ opts.set_fill         (lex_conf_string ()); return; }
#line 2018 "src/parse/lex_conf.cc"
yy442:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy510;
	goto yy14;
yy443:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy511;
	goto yy14;
yy444:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy512;
	goto yy14;
yy445:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy513;
	goto yy14;
yy446:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy515;
	goto yy14;
yy447:
	++cur;
#line 120 "../src/parse/lex_conf.re"
	{ opts.set_yypeek       (lex_conf_string ()); return; }
#line 2043 "src/parse/lex_conf.cc"
yy449:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy516;
	goto yy14;
yy450:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy517;
	goto yy14;
yy451:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy518;
	goto yy14;
yy452:
	++cur;
#line 121 "../src/parse/lex_conf.re"
	{ opts.set_yyskip       (lex_conf_string ()); return; }
#line 2060 "src/parse/lex_conf.cc"
yy454:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy519;
	goto yy14;
yy455:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy520;
	if (yych == 'v') goto yy521;
	goto yy14;
yy456:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy522;
	goto yy14;
yy457:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy523;
	goto yy14;
yy458:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy524;
	goto yy14;
yy459:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy525;
	goto yy14;
yy460:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy92;
	goto yy14;
yy461:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy526;
	goto yy14;
yy462:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy527;
	goto yy14;
yy463:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy528;
	goto yy14;
yy464:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy529;
	goto yy14;
yy465:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy530;
	goto yy14;
yy466:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy531;
	goto yy14;
yy467:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy532;
	goto yy14;
yy468:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy533;
	goto yy14;
yy469:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy534;
	goto yy14;
yy470:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy96;
	goto yy14;
yy471:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy535;
	goto yy14;
yy472:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy536;
	goto yy14;
yy473:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy537;
	goto yy14;
yy474:
	++cur;
	goto yy124;
yy475:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy538;
	goto yy14;
yy476:
	++cur;
#line 135 "../src/parse/lex_conf.re"
	{ opts.set_indString (lex_conf_string ()); return; }
#line 2153 "src/parse/lex_conf.cc"
yy478:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy539;
	goto yy14;
yy479:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy540;
	goto yy14;
yy480:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy541;
	goto yy14;
yy481:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy542;
	goto yy14;
yy482:
	++cur;
#line 101 "../src/parse/lex_conf.re"
	{ opts.set_yybm         (lex_conf_string ()); return; }
#line 2174 "src/parse/lex_conf.cc"
yy484:
	++cur;
#line 150 "../src/parse/lex_conf.re"
	{ opts.set_yych           (lex_conf_string ()); return; }
#line 2179 "src/parse/lex_conf.cc"
yy486:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy543;
	goto yy14;
yy487:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy544;
	goto yy14;
yy488:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy545;
	goto yy14;
yy489:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy546;
	goto yy14;
yy490:
	++cur;
#line 155 "../src/parse/lex_conf.re"
	{ opts.set_fill_use     (lex_conf_bool()); return; }
#line 2200 "src/parse/lex_conf.cc"
yy492:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy547;
	goto yy14;
yy493:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy548;
	goto yy14;
yy494:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy550;
	goto yy14;
yy495:
	++cur;
#line 87 "../src/parse/lex_conf.re"
	{ opts.set_condGotoParam    (lex_conf_string ()); return; }
#line 2217 "src/parse/lex_conf.cc"
yy497:
	++cur;
#line 83 "../src/parse/lex_conf.re"
	{ opts.set_condEnumPrefix   (lex_conf_string ()); return; }
#line 2222 "src/parse/lex_conf.cc"
yy499:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy551;
	goto yy14;
yy500:
	yych = (unsigned char)*++cur;
	if (yych == 'Y') goto yy553;
	goto yy14;
yy501:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy554;
	goto yy14;
yy502:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy555;
	goto yy14;
yy503:
	++cur;
#line 149 "../src/parse/lex_conf.re"
	{ opts.set_yyctype        (lex_conf_string ()); return; }
#line 2243 "src/parse/lex_conf.cc"
yy505:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy556;
	goto yy14;
yy506:
	++cur;
#line 147 "../src/parse/lex_conf.re"
	{ opts.set_yydebug (lex_conf_string ()); return; }
#line 2252 "src/parse/lex_conf.cc"
yy508:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy558;
	goto yy14;
yy509:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy559;
	goto yy14;
yy510:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy560;
	goto yy14;
yy511:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy561;
	goto yy14;
yy512:
	yych = (unsigned char)*++cur;
	if (yych == 'H') goto yy562;
	goto yy14;
yy513:
	++cur;
#line 118 "../src/parse/lex_conf.re"
	{ opts.set_yylimit     (lex_conf_string ()); return; }
#line 2277 "src/parse/lex_conf.cc"
yy515:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy563;
	goto yy14;
yy516:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy565;
	goto yy14;
yy517:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy566;
	goto yy14;
yy518:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy567;
	goto yy14;
yy519:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy568;
	goto yy14;
yy520:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy569;
	goto yy14;
yy521:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy570;
	goto yy14;
yy522:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy571;
	goto yy14;
yy523:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy572;
	goto yy14;
yy524:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy573;
	goto yy14;
yy525:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy574;
	goto yy14;
yy526:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy575;
	goto yy14;
yy527:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy576;
	goto yy14;
yy528:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy577;
	goto yy14;
yy529:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy578;
	goto yy14;
yy530:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy579;
	goto yy14;
yy531:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy580;
	goto yy14;
yy532:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy581;
	goto yy14;
yy533:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy582;
	goto yy14;
yy534:
	++cur;
	goto yy118;
yy535:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy583;
	goto yy14;
yy536:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy584;
	goto yy14;
yy537:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy585;
	goto yy14;
yy538:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy586;
	goto yy14;
yy539:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy587;
	goto yy14;
yy540:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy588;
	goto yy14;
yy541:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy590;
	goto yy14;
yy542:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy592;
	goto yy14;
yy543:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy593;
	goto yy14;
yy544:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy594;
	goto yy14;
yy545:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy595;
	goto yy14;
yy546:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy596;
	goto yy14;
yy547:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy598;
	goto yy14;
yy548:
	++cur;
#line 104 "../src/parse/lex_conf.re"
	{
		const int32_t n = lex_conf_number ();
		if (n < 0)
		{
			fatal ("configuration 'cgoto:threshold' must be nonnegative");
		}
		opts.set_cGotoThreshold (static_cast<uint32_t> (n));
		return;
	}
#line 2421 "src/parse/lex_conf.cc"
yy550:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy599;
	goto yy14;
yy551:
	yyaccept = 17;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'C') goto yy600;
	if (yych == 'T') goto yy601;
yy552:
#line 122 "../src/parse/lex_conf.re"
	{ opts.set_yybackup     (lex_conf_string ()); return; }
#line 2434 "src/parse/lex_conf.cc"
yy553:
	yych = (unsigned char)*++cur;
	if (yych == 'P') goto yy602;
	goto yy14;
yy554:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy603;
	goto yy14;
yy555:
	yych = (unsigned char)*++cur;
	if (yych == 'K') goto yy605;
	goto yy14;
yy556:
	++cur;
#line 115 "../src/parse/lex_conf.re"
	{ opts.set_yycursor    (lex_conf_string ()); return; }
#line 2451 "src/parse/lex_conf.cc"
yy558:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy606;
	goto yy14;
yy559:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy607;
	goto yy14;
yy560:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy608;
	goto yy14;
yy561:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy609;
	goto yy14;
yy562:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy610;
	goto yy14;
yy563:
	++cur;
#line 116 "../src/parse/lex_conf.re"
	{ opts.set_yymarker    (lex_conf_string ()); return; }
#line 2476 "src/parse/lex_conf.cc"
yy565:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy611;
	goto yy14;
yy566:
	yych = (unsigned char)*++cur;
	if (yych == 'D') goto yy613;
	goto yy14;
yy567:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy614;
	goto yy14;
yy568:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy615;
	goto yy14;
yy569:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy616;
	goto yy14;
yy570:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy617;
	goto yy14;
yy571:
	yych = (unsigned char)*++cur;
	if (yych == 'g') goto yy618;
	goto yy14;
yy572:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy619;
	goto yy14;
yy573:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy620;
	goto yy14;
yy574:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy621;
	goto yy14;
yy575:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy623;
	goto yy14;
yy576:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy624;
	goto yy14;
yy577:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy625;
	goto yy14;
yy578:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy626;
	goto yy14;
yy579:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy627;
	goto yy14;
yy580:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy628;
	goto yy14;
yy581:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy629;
	goto yy14;
yy582:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy630;
	goto yy14;
yy583:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy632;
	goto yy14;
yy584:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy633;
	goto yy14;
yy585:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy634;
	goto yy14;
yy586:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy635;
	goto yy14;
yy587:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy636;
	goto yy14;
yy588:
	++cur;
#line 98 "../src/parse/lex_conf.re"
	{ opts.set_bUseStateNext   (lex_conf_bool()); return; }
#line 2573 "src/parse/lex_conf.cc"
yy590:
	++cur;
#line 133 "../src/parse/lex_conf.re"
	{ opts.set_tags_expression(lex_conf_string ()); return; }
#line 2578 "src/parse/lex_conf.cc"
yy592:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy637;
	goto yy14;
yy593:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy638;
	goto yy14;
yy594:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy639;
	goto yy14;
yy595:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy640;
	goto yy14;
yy596:
	++cur;
#line 151 "../src/parse/lex_conf.re"
	{ opts.set_yychConversion (lex_conf_bool()); return; }
#line 2599 "src/parse/lex_conf.cc"
yy598:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy641;
	goto yy14;
yy599:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy643;
	goto yy14;
yy600:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy645;
	goto yy14;
yy601:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy646;
	goto yy14;
yy602:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy647;
	goto yy14;
yy603:
	++cur;
#line 128 "../src/parse/lex_conf.re"
	{ opts.set_yycopytag    (lex_conf_string ()); return; }
#line 2624 "src/parse/lex_conf.cc"
yy605:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy649;
	goto yy14;
yy606:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy650;
	goto yy14;
yy607:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy651;
	goto yy14;
yy608:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy653;
	goto yy14;
yy609:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy654;
	goto yy14;
yy610:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy656;
	goto yy14;
yy611:
	yyaccept = 18;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'C') goto yy658;
	if (yych == 'T') goto yy659;
yy612:
#line 125 "../src/parse/lex_conf.re"
	{ opts.set_yyrestore    (lex_conf_string ()); return; }
#line 2657 "src/parse/lex_conf.cc"
yy613:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy660;
	goto yy14;
yy614:
	yych = (unsigned char)*++cur;
	if (yych == 'E') goto yy661;
	goto yy14;
yy615:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy663;
	goto yy14;
yy616:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy664;
	goto yy14;
yy617:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy665;
	goto yy14;
yy618:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy666;
	goto yy14;
yy619:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy667;
	goto yy14;
yy620:
	yych = (unsigned char)*++cur;
	if (yych == 'z') goto yy668;
	goto yy14;
yy621:
	++cur;
#line 60 "../src/parse/lex_conf.re"
	{ opts.set_eager_skip(lex_conf_bool());         return; }
#line 2694 "src/parse/lex_conf.cc"
yy623:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy669;
	goto yy14;
yy624:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy671;
	goto yy14;
yy625:
	yych = (unsigned char)*++cur;
	if (yych == 'x') goto yy94;
	goto yy14;
yy626:
	++cur;
	goto yy120;
yy627:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy672;
	goto yy14;
yy628:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy673;
	goto yy14;
yy629:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy674;
	goto yy14;
yy630:
	++cur;
#line 56 "../src/parse/lex_conf.re"
	{ opts.set_version(!lex_conf_bool());           return; }
#line 2726 "src/parse/lex_conf.cc"
yy632:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy675;
	goto yy14;
yy633:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy676;
	goto yy14;
yy634:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy677;
	goto yy14;
yy635:
	++cur;
	goto yy126;
yy636:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy678;
	goto yy14;
yy637:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy680;
	goto yy14;
yy638:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy682;
	goto yy14;
yy639:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy684;
	goto yy14;
yy640:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy686;
	goto yy14;
yy641:
	++cur;
#line 157 "../src/parse/lex_conf.re"
	{ opts.set_fill_arg_use (lex_conf_bool()); return; }
#line 2766 "src/parse/lex_conf.cc"
yy643:
	++cur;
#line 85 "../src/parse/lex_conf.re"
	{ opts.set_condDividerParam (lex_conf_string ()); return; }
#line 2771 "src/parse/lex_conf.cc"
yy645:
	yych = (unsigned char)*++cur;
	if (yych == 'X') goto yy688;
	goto yy14;
yy646:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy690;
	goto yy14;
yy647:
	++cur;
#line 76 "../src/parse/lex_conf.re"
	{ opts.set_yycondtype       (lex_conf_string ()); return; }
#line 2784 "src/parse/lex_conf.cc"
yy649:
	yych = (unsigned char)*++cur;
	if (yych == 'R') goto yy692;
	goto yy14;
yy650:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy694;
	goto yy14;
yy651:
	++cur;
#line 156 "../src/parse/lex_conf.re"
	{ opts.set_fill_arg     (lex_conf_string ()); return; }
#line 2797 "src/parse/lex_conf.cc"
yy653:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy695;
	goto yy14;
yy654:
	yyaccept = 19;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == ':') goto yy696;
yy655:
#line 90 "../src/parse/lex_conf.re"
	{ opts.set_state_get       (lex_conf_string ()); return; }
#line 2809 "src/parse/lex_conf.cc"
yy656:
	++cur;
#line 129 "../src/parse/lex_conf.re"
	{ opts.set_yylessthan   (lex_conf_string ()); return; }
#line 2814 "src/parse/lex_conf.cc"
yy658:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy697;
	goto yy14;
yy659:
	yych = (unsigned char)*++cur;
	if (yych == 'A') goto yy698;
	goto yy14;
yy660:
	yych = (unsigned char)*++cur;
	if (yych == 'T') goto yy699;
	goto yy14;
yy661:
	yyaccept = 20;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == ':') goto yy700;
	if (yych == '@') goto yy701;
yy662:
#line 92 "../src/parse/lex_conf.re"
	{ opts.set_state_set       (lex_conf_string ()); return; }
#line 2835 "src/parse/lex_conf.cc"
yy663:
	++cur;
	goto yy101;
yy664:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy702;
	goto yy14;
yy665:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy703;
	goto yy14;
yy666:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy704;
	goto yy14;
yy667:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy705;
	goto yy14;
yy668:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy706;
	goto yy14;
yy669:
	++cur;
#line 73 "../src/parse/lex_conf.re"
	{ lex_conf_empty_class();      return; }
#line 2863 "src/parse/lex_conf.cc"
yy671:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy707;
	goto yy14;
yy672:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy708;
	goto yy14;
yy673:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy709;
	goto yy14;
yy674:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy710;
	goto yy14;
yy675:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy712;
	goto yy14;
yy676:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy713;
	goto yy14;
yy677:
	++cur;
	goto yy122;
yy678:
	++cur;
#line 95 "../src/parse/lex_conf.re"
	{ opts.set_yyfilllabel     (lex_conf_string ()); return; }
#line 2895 "src/parse/lex_conf.cc"
yy680:
	++cur;
#line 99 "../src/parse/lex_conf.re"
	{ opts.set_yyaccept        (lex_conf_string ()); return; }
#line 2900 "src/parse/lex_conf.cc"
yy682:
	++cur;
#line 88 "../src/parse/lex_conf.re"
	{ opts.set_yyctable         (lex_conf_string ()); return; }
#line 2905 "src/parse/lex_conf.cc"
yy684:
	++cur;
#line 168 "../src/parse/lex_conf.re"
	{ lex_conf_string (); return; }
#line 2910 "src/parse/lex_conf.cc"
yy686:
	++cur;
#line 113 "../src/parse/lex_conf.re"
	{ opts.set_yytarget (lex_conf_string ()); return; }
#line 2915 "src/parse/lex_conf.cc"
yy688:
	++cur;
#line 123 "../src/parse/lex_conf.re"
	{ opts.set_yybackupctx  (lex_conf_string ()); return; }
#line 2920 "src/parse/lex_conf.cc"
yy690:
	++cur;
#line 124 "../src/parse/lex_conf.re"
	{ opts.set_yybackuptag  (lex_conf_string ()); return; }
#line 2925 "src/parse/lex_conf.cc"
yy692:
	++cur;
#line 117 "../src/parse/lex_conf.re"
	{ opts.set_yyctxmarker (lex_conf_string ()); return; }
#line 2930 "src/parse/lex_conf.cc"
yy694:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy714;
	goto yy14;
yy695:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy716;
	goto yy14;
yy696:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy717;
	goto yy14;
yy697:
	yych = (unsigned char)*++cur;
	if (yych == 'X') goto yy718;
	goto yy14;
yy698:
	yych = (unsigned char)*++cur;
	if (yych == 'G') goto yy720;
	goto yy14;
yy699:
	yych = (unsigned char)*++cur;
	if (yych == 'I') goto yy722;
	goto yy14;
yy700:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy723;
	goto yy14;
yy701:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy724;
	goto yy14;
yy702:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy725;
	goto yy14;
yy703:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy726;
	goto yy14;
yy704:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy728;
	goto yy14;
yy705:
	++cur;
	goto yy105;
yy706:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy729;
	goto yy14;
yy707:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy730;
	goto yy14;
yy708:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy731;
	goto yy14;
yy709:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy732;
	goto yy14;
yy710:
	++cur;
#line 59 "../src/parse/lex_conf.re"
	{ opts.set_lookahead(!lex_conf_bool());         return; }
#line 2998 "src/parse/lex_conf.cc"
yy712:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy733;
	goto yy14;
yy713:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy734;
	goto yy14;
yy714:
	++cur;
#line 158 "../src/parse/lex_conf.re"
	{ opts.set_fill_naked   (lex_conf_bool()); return; }
#line 3011 "src/parse/lex_conf.cc"
yy716:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy735;
	goto yy14;
yy717:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy736;
	goto yy14;
yy718:
	++cur;
#line 126 "../src/parse/lex_conf.re"
	{ opts.set_yyrestorectx (lex_conf_string ()); return; }
#line 3024 "src/parse/lex_conf.cc"
yy720:
	++cur;
#line 127 "../src/parse/lex_conf.re"
	{ opts.set_yyrestoretag (lex_conf_string ()); return; }
#line 3029 "src/parse/lex_conf.cc"
yy722:
	yych = (unsigned char)*++cur;
	if (yych == 'O') goto yy737;
	goto yy14;
yy723:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy738;
	goto yy14;
yy724:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy739;
	goto yy14;
yy725:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy740;
	goto yy14;
yy726:
	++cur;
#line 58 "../src/parse/lex_conf.re"
	{ opts.set_bCaseInverted(lex_conf_bool());      return; }
#line 3050 "src/parse/lex_conf.cc"
yy728:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy110;
	goto yy14;
yy729:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy741;
	goto yy14;
yy730:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy742;
	goto yy14;
yy731:
	++cur;
	goto yy113;
yy732:
	yych = (unsigned char)*++cur;
	if (yych == '-') goto yy743;
	goto yy14;
yy733:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy744;
	goto yy14;
yy734:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy745;
	goto yy14;
yy735:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy746;
	goto yy14;
yy736:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy748;
	goto yy14;
yy737:
	yych = (unsigned char)*++cur;
	if (yych == 'N') goto yy749;
	goto yy14;
yy738:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy751;
	goto yy14;
yy739:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy752;
	goto yy14;
yy740:
	yych = (unsigned char)*++cur;
	if (yych == 'v') goto yy753;
	goto yy14;
yy741:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy754;
	goto yy14;
yy742:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy755;
	goto yy14;
yy743:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy757;
	goto yy14;
yy744:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy758;
	goto yy14;
yy745:
	++cur;
	goto yy109;
yy746:
	yyaccept = 21;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == ':') goto yy759;
yy747:
#line 77 "../src/parse/lex_conf.re"
	{ opts.set_cond_get         (lex_conf_string ()); return; }
#line 3128 "src/parse/lex_conf.cc"
yy748:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy760;
	goto yy14;
yy749:
	yyaccept = 22;
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == ':') goto yy761;
	if (yych == '@') goto yy762;
yy750:
#line 79 "../src/parse/lex_conf.re"
	{ opts.set_cond_set         (lex_conf_string ()); return; }
#line 3141 "src/parse/lex_conf.cc"
yy751:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy763;
	goto yy14;
yy752:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy764;
	goto yy14;
yy753:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy765;
	goto yy14;
yy754:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy767;
	goto yy14;
yy755:
	++cur;
#line 71 "../src/parse/lex_conf.re"
	{ lex_conf_encoding_policy();  return; }
#line 3162 "src/parse/lex_conf.cc"
yy757:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy769;
	goto yy14;
yy758:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy770;
	goto yy14;
yy759:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy771;
	goto yy14;
yy760:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy772;
	goto yy14;
yy761:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy774;
	goto yy14;
yy762:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy775;
	goto yy14;
yy763:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy776;
	goto yy14;
yy764:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy778;
	goto yy14;
yy765:
	++cur;
#line 57 "../src/parse/lex_conf.re"
	{ opts.set_bCaseInsensitive(lex_conf_bool());   return; }
#line 3199 "src/parse/lex_conf.cc"
yy767:
	++cur;
#line 74 "../src/parse/lex_conf.re"
	{ lex_conf_dfa_minimization(); return; }
#line 3204 "src/parse/lex_conf.cc"
yy769:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy780;
	goto yy14;
yy770:
	++cur;
	goto yy103;
yy771:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy781;
	goto yy14;
yy772:
	++cur;
#line 91 "../src/parse/lex_conf.re"
	{ opts.set_state_get_naked (lex_conf_bool()); return; }
#line 3220 "src/parse/lex_conf.cc"
yy774:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy782;
	goto yy14;
yy775:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy783;
	goto yy14;
yy776:
	++cur;
#line 93 "../src/parse/lex_conf.re"
	{ opts.set_state_set_naked (lex_conf_bool()); return; }
#line 3233 "src/parse/lex_conf.cc"
yy778:
	++cur;
#line 94 "../src/parse/lex_conf.re"
	{ opts.set_state_set_arg   (lex_conf_string ()); return; }
#line 3238 "src/parse/lex_conf.cc"
yy780:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy784;
	goto yy14;
yy781:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy786;
	goto yy14;
yy782:
	yych = (unsigned char)*++cur;
	if (yych == 'k') goto yy787;
	goto yy14;
yy783:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy788;
	goto yy14;
yy784:
	++cur;
#line 55 "../src/parse/lex_conf.re"
	{ opts.set_bNoGenerationDate(lex_conf_bool());  return; }
#line 3259 "src/parse/lex_conf.cc"
yy786:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy789;
	goto yy14;
yy787:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy790;
	goto yy14;
yy788:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy791;
	goto yy14;
yy789:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy793;
	goto yy14;
yy790:
	yych = (unsigned char)*++cur;
	if (yych == 'd') goto yy795;
	goto yy14;
yy791:
	++cur;
#line 80 "../src/parse/lex_conf.re"
	{ opts.set_cond_set_arg     (lex_conf_string ()); return; }
#line 3284 "src/parse/lex_conf.cc"
yy793:
	++cur;
#line 78 "../src/parse/lex_conf.re"
	{ opts.set_cond_get_naked   (lex_conf_bool()); return; }
#line 3289 "src/parse/lex_conf.cc"
yy795:
	++cur;
#line 81 "../src/parse/lex_conf.re"
	{ opts.set_cond_set_naked   (lex_conf_bool()); return; }
#line 3294 "src/parse/lex_conf.cc"
}
#line 169 "../src/parse/lex_conf.re"

}

void Scanner::lex_conf_encoding_policy()
{
	lex_conf_assign ();

#line 3304 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 10) fill(10);
	yych = (unsigned char)*cur;
	if (yych <= 'h') {
		if (yych == 'f') goto yy801;
	} else {
		if (yych <= 'i') goto yy802;
		if (yych == 's') goto yy803;
	}
	++cur;
yy800:
#line 176 "../src/parse/lex_conf.re"
	{ fatal("bad configuration value"
		" (expected: 'ignore', 'substitute', 'fail')"); }
#line 3320 "src/parse/lex_conf.cc"
yy801:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy804;
	goto yy800;
yy802:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'g') goto yy806;
	goto yy800;
yy803:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'u') goto yy807;
	goto yy800;
yy804:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy808;
yy805:
	cur = ptr;
	goto yy800;
yy806:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy809;
	goto yy805;
yy807:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy810;
	goto yy805;
yy808:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy811;
	goto yy805;
yy809:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy813;
	goto yy805;
yy810:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy814;
	goto yy805;
yy811:
	++cur;
#line 180 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_FAIL);       goto end; }
#line 3363 "src/parse/lex_conf.cc"
yy813:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy815;
	goto yy805;
yy814:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy816;
	goto yy805;
yy815:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy817;
	goto yy805;
yy816:
	yych = (unsigned char)*++cur;
	if (yych == 'i') goto yy819;
	goto yy805;
yy817:
	++cur;
#line 178 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_IGNORE);     goto end; }
#line 3384 "src/parse/lex_conf.cc"
yy819:
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy805;
	yych = (unsigned char)*++cur;
	if (yych != 'u') goto yy805;
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy805;
	yych = (unsigned char)*++cur;
	if (yych != 'e') goto yy805;
	++cur;
#line 179 "../src/parse/lex_conf.re"
	{ opts.set_encoding_policy(Enc::POLICY_SUBSTITUTE); goto end; }
#line 3397 "src/parse/lex_conf.cc"
}
#line 181 "../src/parse/lex_conf.re"

end:
	lex_conf_semicolon();
}

void Scanner::lex_conf_input()
{
	lex_conf_assign ();

#line 3409 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 7) fill(7);
	yych = (unsigned char)*cur;
	if (yych <= 'b') goto yy827;
	if (yych <= 'c') goto yy829;
	if (yych <= 'd') goto yy830;
yy827:
	++cur;
yy828:
#line 190 "../src/parse/lex_conf.re"
	{ fatal("bad configuration value"
		" (expected: 'default', 'custom')"); }
#line 3423 "src/parse/lex_conf.cc"
yy829:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'u') goto yy831;
	goto yy828;
yy830:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'e') goto yy833;
	goto yy828;
yy831:
	yych = (unsigned char)*++cur;
	if (yych == 's') goto yy834;
yy832:
	cur = ptr;
	goto yy828;
yy833:
	yych = (unsigned char)*++cur;
	if (yych == 'f') goto yy835;
	goto yy832;
yy834:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy836;
	goto yy832;
yy835:
	yych = (unsigned char)*++cur;
	if (yych == 'a') goto yy837;
	goto yy832;
yy836:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy838;
	goto yy832;
yy837:
	yych = (unsigned char)*++cur;
	if (yych == 'u') goto yy839;
	goto yy832;
yy838:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy840;
	goto yy832;
yy839:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy842;
	goto yy832;
yy840:
	++cur;
#line 193 "../src/parse/lex_conf.re"
	{ opts.set_input_api(INPUT_CUSTOM);  goto end; }
#line 3470 "src/parse/lex_conf.cc"
yy842:
	yych = (unsigned char)*++cur;
	if (yych != 't') goto yy832;
	++cur;
#line 192 "../src/parse/lex_conf.re"
	{ opts.set_input_api(INPUT_DEFAULT); goto end; }
#line 3477 "src/parse/lex_conf.cc"
}
#line 194 "../src/parse/lex_conf.re"

end:
	lex_conf_semicolon();
}

void Scanner::lex_conf_empty_class()
{
	lex_conf_assign ();

#line 3489 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 11) fill(11);
	yych = (unsigned char)*cur;
	if (yych == 'e') goto yy849;
	if (yych == 'm') goto yy850;
	++cur;
yy848:
#line 203 "../src/parse/lex_conf.re"
	{ fatal("bad configuration value"
		" (expected: 'match-empty', 'match-none', 'error')"); }
#line 3501 "src/parse/lex_conf.cc"
yy849:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'r') goto yy851;
	goto yy848;
yy850:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy853;
	goto yy848;
yy851:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy854;
yy852:
	cur = ptr;
	goto yy848;
yy853:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy855;
	goto yy852;
yy854:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy856;
	goto yy852;
yy855:
	yych = (unsigned char)*++cur;
	if (yych == 'c') goto yy857;
	goto yy852;
yy856:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy858;
	goto yy852;
yy857:
	yych = (unsigned char)*++cur;
	if (yych == 'h') goto yy860;
	goto yy852;
yy858:
	++cur;
#line 207 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_ERROR);       goto end; }
#line 3540 "src/parse/lex_conf.cc"
yy860:
	yych = (unsigned char)*++cur;
	if (yych != '-') goto yy852;
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy862;
	if (yych == 'n') goto yy863;
	goto yy852;
yy862:
	yych = (unsigned char)*++cur;
	if (yych == 'm') goto yy864;
	goto yy852;
yy863:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy865;
	goto yy852;
yy864:
	yych = (unsigned char)*++cur;
	if (yych == 'p') goto yy866;
	goto yy852;
yy865:
	yych = (unsigned char)*++cur;
	if (yych == 'n') goto yy867;
	goto yy852;
yy866:
	yych = (unsigned char)*++cur;
	if (yych == 't') goto yy868;
	goto yy852;
yy867:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy869;
	goto yy852;
yy868:
	yych = (unsigned char)*++cur;
	if (yych == 'y') goto yy871;
	goto yy852;
yy869:
	++cur;
#line 206 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_MATCH_NONE);  goto end; }
#line 3580 "src/parse/lex_conf.cc"
yy871:
	++cur;
#line 205 "../src/parse/lex_conf.re"
	{ opts.set_empty_class_policy(EMPTY_CLASS_MATCH_EMPTY); goto end; }
#line 3585 "src/parse/lex_conf.cc"
}
#line 208 "../src/parse/lex_conf.re"

end:
	lex_conf_semicolon();
}

void Scanner::lex_conf_dfa_minimization()
{
	lex_conf_assign ();

#line 3597 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	if ((lim - cur) < 5) fill(5);
	yych = (unsigned char)*cur;
	if (yych == 'm') goto yy877;
	if (yych == 't') goto yy878;
	++cur;
yy876:
#line 217 "../src/parse/lex_conf.re"
	{ fatal("bad configuration value"
		" (expected: 'table', 'moore')"); }
#line 3609 "src/parse/lex_conf.cc"
yy877:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'o') goto yy879;
	goto yy876;
yy878:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych == 'a') goto yy881;
	goto yy876;
yy879:
	yych = (unsigned char)*++cur;
	if (yych == 'o') goto yy882;
yy880:
	cur = ptr;
	goto yy876;
yy881:
	yych = (unsigned char)*++cur;
	if (yych == 'b') goto yy883;
	goto yy880;
yy882:
	yych = (unsigned char)*++cur;
	if (yych == 'r') goto yy884;
	goto yy880;
yy883:
	yych = (unsigned char)*++cur;
	if (yych == 'l') goto yy885;
	goto yy880;
yy884:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy886;
	goto yy880;
yy885:
	yych = (unsigned char)*++cur;
	if (yych == 'e') goto yy888;
	goto yy880;
yy886:
	++cur;
#line 220 "../src/parse/lex_conf.re"
	{ opts.set_dfa_minimization(DFA_MINIMIZATION_MOORE); goto end; }
#line 3648 "src/parse/lex_conf.cc"
yy888:
	++cur;
#line 219 "../src/parse/lex_conf.re"
	{ opts.set_dfa_minimization(DFA_MINIMIZATION_TABLE); goto end; }
#line 3653 "src/parse/lex_conf.cc"
}
#line 221 "../src/parse/lex_conf.re"

end:
	lex_conf_semicolon();
}

void Scanner::lex_conf_enc(Enc::type_t enc)
{
	const bool off = !lex_conf_bool();
	if (off) {
		opts.unset_encoding(enc);
	} else if (!opts.set_encoding(enc)) {
		fatalf ("Cannot set %s encoding: please reset %s encoding first"
			, Enc::name(enc)
			, Enc::name(opts->encoding.type()));
	}
}

void Scanner::lex_conf_assign ()
{

#line 3676 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) fill(2);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy894;
	} else {
		if (yych <= ' ') goto yy894;
		if (yych == '=') goto yy895;
	}
	++cur;
yy893:
#line 241 "../src/parse/lex_conf.re"
	{ fatal ("missing '=' in configuration"); }
#line 3725 "src/parse/lex_conf.cc"
yy894:
	yych = (unsigned char)*(ptr = ++cur);
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy898;
		goto yy893;
	} else {
		if (yych <= ' ') goto yy898;
		if (yych != '=') goto yy893;
	}
yy895:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy895;
	}
#line 242 "../src/parse/lex_conf.re"
	{ return; }
#line 3744 "src/parse/lex_conf.cc"
yy898:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy898;
	} else {
		if (yych <= ' ') goto yy898;
		if (yych == '=') goto yy895;
	}
	cur = ptr;
	goto yy893;
}
#line 243 "../src/parse/lex_conf.re"

}

void Scanner::lex_conf_semicolon ()
{

#line 3765 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) fill(2);
	yych = (unsigned char)*cur;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy905;
	} else {
		if (yych <= ' ') goto yy905;
		if (yych == ';') goto yy906;
	}
	++cur;
yy904:
#line 249 "../src/parse/lex_conf.re"
	{ fatal ("missing ending ';' in configuration"); }
#line 3814 "src/parse/lex_conf.cc"
yy905:
	yych = (unsigned char)*(ptr = ++cur);
	if (yybm[0+yych] & 128) {
		goto yy908;
	}
	if (yych != ';') goto yy904;
yy906:
	++cur;
#line 250 "../src/parse/lex_conf.re"
	{ return; }
#line 3825 "src/parse/lex_conf.cc"
yy908:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy908;
	}
	if (yych == ';') goto yy906;
	cur = ptr;
	goto yy904;
}
#line 251 "../src/parse/lex_conf.re"

}

bool Scanner::lex_conf_bool()
{
	return lex_conf_number() != 0;
}

int32_t Scanner::lex_conf_number ()
{
	lex_conf_assign ();
	tok = cur;

#line 3851 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((lim - cur) < 2) fill(2);
	yych = (unsigned char)*cur;
	if (yych <= '/') {
		if (yych == '-') goto yy914;
	} else {
		if (yych <= '0') goto yy915;
		if (yych <= '9') goto yy917;
	}
yy913:
yy914:
	yych = (unsigned char)*++cur;
	if (yych <= '0') goto yy913;
	if (yych <= '9') goto yy917;
	goto yy913;
yy915:
	++cur;
yy916:
#line 265 "../src/parse/lex_conf.re"
	{
		int32_t n = 0;
		if (!s_to_i32_unsafe (tok, cur, n))
		{
			fatal ("configuration value overflow");
		}
		lex_conf_semicolon ();
		return n;
	}
#line 3915 "src/parse/lex_conf.cc"
yy917:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy917;
	}
	goto yy916;
}
#line 274 "../src/parse/lex_conf.re"

}

std::string Scanner::lex_conf_string ()
{
	lex_conf_assign ();
	std::string s;
	tok = cur;

#line 3935 "src/parse/lex_conf.cc"
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		128, 128, 128, 128, 128, 128, 128, 128, 
		128,   0,   0, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yych <= '!') {
		if (yych <= '\n') {
			if (yych <= 0x08) goto yy922;
		} else {
			if (yych != ' ') goto yy922;
		}
	} else {
		if (yych <= '\'') {
			if (yych <= '"') goto yy925;
			if (yych <= '&') goto yy922;
			goto yy925;
		} else {
			if (yych != ';') goto yy922;
		}
	}
#line 301 "../src/parse/lex_conf.re"
	{ goto end; }
#line 3991 "src/parse/lex_conf.cc"
yy922:
	++cur;
	if (lim <= cur) fill(1);
	yych = (unsigned char)*cur;
	if (yybm[0+yych] & 128) {
		goto yy922;
	}
#line 297 "../src/parse/lex_conf.re"
	{
		s = std::string(tok, tok_len());
		goto end;
	}
#line 4004 "src/parse/lex_conf.cc"
yy925:
	++cur;
#line 283 "../src/parse/lex_conf.re"
	{
		const char quote = tok[0];
		for (bool end;;) {
			const uint32_t c = lex_str_chr(quote, end);
			if (end) {
				goto end;
			}
			if (c > 0xFF) {
				fatalf ("multibyte character in configuration string: 0x%X", c);
			} else {
				s += static_cast<char>(c);
			}
		}
	}
#line 4022 "src/parse/lex_conf.cc"
}
#line 302 "../src/parse/lex_conf.re"

end:
	lex_conf_semicolon ();
	return s;
}

} // end namespace re2c
