all:
	$(MAKE) -C skeleton
	$(MAKE) -C numscan-coupled
	$(MAKE) -C numscan-modular
	$(MAKE) -C startstate
	$(MAKE) -C compare

clean:
	$(MAKE) -C skeleton clean
	$(MAKE) -C numscan-coupled clean
	$(MAKE) -C numscan-modular clean
	$(MAKE) -C startstate clean
	$(MAKE) -C compare clean
