/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i --flex-syntax --stadfa

{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 32) YYFILL(32);
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
		case 'a': goto yy2;
		case 'b': goto yy4;
		case 'c': goto yy5;
		default: goto yy1;
	}
yy1:
	yynmatch = 1;
	yypmatch[0] = YYCURSOR;
	yypmatch[1] = YYCURSOR;
	{}
yy2:
	yych = *++YYCURSOR;
	yyt2 = yyt5 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy6;
		case 'b': goto yy7;
		case 'c': goto yy8;
		default: goto yy3;
	}
yy3:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy1;
	} else {
		yyt2 = yyt1;
		yyt1 = yyt5;
		yyt3 = yyt4 = YYCURSOR;
		goto yy19;
	}
yy4:
	yych = *++YYCURSOR;
	yyt5 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy9;
		default: goto yy3;
	}
yy5:
	yych = *++YYCURSOR;
	yyt2 = yyt5 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy6;
		case 'b': goto yy10;
		case 'c': goto yy8;
		default: goto yy3;
	}
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy12;
		case 'c': goto yy13;
		default: goto yy3;
	}
yy7:
	yych = *++YYCURSOR;
	yyt3 = yyt5;
	yyt2 = yyt5;
	switch (yych) {
		case 'a': goto yy6;
		case 'b': goto yy10;
		case 'c': goto yy14;
		default: goto yy3;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy15;
		case 'c': goto yy13;
		default: goto yy3;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy16;
		default: goto yy3;
	}
yy10:
	yych = *++YYCURSOR;
	yyt3 = yyt5;
	switch (yych) {
		case 'c': goto yy17;
		default: goto yy3;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy18;
		case 'b': goto yy20;
		case 'c': goto yy21;
		default: goto yy3;
	}
yy12:
	yych = *++YYCURSOR;
	yyt3 = yyt5;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy15;
		case 'c': goto yy22;
		default: goto yy3;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy18;
		case 'b': goto yy23;
		case 'c': goto yy21;
		default: goto yy3;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy15;
		case 'c': goto yy13;
		case 'd': goto yy24;
		default: goto yy3;
	}
yy15:
	yych = *++YYCURSOR;
	yyt3 = yyt5;
	switch (yych) {
		case 'c': goto yy25;
		default: goto yy3;
	}
yy16:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	switch (yych) {
		case 'a': goto yy6;
		case 'b': goto yy10;
		case 'c': goto yy8;
		default: goto yy3;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy24;
		default: goto yy3;
	}
yy18:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy26;
		case 'b': goto yy27;
		case 'c': goto yy28;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy19:
	yynmatch = 3;
	yypmatch[0] = yyt1;
	yypmatch[2] = yyt2;
	yypmatch[3] = yyt3;
	yypmatch[4] = yyt4;
	yypmatch[1] = YYCURSOR;
	yypmatch[5] = YYCURSOR;
	{}
yy20:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy18;
		case 'b': goto yy23;
		case 'c': goto yy30;
		default: goto yy3;
	}
yy21:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy26;
		case 'b': goto yy31;
		case 'c': goto yy28;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy18;
		case 'b': goto yy23;
		case 'c': goto yy21;
		case 'd': goto yy32;
		default: goto yy3;
	}
yy23:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy33;
		default: goto yy3;
	}
yy24:
	yych = *++YYCURSOR;
	yyt5 = yyt3;
	switch (yych) {
		case 'a': goto yy11;
		case 'b': goto yy15;
		case 'c': goto yy13;
		default: goto yy3;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy32;
		default: goto yy3;
	}
yy26:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy34;
		case 'b': goto yy35;
		case 'c': goto yy36;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy27:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy26;
		case 'b': goto yy31;
		case 'c': goto yy37;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy28:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy34;
		case 'b': goto yy38;
		case 'c': goto yy36;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy29:
	yych = *++YYCURSOR;
	yyt2 = yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'd': goto yy39;
		default:
			yyt4 = yyt3;
			yyt3 = yyt2;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy30:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy26;
		case 'b': goto yy31;
		case 'c': goto yy28;
		case 'd': goto yy40;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy31:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy41;
		default: goto yy3;
	}
yy32:
	yych = *++YYCURSOR;
	yyt5 = yyt3;
	switch (yych) {
		case 'a': goto yy18;
		case 'b': goto yy23;
		case 'c': goto yy21;
		default: goto yy3;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy40;
		default: goto yy3;
	}
yy34:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy42;
		case 'b': goto yy43;
		case 'c': goto yy44;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy35:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy34;
		case 'b': goto yy38;
		case 'c': goto yy45;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy36:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy42;
		case 'b': goto yy46;
		case 'c': goto yy44;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy37:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy34;
		case 'b': goto yy38;
		case 'c': goto yy36;
		case 'd': goto yy47;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy38:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy48;
		default: goto yy3;
	}
yy39:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'd': goto yy39;
		default:
			yyt4 = yyt3;
			yyt3 = yyt2;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy40:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy26;
		case 'b': goto yy31;
		case 'c': goto yy28;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy47;
		default: goto yy3;
	}
yy42:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy49;
		case 'b': goto yy50;
		case 'c': goto yy51;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy43:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy42;
		case 'b': goto yy46;
		case 'c': goto yy52;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy44:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy49;
		case 'b': goto yy53;
		case 'c': goto yy51;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy45:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy42;
		case 'b': goto yy46;
		case 'c': goto yy44;
		case 'd': goto yy54;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy46:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy55;
		default: goto yy3;
	}
yy47:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy34;
		case 'b': goto yy38;
		case 'c': goto yy36;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy54;
		default: goto yy3;
	}
yy49:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy56;
		case 'b': goto yy57;
		case 'c': goto yy58;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy50:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy49;
		case 'b': goto yy53;
		case 'c': goto yy59;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy51:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy56;
		case 'b': goto yy60;
		case 'c': goto yy58;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy52:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy49;
		case 'b': goto yy53;
		case 'c': goto yy51;
		case 'd': goto yy61;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy53:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy62;
		default: goto yy3;
	}
yy54:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy42;
		case 'b': goto yy46;
		case 'c': goto yy44;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy61;
		default: goto yy3;
	}
yy56:
	yych = *++YYCURSOR;
	yyt4 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy63;
		case 'b': goto yy64;
		case 'c': goto yy65;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy57:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy56;
		case 'b': goto yy60;
		case 'c': goto yy66;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy58:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy63;
		case 'b': goto yy67;
		case 'c': goto yy65;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy59:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy56;
		case 'b': goto yy60;
		case 'c': goto yy58;
		case 'd': goto yy68;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy60:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy69;
		default: goto yy3;
	}
yy61:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy49;
		case 'b': goto yy53;
		case 'c': goto yy51;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy68;
		default: goto yy3;
	}
yy63:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'b': goto yy70;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy64:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	yyt5 = yyt4;
	switch (yych) {
		case 'a': goto yy63;
		case 'b': goto yy67;
		case 'c': goto yy71;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy65:
	yych = *++YYCURSOR;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy66:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'a': goto yy63;
		case 'b': goto yy67;
		case 'c': goto yy65;
		case 'd': goto yy72;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy67:
	yych = *++YYCURSOR;
	yyt2 = yyt5;
	yyt3 = YYCURSOR - 1;
	switch (yych) {
		case 'c': goto yy73;
		default: goto yy3;
	}
yy68:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy56;
		case 'b': goto yy60;
		case 'c': goto yy58;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy72;
		default: goto yy3;
	}
yy70:
	yych = *++YYCURSOR;
	yyt5 = yyt2;
	switch (yych) {
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy71:
	yych = *++YYCURSOR;
	yyt1 = YYCURSOR - 1;
	switch (yych) {
		case 'd': goto yy74;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy72:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'a': goto yy63;
		case 'b': goto yy67;
		case 'c': goto yy65;
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy74;
		default: goto yy3;
	}
yy74:
	yych = *++YYCURSOR;
	yyt1 = yyt3;
	yyt5 = yyt2;
	switch (yych) {
		case 'd': goto yy29;
		default:
			yyt3 = yyt4 = YYCURSOR;
			yyt2 = yyt1;
			yyt1 = yyt5;
			goto yy19;
	}
}

posix_captures/repetition/89_stadfa.re:7:7: warning: rule matches empty string [-Wmatch-empty-string]
