/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i --tags

{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a':
			yyt1 = YYCURSOR;
			goto yy2;
		case 'b':
			yyt1 = YYCURSOR;
			goto yy3;
		case 'c':
			yyt1 = YYCURSOR;
			goto yy5;
		case 'd': goto yy7;
		case 'e': goto yy9;
		case 'f': goto yy11;
		default:
			yyt1 = NULL;
			goto yy1;
	}
yy1:
	a = yyt1;
	{ @a }
yy2:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a':
			yyt1 = YYCURSOR;
			goto yy2;
		default: goto yy1;
	}
yy3:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'b': goto yy3;
		default: goto yy4;
	}
yy4:
	b = yyt1;
	{ @b }
yy5:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'c': goto yy5;
		default: goto yy6;
	}
yy6:
	c = yyt1;
	{ @c }
yy7:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'd': goto yy7;
		default:
			yyt1 = YYCURSOR;
			goto yy8;
	}
yy8:
	d = yyt1;
	{ @d }
yy9:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'e': goto yy9;
		default:
			yyt1 = YYCURSOR;
			goto yy10;
	}
yy10:
	e = yyt1;
	{ @e }
yy11:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 'f': goto yy11;
		default:
			yyt1 = YYCURSOR;
			goto yy12;
	}
yy12:
	f = yyt1;
	{ @f }
}

tags/ambiguity/iter.re:3:17: warning: rule matches empty string [-Wmatch-empty-string]
tags/ambiguity/iter.re:4:17: warning: rule matches empty string [-Wmatch-empty-string]
tags/ambiguity/iter.re:6:15: warning: rule matches empty string [-Wmatch-empty-string]
tags/ambiguity/iter.re:7:15: warning: rule matches empty string [-Wmatch-empty-string]
tags/ambiguity/iter.re:9:15: warning: rule matches empty string [-Wmatch-empty-string]
tags/ambiguity/iter.re:10:15: warning: rule matches empty string [-Wmatch-empty-string]
