/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i --flex-syntax --stadfa

{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 5) YYFILL(5);
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case 'a':	goto yy3;
	case 'b':	goto yy5;
	default:	goto yy2;
	}
yy2:
	yynmatch = 1;
	yypmatch[0] = YYCURSOR;
	yypmatch[1] = YYCURSOR;
	{}
yy3:
	yych = *++YYCURSOR;
	yyt4 = YYCURSOR - 1;
	switch (yych) {
	case 'a':	goto yy6;
	case 'b':	goto yy8;
	default:	goto yy4;
	}
yy4:
	YYCURSOR = YYMARKER;
	goto yy2;
yy5:
	yych = *++YYCURSOR;
	yyt4 = yyt5 = yyt7 = YYCURSOR - 1;
	switch (yych) {
	case 'b':	goto yy9;
	default:	goto yy4;
	}
yy6:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy6;
	case 'b':	goto yy8;
	default:	goto yy4;
	}
yy8:
	yych = *++YYCURSOR;
	yyt5 = yyt7 = YYCURSOR - 1;
	switch (yych) {
	case 'b':	goto yy9;
	default:	goto yy4;
	}
yy9:
	yych = *++YYCURSOR;
	yyt8 = yyt5;
	yyt6 = yyt4;
	yyt5 = YYCURSOR - 1;
	switch (yych) {
	case 'b':	goto yy10;
	default:	goto yy4;
	}
yy10:
	yych = *++YYCURSOR;
	yyt11 = yyt8;
	yyt10 = yyt7;
	yyt9 = yyt6;
	yyt8 = yyt5;
	yyt6 = yyt4;
	switch (yych) {
	case 'b':	goto yy11;
	default:	goto yy4;
	}
yy11:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	yyt3 = yyt11;
	yyt2 = yyt10;
	yyt1 = yyt9;
	yyt11 = yyt8;
	yyt10 = yyt7;
	yyt9 = yyt6;
	yyt8 = yyt5;
	yyt6 = yyt4;
	switch (yych) {
	case 'b':	goto yy11;
	default:	goto yy13;
	}
yy13:
	yynmatch = 4;
	yypmatch[2] = yyt1;
	yypmatch[4] = yyt2;
	yypmatch[6] = yyt3;
	yypmatch[0] = yyt1;
	yypmatch[1] = YYCURSOR;
	yypmatch[3] = yyt2;
	yypmatch[5] = yyt3;
	yypmatch[7] = YYCURSOR - 3;
	{}
}

posix_captures/basic/05_stadfa.re:7:7: warning: rule matches empty string [-Wmatch-empty-string]
