re2c: warning: line 3: naked default case in condition a (stray code units: [0x00-`][b-0xFF]), better add default rule * [-Wnaked-default]
/* Generated by re2c */
#line 1 "condtype_single.c.re"

#line 5 "<stdout>"
{
	YYCTYPE yych;
	switch (YYGETCONDITION()) {
	case yyca: goto yyc_a;
	}
/* *********************************** */
yyc_a:
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy4;
	default:	goto yy3;
	}
yy3:
yy4:
	++YYCURSOR;
#line 2 "condtype_single.c.re"
	{}
#line 24 "<stdout>"
}
#line 3 "condtype_single.c.re"

