/* Generated by re2c */
#line 1 "default_00.re"

#line 5 "default_00.c"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy4;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
#line 2 "default_00.re"
	{ return DEFAULT; }
#line 18 "default_00.c"
yy4:
	++YYCURSOR;
#line 3 "default_00.re"
	{ return A; }
#line 23 "default_00.c"
}
#line 4 "default_00.re"

