/* Generated by re2c */

{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	switch (YYGETCONDITION()) {
	case yycINITIAL: goto yyc_INITIAL;
	case yycST_OFFSET: goto yyc_ST_OFFSET;
	case yycST_SECTION_VALUE: goto yyc_ST_SECTION_VALUE;
	case yycST_VALUE: goto yyc_ST_VALUE;
	case yycST_SECTION_RAW: goto yyc_ST_SECTION_RAW;
	case yycST_DOUBLE_QUOTES: goto yyc_ST_DOUBLE_QUOTES;
	case yycST_VARNAME: goto yyc_ST_VARNAME;
	case yycST_RAW: goto yyc_ST_RAW;
	}
/* *********************************** */
yyc_INITIAL:
	YYFILL(5);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case ' ':	goto yy12;
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy14;
	case ';':	goto yy16;
	case '=':	goto yy18;
	case '[':	goto yy21;
	case 'f':	goto yy23;
	case 'n':	goto yy24;
	case 'o':	goto yy25;
	case 't':	goto yy26;
	case 'y':	goto yy27;
	default:	goto yy3;
	}
yy3:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
yy4:
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy5;
	case '[':	goto yy28;
	default:	goto yy3;
	}
yy5:
	{}
yy6:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case ';':	goto yy16;
	case '=':	goto yy18;
	default:	goto yy8;
	}
yy8:
	{}
yy9:
	++YYCURSOR;
yy10:
	{}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy9;
	default:	goto yy10;
	}
yy12:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case ' ':	goto yy12;
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy5;
	case ';':	goto yy16;
	case '=':	goto yy18;
	case '[':	goto yy28;
	default:	goto yy3;
	}
yy14:
	++YYCURSOR;
	{}
yy16:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy31;
	case '\r':	goto yy33;
	default:	goto yy16;
	}
yy18:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy18;
	default:	goto yy20;
	}
yy20:
	{}
yy21:
	++YYCURSOR;
	{}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy34;
	default:	goto yy4;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy35;
	case 'u':	goto yy37;
	default:	goto yy4;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy38;
	case 'n':	goto yy39;
	default:	goto yy4;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy42;
	default:	goto yy4;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy43;
	default:	goto yy4;
	}
yy28:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy28;
	default:	goto yy30;
	}
yy30:
	{}
yy31:
	++YYCURSOR;
yy32:
	{}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy31;
	default:	goto yy32;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy44;
	default:	goto yy4;
	}
yy35:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\t':	goto yy45;
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy36;
	case ' ':	goto yy47;
	case 'n':	goto yy49;
	default:	goto yy4;
	}
yy36:
	{}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy50;
	default:	goto yy4;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy47;
	default:	goto yy4;
	}
yy39:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy51;
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy41;
	case ' ':	goto yy39;
	case '[':	goto yy28;
	default:	goto yy3;
	}
yy41:
	{}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy53;
	default:	goto yy4;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy39;
	default:	goto yy4;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy49;
	default:	goto yy4;
	}
yy45:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy45;
	default:	goto yy36;
	}
yy47:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy45;
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy36;
	case ' ':	goto yy47;
	case '[':	goto yy28;
	default:	goto yy3;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy47;
	default:	goto yy4;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy54;
	default:	goto yy4;
	}
yy51:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy51;
	default:	goto yy41;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy39;
	default:	goto yy4;
	}
yy54:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy57;
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy56;
	case ' ':	goto yy54;
	case '[':	goto yy28;
	default:	goto yy3;
	}
yy56:
	{}
yy57:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy57;
	default:	goto yy56;
	}
/* *********************************** */
yyc_ST_DOUBLE_QUOTES:
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy63;
	case '$':	goto yy66;
	default:	goto yy61;
	}
yy61:
	++YYCURSOR;
yy62:
	{}
yy63:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy63;
	default:	goto yy65;
	}
yy65:
	{}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case '{':	goto yy67;
	default:	goto yy62;
	}
yy67:
	++YYCURSOR;
	{}
/* *********************************** */
yyc_ST_OFFSET:
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy74;
	case '\n':
	case '\r':
	case ';':	goto yy76;
	case '"':	goto yy78;
	case '$':	goto yy80;
	case '\'':	goto yy81;
	case '-':
	case '.':	goto yy82;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy83;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy86;
	case '\\':	goto yy89;
	case ']':	goto yy90;
	default:	goto yy71;
	}
yy71:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
yy72:
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy73;
	case '$':	goto yy92;
	case '\\':	goto yy89;
	default:	goto yy71;
	}
yy73:
	{}
yy74:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy74;
	case '\n':
	case '\r':
	case '\'':
	case ';':	goto yy73;
	case '"':	goto yy78;
	case '$':	goto yy92;
	case '\\':	goto yy89;
	case ']':	goto yy90;
	default:	goto yy71;
	}
yy76:
	++YYCURSOR;
yy77:
	{}
yy78:
	++YYCURSOR;
	{}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy77;
	case '\\':	goto yy94;
	case '{':	goto yy96;
	default:	goto yy71;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy77;
	default:	goto yy98;
	}
yy82:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy100;
	default:	goto yy72;
	}
yy83:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy85;
	case '$':	goto yy92;
	case '.':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy83;
	case '\\':	goto yy89;
	default:	goto yy71;
	}
yy85:
	{}
yy86:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy88;
	case '$':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy86;
	case '\\':	goto yy89;
	default:	goto yy71;
	}
yy88:
	{}
yy89:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	goto yy71;
yy90:
	++YYCURSOR;
	{}
yy92:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '{':	goto yy93;
	case '\\':	goto yy94;
	default:	goto yy71;
	}
yy93:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy73;
	case 1: 	goto yy85;
	default:	goto yy88;
	}
yy94:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case '\\':	goto yy94;
	default:	goto yy71;
	}
yy96:
	++YYCURSOR;
	{}
yy98:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy102;
	default:	goto yy98;
	}
yy100:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy85;
	case '$':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy100;
	case '\\':	goto yy89;
	default:	goto yy71;
	}
yy102:
	++YYCURSOR;
	{}
/* *********************************** */
yyc_ST_RAW:
	YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy106;
	case '\t':
	case ' ':	goto yy110;
	case '\n':	goto yy111;
	case '\r':	goto yy113;
	case ';':	goto yy114;
	default:	goto yy108;
	}
yy106:
	++YYCURSOR;
	{}
yy108:
	++YYCURSOR;
yy109:
	{}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case ';':	goto yy117;
	default:	goto yy109;
	}
yy111:
	++YYCURSOR;
yy112:
	{}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy111;
	default:	goto yy112;
	}
yy114:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy119;
	case '\r':	goto yy121;
	default:	goto yy114;
	}
yy116:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
yy117:
	switch (yych) {
	case '\t':
	case ' ':	goto yy116;
	case '\n':	goto yy111;
	case '\r':	goto yy113;
	case ';':	goto yy114;
	default:	goto yy118;
	}
yy118:
	{}
yy119:
	++YYCURSOR;
yy120:
	{}
yy121:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy119;
	default:	goto yy120;
	}
/* *********************************** */
yyc_ST_SECTION_RAW:
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':	goto yy127;
	case ']':	goto yy129;
	default:	goto yy124;
	}
yy124:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case ']':	goto yy126;
	default:	goto yy124;
	}
yy126:
	{}
yy127:
	++YYCURSOR;
	{}
yy129:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy129;
	case '\n':	goto yy132;
	case '\r':	goto yy133;
	default:	goto yy131;
	}
yy131:
	{}
yy132:
	++YYCURSOR;
	goto yy131;
yy133:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy132;
	default:	goto yy131;
	}
/* *********************************** */
yyc_ST_SECTION_VALUE:
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy139;
	case '\n':
	case '\r':
	case ';':	goto yy141;
	case '"':	goto yy143;
	case '$':	goto yy145;
	case '\'':	goto yy146;
	case '-':
	case '.':	goto yy147;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy148;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy151;
	case '\\':	goto yy154;
	case ']':	goto yy155;
	default:	goto yy136;
	}
yy136:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
yy137:
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy138;
	case '$':	goto yy158;
	case '\\':	goto yy154;
	default:	goto yy136;
	}
yy138:
	{}
yy139:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy139;
	case '\n':
	case '\r':
	case '\'':
	case ';':
	case ']':	goto yy138;
	case '"':	goto yy143;
	case '$':	goto yy158;
	case '\\':	goto yy154;
	default:	goto yy136;
	}
yy141:
	++YYCURSOR;
yy142:
	{}
yy143:
	++YYCURSOR;
	{}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy142;
	case '\\':	goto yy160;
	case '{':	goto yy162;
	default:	goto yy136;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy142;
	default:	goto yy164;
	}
yy147:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy166;
	default:	goto yy137;
	}
yy148:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy150;
	case '$':	goto yy158;
	case '.':	goto yy166;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy148;
	case '\\':	goto yy154;
	default:	goto yy136;
	}
yy150:
	{}
yy151:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy153;
	case '$':	goto yy158;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy151;
	case '\\':	goto yy154;
	default:	goto yy136;
	}
yy153:
	{}
yy154:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	goto yy136;
yy155:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy155;
	case '\n':	goto yy168;
	case '\r':	goto yy169;
	default:	goto yy157;
	}
yy157:
	{}
yy158:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '{':	goto yy159;
	case '\\':	goto yy160;
	default:	goto yy136;
	}
yy159:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy138;
	case 1: 	goto yy150;
	default:	goto yy153;
	}
yy160:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case '\\':	goto yy160;
	default:	goto yy136;
	}
yy162:
	++YYCURSOR;
	{}
yy164:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy170;
	default:	goto yy164;
	}
yy166:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':
	case '\r':
	case '"':
	case '\'':
	case ';':
	case ']':	goto yy150;
	case '$':	goto yy158;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy166;
	case '\\':	goto yy154;
	default:	goto yy136;
	}
yy168:
	++YYCURSOR;
	goto yy157;
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy168;
	default:	goto yy157;
	}
yy170:
	++YYCURSOR;
	{}
/* *********************************** */
yyc_ST_VALUE:
	YYFILL(6);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy174;
	case '\t':
	case ' ':	goto yy179;
	case '\n':	goto yy182;
	case '\r':	goto yy184;
	case '!':
	case '&':
	case '(':
	case ')':
	case '^':
	case '|':
	case '~':	goto yy185;
	case '"':	goto yy188;
	case '$':	goto yy190;
	case '\'':	goto yy191;
	case '-':
	case '.':	goto yy192;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy193;
	case ';':	goto yy196;
	case '=':	goto yy198;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'z':	goto yy200;
	case 'f':	goto yy203;
	case 'n':	goto yy204;
	case 'o':	goto yy205;
	case 't':	goto yy206;
	case 'y':	goto yy207;
	default:	goto yy176;
	}
yy174:
	++YYCURSOR;
yy175:
	{}
yy176:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
yy177:
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy178;
	case '$':	goto yy208;
	default:	goto yy176;
	}
yy178:
	{}
yy179:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy179;
	case '\n':	goto yy182;
	case '\r':	goto yy184;
	case '"':	goto yy188;
	case ';':	goto yy196;
	default:	goto yy181;
	}
yy181:
	{}
yy182:
	++YYCURSOR;
yy183:
	{}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy182;
	default:	goto yy183;
	}
yy185:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy185;
	default:	goto yy187;
	}
yy187:
	{}
yy188:
	++YYCURSOR;
	{}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy175;
	case '\\':	goto yy210;
	case '{':	goto yy211;
	default:	goto yy176;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy175;
	default:	goto yy213;
	}
yy192:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy215;
	default:	goto yy177;
	}
yy193:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy195;
	case '$':	goto yy208;
	case '.':	goto yy215;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy193;
	default:	goto yy176;
	}
yy195:
	{}
yy196:
	++YYCURSOR;
	YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy217;
	case '\r':	goto yy219;
	default:	goto yy196;
	}
yy198:
	++YYCURSOR;
	{}
yy200:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '$':	goto yy208;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	default:	goto yy176;
	}
yy202:
	{}
yy203:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'a':	goto yy220;
	default:	goto yy177;
	}
yy204:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'o':	goto yy221;
	case 'u':	goto yy223;
	default:	goto yy177;
	}
yy205:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'f':	goto yy224;
	case 'n':	goto yy225;
	default:	goto yy177;
	}
yy206:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'r':	goto yy227;
	default:	goto yy177;
	}
yy207:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'e':	goto yy228;
	default:	goto yy177;
	}
yy208:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '{':	goto yy209;
	case '\\':	goto yy210;
	default:	goto yy176;
	}
yy209:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy178;
	case 1: 	goto yy195;
	case 2: 	goto yy202;
	case 3: 	goto yy222;
	case 4: 	goto yy226;
	default:	goto yy243;
	}
yy210:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '$':	goto yy229;
	default:	goto yy176;
	}
yy211:
	++YYCURSOR;
	{}
yy213:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy231;
	default:	goto yy213;
	}
yy215:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy195;
	case '$':	goto yy208;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy215;
	default:	goto yy176;
	}
yy217:
	++YYCURSOR;
yy218:
	{}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy217;
	default:	goto yy218;
	}
yy220:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'l':	goto yy233;
	default:	goto yy177;
	}
yy221:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy222;
	case '\t':
	case ' ':	goto yy234;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'n':	goto yy236;
	default:	goto yy177;
	}
yy222:
	{}
yy223:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'l':	goto yy237;
	default:	goto yy177;
	}
yy224:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'f':	goto yy238;
	default:	goto yy177;
	}
yy225:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy226;
	case '\t':
	case ' ':	goto yy239;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	default:	goto yy177;
	}
yy226:
	{}
yy227:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'u':	goto yy241;
	default:	goto yy177;
	}
yy228:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 's':	goto yy225;
	default:	goto yy177;
	}
yy229:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy178;
	case '$':	goto yy229;
	case '\\':	goto yy210;
	default:	goto yy176;
	}
yy231:
	++YYCURSOR;
	{}
yy233:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 's':	goto yy236;
	default:	goto yy177;
	}
yy234:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy234;
	default:	goto yy222;
	}
yy236:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'e':	goto yy238;
	default:	goto yy177;
	}
yy237:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'l':	goto yy242;
	default:	goto yy177;
	}
yy238:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy222;
	case '\t':
	case ' ':	goto yy234;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	default:	goto yy177;
	}
yy239:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy239;
	default:	goto yy226;
	}
yy241:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy202;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	case 'e':	goto yy225;
	default:	goto yy177;
	}
yy242:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '&':
	case '\'':
	case '(':
	case ')':
	case ';':
	case '=':
	case '^':
	case '|':
	case '~':	goto yy243;
	case '\t':
	case ' ':	goto yy244;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy200;
	default:	goto yy177;
	}
yy243:
	{}
yy244:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy244;
	default:	goto yy243;
	}
/* *********************************** */
yyc_ST_VARNAME:
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '[':
	case '^':
	case '{':
	case '|':
	case '~':	goto yy251;
	case '}':	goto yy253;
	default:	goto yy248;
	}
yy248:
	++YYCURSOR;
	YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case '!':
	case '"':
	case '$':
	case '&':
	case '(':
	case ')':
	case ';':
	case '=':
	case '[':
	case '^':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy250;
	default:	goto yy248;
	}
yy250:
	{}
yy251:
	++YYCURSOR;
	{}
yy253:
	++YYCURSOR;
	{}
}

re2c: warning: line 4: column 13: escape has no effect: '\.' [-Wuseless-escape]
re2c: warning: line 4: column 32: escape has no effect: '\.' [-Wuseless-escape]
re2c: warning: line 11: column 27: escape has no effect: '\[' [-Wuseless-escape]
re2c: warning: line 12: column 11: escape has no effect: '\[' [-Wuseless-escape]
re2c: warning: line 55: unreachable rule in condition 'INITIAL' (shadowed by rules at lines 24, 35, 36, 42, 51, 52, 53) [-Wunreachable-rules]
re2c: warning: line 55: unreachable rule in condition 'ST_DOUBLE_QUOTES' (shadowed by rules at lines 48, 49) [-Wunreachable-rules]
re2c: warning: line 50: unreachable rule in condition 'ST_OFFSET' (shadowed by rule at line 46) [-Wunreachable-rules]
re2c: warning: line 55: unreachable rule in condition 'ST_RAW' (shadowed by rules at lines 37, 39, 54) [-Wunreachable-rules]
re2c: warning: line 50: unreachable rule in condition 'ST_SECTION_VALUE' (shadowed by rule at line 46) [-Wunreachable-rules]
re2c: warning: line 55: unreachable rule in condition 'ST_VALUE' (shadowed by rules at lines 39, 40, 41, 43, 44, 45, 47, 50, 54) [-Wunreachable-rules]
