/* Generated by re2c */
#line 1 "range_neg_lf.e.re"

#line 5 "range_neg_lf.e.c"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x25:	goto yy2;
	default:	goto yy3;
	}
yy2:
yy3:
	++YYCURSOR;
#line 2 "range_neg_lf.e.re"
	{return 0;}
#line 19 "range_neg_lf.e.c"
}
#line 3 "range_neg_lf.e.re"

re2c: warning: line 3: control flow is undefined for strings that match '\x25', use default rule '*' [-Wundefined-control-flow]
