/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i



{
	YYCTYPE yych;
yyFillLabel0:
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy4;
	default:
		if (YYLIMIT <= YYCURSOR) {
			if (fill() == 0) goto yyFillLabel0;
			goto yy6;
		}
		goto yy2;
	}
yy2:
	++YYCURSOR;
	{ return FAIL; }
yy4:
	++YYCURSOR;
	{ return OK; }
yy6:
	{ return EOF; }
}



{
	YYCTYPE yych;
yyFillLabel1:
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy11;
	default:
		if (YYLIMIT <= YYCURSOR) {
			if (fill() == 0) goto yyFillLabel1;
			goto yy13;
		}
		goto yy9;
	}
yy9:
	++YYCURSOR;
	{ return FAIL; }
yy11:
	++YYCURSOR;
	{ return OK; }
yy13:
	{ return EOF; }
}



{
	YYCTYPE yych;
yyFillLabel2:
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy18;
	default:
		if (YYLIMIT <= YYCURSOR) {
			if (fill() == 0) goto yyFillLabel2;
			goto yy20;
		}
		goto yy16;
	}
yy16:
	++YYCURSOR;
	{ return FAIL; }
yy18:
	++YYCURSOR;
	{ return OK; }
yy20:
	{ return EOF; }
}



{
	YYCTYPE yych;
yyFillLabel3:
	yych = *YYCURSOR;
	switch (yych) {
	case 'a':	goto yy25;
	default:
		if (YYLIMIT <= YYCURSOR) {
			if (fill() == 0) goto yyFillLabel3;
			goto yy27;
		}
		goto yy23;
	}
yy23:
	++YYCURSOR;
	{ return FAIL; }
yy25:
	++YYCURSOR;
	{ return OK; }
yy27:
	{ return EOF; }
}

