eof/sentinel_01.re:8:8: warning: sentinel symbol 0 occurs in the middle of the rule (note: if a different sentinel symbol is used, specify it with 're2c:sentinel' configuration) [-Wsentinel-in-midrule]
eof/sentinel_01.re:14:8: error: sentinel symbol 0 occurs in the middle of the rule [-Werror-sentinel-in-midrule]
eof/sentinel_01.re:20:8: warning: sentinel symbol 0 occurs in the middle of the rule (note: if a different sentinel symbol is used, specify it with 're2c:sentinel' configuration) [-Wsentinel-in-midrule]
eof/sentinel_01.re:26:8: error: sentinel symbol 39 occurs in the middle of the rule [-Werror-sentinel-in-midrule]
eof/sentinel_01.re:38:8: error: sentinel symbol 255 occurs in the middle of the rule [-Werror-sentinel-in-midrule]
