/* Generated by re2c */
#line 1 "header/header_03.--type-header(header_03.h).re"
// re2c $INPUT -o $OUTPUT  --type-header header_03.h
#line 2 "header/header_03.--type-header(header_03.h).re"


#line 7 "header/header_03.--type-header(header_03.h).re"


#include "header_03.h"

void lex(const YYCTYPE *YYCURSOR)
{
    
#line 16 "header/header_03.--type-header(header_03.h).c"
{
	YYCTYPE yych;
	yych = *YYCURSOR++;
#line 15 "header/header_03.--type-header(header_03.h).re"
	{ return; }
#line 22 "header/header_03.--type-header(header_03.h).c"
}
#line 16 "header/header_03.--type-header(header_03.h).re"

}
/* Generated by re2c */

#define YYCTYPE char
void lex(const YYCTYPE *);
