// Code generated by re2c, DO NOT EDIT.
//line "golang/004_yyaccept.re":1
//go:generate re2go $INPUT -o $OUTPUT 
package main

func Lex(str string) int {
	var cursor, marker int

	
//line "golang/004_yyaccept.go":11
{
	var yych byte
	yyaccept := 0
	yych = str[cursor]
	switch (yych) {
	case 'a':
		goto yy4
	default:
		goto yy2
	}
yy2:
	cursor += 1
//line "golang/004_yyaccept.re":17
	{
		return -1
	}
//line "golang/004_yyaccept.go":28
yy4:
	yyaccept = 0
	cursor += 1
	marker = cursor
	yych = str[cursor]
	switch (yych) {
	case 'b':
		goto yy6
	default:
		goto yy5
	}
yy5:
//line "golang/004_yyaccept.re":21
	{
		return 1
	}
//line "golang/004_yyaccept.go":45
yy6:
	cursor += 1
	yych = str[cursor]
	switch (yych) {
	case 'c':
		goto yy8
	default:
		goto yy7
	}
yy7:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy5
	case 1:
		goto yy9
	default:
		goto yy12
	}
yy8:
	yyaccept = 1
	cursor += 1
	marker = cursor
	yych = str[cursor]
	switch (yych) {
	case 'd':
		goto yy10
	default:
		goto yy9
	}
yy9:
//line "golang/004_yyaccept.re":25
	{
		return 2
	}
//line "golang/004_yyaccept.go":81
yy10:
	cursor += 1
	yych = str[cursor]
	switch (yych) {
	case 'e':
		goto yy11
	default:
		goto yy7
	}
yy11:
	yyaccept = 2
	cursor += 1
	marker = cursor
	yych = str[cursor]
	switch (yych) {
	case 'f':
		goto yy13
	default:
		goto yy12
	}
yy12:
//line "golang/004_yyaccept.re":29
	{
		return 3
	}
//line "golang/004_yyaccept.go":107
yy13:
	cursor += 1
	yych = str[cursor]
	switch (yych) {
	case 'g':
		goto yy14
	default:
		goto yy7
	}
yy14:
	cursor += 1
//line "golang/004_yyaccept.re":33
	{
		return 4
	}
//line "golang/004_yyaccept.go":123
}
//line "golang/004_yyaccept.re":36

}

func main() {
	if Lex("\000") != -1 {
		panic("expected error")
	}
	if Lex("a\000") != 1 {
		panic("expected 'a'")
	}
	if Lex("abc\000") != 2 {
		panic("expected 'abc'")
	}
	if Lex("abcde\000") != 3 {
		panic("expected 'abcde'")
	}
	if Lex("abcdefg\000") != 4 {
		panic("expected 'abcdefg'")
	}
}
