/* Generated by re2c */
#line 1 "encodings/range_empty_8.re"
// re2c $INPUT -o $OUTPUT -8

#line 6 "encodings/range_empty_8.c"
{
	YYCTYPE yych;
#line 3 "encodings/range_empty_8.re"
	{return 0;}
#line 11 "encodings/range_empty_8.c"
}
#line 4 "encodings/range_empty_8.re"

encodings/range_empty_8.re:3:1: warning: empty character class [-Wempty-character-class]
