/* Generated by re2c */
#line 1 "encodings/unicode_group_Pi_8_encoding_policy_substitute.re"
// re2c $INPUT -o $OUTPUT -8 --encoding-policy substitute
#include <stdint.h>
#include <stdio.h>
#include "utf8.h"
#define YYCTYPE uint8_t

bool scan(const YYCTYPE* start, const YYCTYPE* const limit) {
	__attribute__((unused)) const YYCTYPE* YYMARKER;
#define YYCURSOR start
Pi:

#line 15 "encodings/unicode_group_Pi_8_encoding_policy_substitute.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0xC2: goto yy3;
		case 0xE2: goto yy4;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 15 "encodings/unicode_group_Pi_8_encoding_policy_substitute.re"
	{ return YYCURSOR - 1 == limit; }
#line 29 "encodings/unicode_group_Pi_8_encoding_policy_substitute.c"
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0xAB: goto yy5;
		default: goto yy2;
	}
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x80: goto yy6;
		case 0xB8: goto yy8;
		default: goto yy2;
	}
yy5:
	++YYCURSOR;
#line 14 "encodings/unicode_group_Pi_8_encoding_policy_substitute.re"
	{ goto Pi; }
#line 47 "encodings/unicode_group_Pi_8_encoding_policy_substitute.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x98:
		case 0x9B:
		case 0x9C:
		case 0x9F:
		case 0xB9: goto yy5;
		default: goto yy7;
	}
yy7:
	YYCURSOR = YYMARKER;
	goto yy2;
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x82:
		case 0x84:
		case 0x89:
		case 0x8C:
		case 0x9C:
		case 0xA0: goto yy5;
		default: goto yy7;
	}
}
#line 16 "encodings/unicode_group_Pi_8_encoding_policy_substitute.re"

}

static const uint32_t chars_Pi[] = {0xab,0xab,0x2018,0x2018,0x201b,0x201c,0x201f,0x201f,0x2039,0x2039,0x2e02,0x2e02,0x2e04,0x2e04,0x2e09,0x2e09,0x2e0c,0x2e0c,0x2e1c,0x2e1c,0x2e20,0x2e20,};

static uint32_t encode_utf8(const uint32_t* ranges, uint32_t ranges_count, uint8_t* s) {
	uint8_t* const s0 = s;
	for (uint32_t i = 0; i < ranges_count; i += 2)
		for (uint32_t j = ranges[i]; j <= ranges[i + 1]; ++j) s += re2c::utf8::rune_to_bytes(s, j);
	for (uint32_t i = 0; i < 6; ++i) s[i] = 0;
	return s - s0;
}

int main() {
	YYCTYPE* buffer_Pi = new YYCTYPE[78];
	uint32_t buffer_Pi_len = encode_utf8(chars_Pi, sizeof(chars_Pi) / sizeof(uint32_t), buffer_Pi);
	if (!scan(buffer_Pi, buffer_Pi + buffer_Pi_len)) printf("test 'Pi' failed\n");
	delete[] buffer_Pi;
	return 0;
}
