/* Generated by re2c */

{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case 'X':
		yyt2 = YYCURSOR;
		goto yy3;
	default:	goto yy2;
	}
yy2:
	{
		const size_t yynmatch = 1;
		const YYCTYPE *yypmatch[yynmatch * 2];
		yypmatch[0] = YYCURSOR;
		yypmatch[1] = YYCURSOR;
		{}
	}
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
		yyt1 = yyt3 = YYCURSOR;
		goto yy7;
	default:	goto yy6;
	}
yy4:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy2;
	} else {
		goto yy8;
	}
yy5:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy6:
	switch (yych) {
	case 0x00:	goto yy4;
	case 'Y':
		yyt3 = YYCURSOR;
		goto yy9;
	default:
		yyt1 = YYCURSOR;
		goto yy5;
	}
yy7:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'Y':
		yyt3 = YYCURSOR;
		goto yy9;
	default:	goto yy10;
	}
yy8:
	{
		const size_t yynmatch = 2;
		const YYCTYPE *yypmatch[yynmatch * 2];
		yypmatch[0] = yyt2;
		yypmatch[3] = yyt3;
		yypmatch[1] = YYCURSOR;
		yypmatch[2] = yyt4;
		{}
	}
yy9:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy10:
	switch (yych) {
	case 0x00:
		yyt4 = yyt1;
		goto yy8;
	case 'Y':
		yyt1 = yyt3;
		yyt3 = YYCURSOR;
		goto yy9;
	default:
		yyt4 = yyt1;
		yyt1 = YYCURSOR;
		goto yy5;
	}
}

re2c: warning: line 6: rule matches empty string [-Wmatch-empty-string]
re2c: warning: line 5: trailing context is non-deterministic and induces 2 parallel instances [-Wnondeterministic-tags]
re2c: warning: line 5: trailing context is non-deterministic and induces 2 parallel instances [-Wnondeterministic-tags]
